<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.557">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>An Introduction to Quantitative Text Analysis for Linguistics - 6&nbsp; Curate</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../part_3/7_transform.html" rel="next">
<link href="../part_3/5_acquire.html" rel="prev">
<link href="../assets/images/logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><script data-goatcounter="https://italicize.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script><link rel="stylesheet" href="../assets/css/mini.css">
<meta property="og:title" content="An Introduction to Quantitative Text Analysis for Linguistics - 6&nbsp; Curate">
<meta property="og:description" content="">
<meta property="og:site_name" content="An Introduction to Quantitative Text Analysis for Linguistics">
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span id="sec-curate-chapter" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Curate</span></span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">An Introduction to Quantitative Text Analysis for Linguistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/qtalr/book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../qtalr-manuscript.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_0/preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part_1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Orientation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_1/1_text.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Text analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part_2/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_2/2_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_2/3_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_2/4_research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Research</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part_3/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preparation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_3/5_acquire.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Acquire</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_3/6_curate.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Curate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_3/7_transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Transform</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part_4/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_4/8_explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Explore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_4/9_predict.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Predict</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_4/10_infer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part_5/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Communication</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_5/11_contribute.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Contribute</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Contents</h2>
   
  <ul>
<li>
<a href="#sec-unstructured" id="toc-sec-unstructured" class="nav-link active" data-scroll-target="#sec-unstructured"><span class="header-section-number">6.1</span> Unstructured</a>
  <ul class="collapse">
<li><a href="#reading-data" id="toc-reading-data" class="nav-link" data-scroll-target="#reading-data">Reading data</a></li>
  <li><a href="#orientation" id="toc-orientation" class="nav-link" data-scroll-target="#orientation">Orientation</a></li>
  <li><a href="#tidy-the-data" id="toc-tidy-the-data" class="nav-link" data-scroll-target="#tidy-the-data">Tidy the data</a></li>
  </ul>
</li>
  <li>
<a href="#structured" id="toc-structured" class="nav-link" data-scroll-target="#structured"><span class="header-section-number">6.2</span> Structured</a>
  <ul class="collapse">
<li><a href="#reading-datasets" id="toc-reading-datasets" class="nav-link" data-scroll-target="#reading-datasets">Reading datasets</a></li>
  <li><a href="#orientation-1" id="toc-orientation-1" class="nav-link" data-scroll-target="#orientation-1">Orientation</a></li>
  <li><a href="#tidy-the-dataset" id="toc-tidy-the-dataset" class="nav-link" data-scroll-target="#tidy-the-dataset">Tidy the dataset</a></li>
  </ul>
</li>
  <li>
<a href="#semi-structured" id="toc-semi-structured" class="nav-link" data-scroll-target="#semi-structured"><span class="header-section-number">6.3</span> Semi-structured</a>
  <ul class="collapse">
<li><a href="#reading-data-1" id="toc-reading-data-1" class="nav-link" data-scroll-target="#reading-data-1">Reading data</a></li>
  <li><a href="#sec-curate-semi-structured-orientation" id="toc-sec-curate-semi-structured-orientation" class="nav-link" data-scroll-target="#sec-curate-semi-structured-orientation">Orientation</a></li>
  <li><a href="#tidy-the-data-1" id="toc-tidy-the-data-1" class="nav-link" data-scroll-target="#tidy-the-data-1">Tidy the data</a></li>
  </ul>
</li>
  <li><a href="#documentation" id="toc-documentation" class="nav-link" data-scroll-target="#documentation"><span class="header-section-number">6.4</span> Documentation</a></li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/qtalr/book/blob/main/part_3/6_curate.qmd" target="_blank" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/qtalr/book/edit/main/part_3/6_curate.qmd" target="_blank" class="toc-action"><i class="bi empty"></i>Edit this page</a></li><li><a href="https://github.com/qtalr/book/issues" target="_blank" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title d-none d-lg-block"><span id="sec-curate-chapter" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Curate</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><!-- Data Curation in Text Analysis: Strategies for Structuring and Documenting Datasets --><div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-list-alt" aria-label="list-alt"></i> Outcomes</strong></p>
<ul>
<li>Describe the importance of data curation in text analysis</li>
<li>Recognize the different types of data formats</li>
<li>Associate the types data formats with the appropriate R programming techniques to curate the data</li>
</ul>
</div>
</div>
</div>
<p>In this chapter, we will now look at the next step in a text analysis project: data curation. That is, the process of converting the original data we acquire to a tidy dataset. Acquired data can come in a wide variety of formats. These formats tend to signal the richness of the metadata that is included in the file content. We will consider three general types of content formats: (1) unstructured data, (2) structured data, and (3) semi-structured data. Regardless of the file type and the structure of the data, it will be necessary to consider how to curate a dataset that such that the structure reflects the basic the unit of analysis that we wish to investigate. The resulting dataset will form the base from which we will work to further transform the dataset such that it aligns with the unit(s) of observation required for the analysis method that we will implement. Once the dataset is curated, we will create a data dictionary that describes the dataset and the variables that are included in the dataset for transparency and reproducibility.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-terminal" aria-label="terminal"></i> Lessons</strong></p>
<p><strong>What</strong>: Pattern Matching, Tidy Datasets<br><strong>How</strong>: In an R console, load {swirl}, run <code>swirl()</code>, and follow prompts to select the lesson.<br><strong>Why</strong>: To familiarize yourself with the basics of using the pattern matching syntax Regular Expressions and the {dplyr} package to manipulate data into Tidy datasets.</p>
</div>
</div>
</div>
<section id="sec-unstructured" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="sec-unstructured">
<span class="header-section-number">6.1</span> Unstructured</h2>
<p>The bulk of text ever created is of the unstructured variety. Unstructured data is data that has not been organized to make the information contained within machine-readable. Remember that text in itself is not information. Only when given explicit context does text become informative. The explicit contextual information that is included with data is called metadata. Metadata can be linguistic or non-linguistic in nature. So for unstructured data there is little to no metadata directly associated with the data.</p>
<section id="reading-data" class="level3"><h3 class="anchored" data-anchor-id="reading-data">Reading data</h3>
<p>Some of the common file formats which contain unstructured data include TXT, PDF, and DOCX. Although these formats are unstructured, they are not the same. Reading these files into R requires different techniques and tools.</p>
<p>There are many ways to read TXT files into R and many packages that can be used to do so. For example, using {readr}, we can choose to read the entire file into a single vector of character strings with <code>read_file()</code> or read the file by lines with <code>read_lines()</code> in which each line is a character string in a vector.</p>
<p>Less commonly used in prepared data resources, PDF and DOCX files are more complex than TXT files as they contain formatting and embedded document metadata. However, these attributes are primarily for visual presentation and not for machine-readability. Needless to say, we need an alternate strategy to extract the text content from these files and potentially some of the metadata. For example, using {readtext} <span class="citation" data-cites="R-readtext">(<a href="../references.html#ref-R-readtext" role="doc-biblioref">Benoit &amp; Obeng, 2024</a>)</span>, we can read the text content from PDF and DOCX files into a single vector of character strings with <code>readtext()</code>.</p>
<p>Whether in TXT, PDF, or DOCX format, the resulting data structure will require further processing to convert the data into a tidy dataset.</p>
</section><section id="orientation" class="level3"><h3 class="anchored" data-anchor-id="orientation">Orientation</h3>
<p>As an example of curating an unstructured source of corpus data, let’s take a look at the <a href="https://www.statmt.org/europarl/">Europarl Parallel Corpus</a> <span class="citation" data-cites="Koehn2005">(<a href="../references.html#ref-Koehn2005" role="doc-biblioref">Koehn, 2005</a>)</span>. This corpus contains parallel texts (source and translated documents) from the European Parliamentary proceedings between 1996-2011 for some 21 European languages.</p>
<p>Let’s assume we selected this corpus because we are interested in researching Spanish to English translations. After consulting the corpus website, downloading the archive file, and inspecting the unarchived structure, we have the the file structure seen in <a href="#def-curate-europarl-file-structure" class="quarto-xref">Snippet&nbsp;<span>6.1</span></a>.</p>
<div id="def-curate-europarl-file-structure" class="theorem definition">
<p><span class="theorem-title"><strong>Snippet 6.1</strong></span> Project directory structure for the Europarl Parallel Corpus</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">project/</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">├──</span> process/</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">│</span>   ├── 1-acquire-data.qmd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="ex">│</span>   ├── 2-curate-data.qmd</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ex">│</span>   └── ...</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="ex">├──</span> data/</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="ex">│</span>   ├── analysis/</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="ex">│</span>   ├── derived/</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="ex">│</span>   └── original/</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="ex">│</span>       │── europarl_do.csv</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="ex">│</span>       └── europarl/</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="ex">│</span>           ├── europarl-v7.es-en.en</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="ex">│</span>           └── europarl-v7.es-en.es</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="ex">├──</span> reports/</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="ex">├──</span> DESCRIPTION</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="ex">├──</span> Makefile</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="ex">└──</span> README</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <em>europarl_do.csv</em> file contains the data origin information documented as part of the acquisition process. The contents are seen in <a href="#tbl-curate-europarl-data-origin" class="quarto-xref">Table&nbsp;<span>6.1</span></a>.</p>
<div class="cell" data-tbl-colwidths="[25,75]">
<div id="tbl-curate-europarl-data-origin" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-curate-europarl-data-origin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Data origin: Europarl Corpus
</figcaption><div aria-describedby="tbl-curate-europarl-data-origin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead><tr class="header">
<th>attribute</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Resource name</td>
<td>Europarl Parallel Corpus</td>
</tr>
<tr class="even">
<td>Data source</td>
<td><a href="https://www.statmt.org/europarl/" class="uri">https://www.statmt.org/europarl/</a></td>
</tr>
<tr class="odd">
<td>Data sampling frame</td>
<td>Spanish transcripts from the European Parliament proceedings</td>
</tr>
<tr class="even">
<td>Data collection date(s)</td>
<td>1996-2011</td>
</tr>
<tr class="odd">
<td>Data format</td>
<td>TXT files with ‘.es’ for source (Spanish) and ‘.en’ for target (English) files.</td>
</tr>
<tr class="even">
<td>Data schema</td>
<td>Line-by-line unannotated parallel text</td>
</tr>
<tr class="odd">
<td>License</td>
<td>See: <a href="https://www.europarl.europa.eu/legal-notice/en/" class="uri">https://www.europarl.europa.eu/legal-notice/en/</a>
</td>
</tr>
<tr class="even">
<td>Attribution</td>
<td>Please cite the paper: Koehn, P. 2005. ‘Europarl: A Parallel Corpus for Statistical Machine Translation.’ MT Summit X, 12-16.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Now let’s get familiar with the corpus directory structure and the files. In <a href="#def-curate-europarl-file-structure" class="quarto-xref">Snippet&nbsp;<span>6.1</span></a>, we see that there are two corpus files, <em>europarl-v7.es-en.es</em> and <em>europarl-v7.es-en.en</em>, that contain the source and target language texts, respectively. The file names indicate that the files contain Spanish-English parallel texts. The <em>.es</em> and <em>.en</em> extensions indicate the language of the text.</p>
<p>Looking at the beginning of the <em>.es</em> and <em>.en</em> files, in <a href="#def-curate-europarl-es" class="quarto-xref">Snippet&nbsp;<span>6.2</span></a> and <a href="#def-curate-europarl-en" class="quarto-xref">Snippet&nbsp;<span>6.3</span></a>, we see that the files contain a series of lines in either the source or target language.</p>
<div id="def-curate-europarl-es" class="theorem definition">
<p><span class="theorem-title"><strong>Snippet 6.2</strong></span> <em>europarl-v7.es-en.es</em> file</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode xml code-with-copy"><code class="sourceCode xml"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Reanudación del período de sesiones</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>Declaro reanudado el período de sesiones del Parlamento Europeo, interrumpido el viernes 17 de diciembre pasado, y reitero a Sus Señorías mi deseo de que hayan tenido unas buenas vacaciones.</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>Como todos han podido comprobar, el gran "efecto del año 2000" no se ha producido. En cambio, los ciudadanos de varios de nuestros países han sido víctimas de catástrofes naturales verdaderamente terribles.</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>Sus Señorías han solicitado un debate sobre el tema para los próximos días, en el curso de este período de sesiones.</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>A la espera de que se produzca, de acuerdo con muchos colegas que me lo han pedido, pido que hagamos un minuto de silencio en memoria de todas las víctimas de las tormentas, en los distintos países de la Unión Europea afectados.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can clearly appreciate that the data is unstructured. That is, there is no explicit metadata associated with the data. The data is just a series of character strings separated by lines. The only information that we can surmise from structure of the data is that the texts are line-aligned and that the data in each file corresponds to source and target languages.</p>
<div id="def-curate-europarl-en" class="theorem definition">
<p><span class="theorem-title"><strong>Snippet 6.3</strong></span> <em>europarl-v7.es-en.en</em></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode xml code-with-copy"><code class="sourceCode xml"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Resumption of the session</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>I declare resumed the session of the European Parliament adjourned on Friday 17 December 1999, and I would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period.</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>Although, as you will have seen, the dreaded 'millennium bug' failed to materialise, still the people in a number of countries suffered a series of natural disasters that truly were dreadful.</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>You have requested a debate on this subject in the course of the next few days, during this part-session.</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>In the meantime, I should like to observe a minute' s silence, as a number of Members have requested, on behalf of all the victims concerned, particularly those of the terrible storms, in the various countries of the European Union.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, before embarking on a data curation process, it is recommendable to define the structure of the data that we want to create. I call this the “<strong>idealized structure</strong>” of the data. For a curated dataset, we want to reflect the contents of the original data, yet in a tidy format, to maintain the integrity of and connection with the data.</p>
<p>Given what we know about the data, we can define the idealized structure of the data as seen in <a href="#tbl-curate-europarl-structure-example" class="quarto-xref">Table&nbsp;<span>6.2</span></a>.</p>
<div id="tbl-curate-europarl-structure-example" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-curate-europarl-structure-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: Idealized structure for the curated Europarl Corpus datasets
</figcaption><div aria-describedby="tbl-curate-europarl-structure-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 19%">
<col style="width: 54%">
</colgroup>
<thead><tr class="header">
<th>variable</th>
<th>name</th>
<th>type</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>type</td>
<td>Document type</td>
<td>character</td>
<td>Contains the type of document, either ‘Source’ or ‘Target’</td>
</tr>
<tr class="even">
<td>line</td>
<td>Line</td>
<td>character</td>
<td>Contains the text of each line in the document</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Our task now is to develop code that will read the original data and render the idealized structure as a curated dataset for each corpus file. We will then write the datasets to the <em>data/derived/</em> directory. The code we develop will be added to the <em>2-curate-data.qmd</em> file. And finally, the datasets will be documented with a data dictionary file.</p>
</section><section id="tidy-the-data" class="level3"><h3 class="anchored" data-anchor-id="tidy-the-data">Tidy the data</h3>
<p>To create the idealized dataset structure in <a href="#tbl-curate-europarl-structure-example" class="quarto-xref">Table&nbsp;<span>6.2</span></a>, lets’s start by reading the files by lines into R. As the files are aligned by lines, we will use the <code>read_lines()</code> function to read the files into character vectors.</p>
<div id="exm-curate-europarl-readr" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.1</strong></span> &nbsp;</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># Load package</span></span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="fu">library</span>(readr)</span>
<span id="cb4-3"><a href="#cb4-3"></a></span>
<span id="cb4-4"><a href="#cb4-4"></a><span class="co"># Read Europarl files .es and .en</span></span>
<span id="cb4-5"><a href="#cb4-5"></a>europarl_es_chr <span class="ot">&lt;-</span></span>
<span id="cb4-6"><a href="#cb4-6"></a>  <span class="fu">read_lines</span>(<span class="st">"../data/original/europarl-v7.es-en.es"</span>)</span>
<span id="cb4-7"><a href="#cb4-7"></a></span>
<span id="cb4-8"><a href="#cb4-8"></a>europarl_en_chr <span class="ot">&lt;-</span></span>
<span id="cb4-9"><a href="#cb4-9"></a>  <span class="fu">read_lines</span>(<span class="st">"../data/original/europarl-v7.es-en.en"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using the <code>read_lines()</code> function, we read each line of the files into a character vector. Since the Europarl corpus is a parallel corpus, the lines in the source and target files are aligned. This means that the first line in the source file corresponds to the first line in the target file, the second line in the source file corresponds to the second line in the target file, and so on. This alignment is important for the analysis of parallel corpora, as it allows us to compare the source and target texts line by line.</p>
<p>Let’s inspect our character vectors to ensure that they are of the length and appear to be structured as we expect. We can use the <code><a href="https://rdrr.io/r/base/length.html">length()</a></code> function to get the number of lines in each file and the <code><a href="https://rdrr.io/r/utils/head.html">head()</a></code> function to preview the first few lines of each file.</p>
<div id="exm-curate-europarl-inspect-chr" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.2</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># Inspect Spanish character vector</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="fu">length</span>(europarl_es_chr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1965734</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">head</span>(europarl_es_chr, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Reanudación del período de sesiones"                                                                                                                                                                                                 
[2] "Declaro reanudado el período de sesiones del Parlamento Europeo, interrumpido el viernes 17 de diciembre pasado, y reitero a Sus Señorías mi deseo de que hayan tenido unas buenas vacaciones."                                      
[3] "Como todos han podido comprobar, el gran \"efecto del año 2000\" no se ha producido. En cambio, los ciudadanos de varios de nuestros países han sido víctimas de catástrofes naturales verdaderamente terribles."                    
[4] "Sus Señorías han solicitado un debate sobre el tema para los próximos días, en el curso de este período de sesiones."                                                                                                                
[5] "A la espera de que se produzca, de acuerdo con muchos colegas que me lo han pedido, pido que hagamos un minuto de silencio en memoria de todas las víctimas de las tormentas, en los distintos países de la Unión Europea afectados."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># Inspect English character vector</span></span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="fu">length</span>(europarl_en_chr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1965734</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">head</span>(europarl_en_chr, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Resumption of the session"                                                                                                                                                                                                               
[2] "I declare resumed the session of the European Parliament adjourned on Friday 17 December 1999, and I would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period."                         
[3] "Although, as you will have seen, the dreaded 'millennium bug' failed to materialise, still the people in a number of countries suffered a series of natural disasters that truly were dreadful."                                         
[4] "You have requested a debate on this subject in the course of the next few days, during this part-session."                                                                                                                               
[5] "In the meantime, I should like to observe a minute' s silence, as a number of Members have requested, on behalf of all the victims concerned, particularly those of the terrible storms, in the various countries of the European Union."</code></pre>
</div>
</div>
</div>
<p>The output of <a href="#exm-curate-europarl-inspect-chr" class="quarto-xref">Example&nbsp;<span>6.2</span></a> shows that the number of lines in each file is the same. This is good. If the number of lines in each file was different, we would need to figure out why and fix it. We also see that the content of the files is aligned as expected.</p>
<p>Let’s now create a dataset for each of the character vectors. We will use the <code>tibble()</code> function from {tibble} to create a data frame object with the character vectors as the <code>line</code> column and add a <code>type</code> column with the value ‘Source’ for the Spanish file and ‘Target’ for the English file. We will assign the output two new objects <code>europarl_source_df</code> and <code>europarl_target_df</code>, respectively, as seen in <a href="#exm-curate-europarl-df" class="quarto-xref">Example&nbsp;<span>6.3</span></a>.</p>
<div id="exm-curate-europarl-df" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.3</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="co"># Create source data frame</span></span>
<span id="cb13-2"><a href="#cb13-2"></a>europarl_source_df <span class="ot">&lt;-</span></span>
<span id="cb13-3"><a href="#cb13-3"></a>  <span class="fu">tibble</span>(</span>
<span id="cb13-4"><a href="#cb13-4"></a>    <span class="at">type =</span> <span class="st">"Source"</span>,</span>
<span id="cb13-5"><a href="#cb13-5"></a>    <span class="at">lines =</span> europarl_es_chr</span>
<span id="cb13-6"><a href="#cb13-6"></a>  )</span>
<span id="cb13-7"><a href="#cb13-7"></a><span class="co"># Create target data frame</span></span>
<span id="cb13-8"><a href="#cb13-8"></a>europarl_target_df <span class="ot">&lt;-</span></span>
<span id="cb13-9"><a href="#cb13-9"></a>  <span class="fu">tibble</span>(</span>
<span id="cb13-10"><a href="#cb13-10"></a>    <span class="at">type =</span> <span class="st">"Target"</span>,</span>
<span id="cb13-11"><a href="#cb13-11"></a>    <span class="at">lines =</span> europarl_en_chr</span>
<span id="cb13-12"><a href="#cb13-12"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>Inspecting these data frames with <code>glimpse()</code> in <a href="#exm-curate-europarl-glimpse" class="quarto-xref">Example&nbsp;<span>6.4</span></a>, we can see if the data frames have the structure we expect.</p>
<div id="exm-curate-europarl-glimpse" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.4</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="co"># Preview source</span></span>
<span id="cb14-2"><a href="#cb14-2"></a><span class="fu">glimpse</span>(europarl_source_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,965,734
Columns: 2
$ type  &lt;chr&gt; "Source", "Source", "Source", "Source", "Source", "Source", "Sou…
$ lines &lt;chr&gt; "Reanudación del período de sesiones", "Declaro reanudado el per…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># Preview target</span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="fu">glimpse</span>(europarl_target_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,965,734
Columns: 2
$ type  &lt;chr&gt; "Target", "Target", "Target", "Target", "Target", "Target", "Tar…
$ lines &lt;chr&gt; "Resumption of the session", "I declare resumed the session of t…</code></pre>
</div>
</div>
</div>
<p>We now have our <code>type</code> and <code>lines</code> columns and the associated observations for our idealized dataset, in <a href="#tbl-curate-europarl-structure-example" class="quarto-xref">Table&nbsp;<span>6.2</span></a>. We can now write these datasets to the <em>data/derived/</em> directory using <code>write_csv()</code> and create corresponding data dictionary files.</p>
</section></section><section id="structured" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="structured">
<span class="header-section-number">6.2</span> Structured</h2>
<p>Structured data already reflects the physical and semantic structure of a tidy dataset. This means that the data is already in a tabular format and the relationships between columns and rows are already well-defined. Therefore the heavy lifting of curating the data is already done. There are two remaining questions, however, that need to be taken into account. One, logistical question, is what file format the dataset is in and how to read it into R. And the second, more research-based, is whether the data may benefit from some additional curation and documentation to make it more amenable to analysis and more understandable to others.</p>
<section id="reading-datasets" class="level3"><h3 class="anchored" data-anchor-id="reading-datasets">Reading datasets</h3>
<p>Let’s consider some common formats for structured data, <em>i.e.</em> datasets, and how to read them into R. First, we will consider R-native formats, such as package datasets and RDS files. Then will consider non-native formats, such as relational databases and datasets produced by other software. Finally, we will consider software agnostic formats, such as CSV.</p>
<p>R and some R packages provide structured datasets that are available for use directly within R. For example, {languageR} <span class="citation" data-cites="R-languageR">(<a href="../references.html#ref-R-languageR" role="doc-biblioref">Baayen &amp; Shafaei-Bajestan, 2019</a>)</span> provides the <code>dative</code> dataset, which is a dataset containing the realization of the dative as NP or PP in the Switchboard corpus and the Treebank Wall Street Journal collection. {janeaustenr} <span class="citation" data-cites="R-janeaustenr">(<a href="../references.html#ref-R-janeaustenr" role="doc-biblioref">Silge, 2022</a>)</span> provides the <code>austen_books</code> dataset, which is a dataset of Jane Austen’s novels. <strong>Package datasets</strong> are loaded into an R session using either the <code><a href="https://rdrr.io/r/utils/data.html">data()</a></code> function, if the package is loaded, or the <code>::</code> operator, if the package is not loaded, <code>data(dative)</code> or <code><a href="https://rdrr.io/pkg/languageR/man/dative.html">languageR::dative</a></code>, respectively.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-medal" aria-label="medal"></i> Dive deeper</strong></p>
<p>To explore the available datasets in a package, you can use the <code>data(package = "package_name")</code> function. For example, <code>data(package = "languageR")</code> will list the datasets available in {languageR}. You can also explore all the datasets available in the loaded packages with the <code><a href="https://rdrr.io/r/utils/data.html">data()</a></code> function using no arguments. For example, <code><a href="https://rdrr.io/r/utils/data.html">data()</a></code>.</p>
</div>
</div>
</div>
<p>R also provides a native file format for storing R objects, the <strong>RDS file</strong>. Any R object, including data frames, can be written from an R session to disk by using the <code>write_rds()</code> function from <code>readr</code>. The <em>.rds</em> files will be written to disk in a binary format that is not human-readable, which is not ideal for transparent data sharing. However, the files and the R objects can be read back into an R session using the <code>read_rds()</code> function with all the attributes intact, such as vector types, factor levels, <em>etc.</em>.</p>
<p>R provides a suite of tools for importing data from non-native structured sources such as databases and datasets from software such as SPSS, SAS, and Stata. For instance, if you are working with data stored in a <strong>relational database</strong> such as MySQL, PostgreSQL, or SQLite, you can use {DBI} <span class="citation" data-cites="R-DBI">(<a href="../references.html#ref-R-DBI" role="doc-biblioref">R Special Interest Group on Databases (R-SIG-DB), Wickham, &amp; Müller, 2024</a>)</span> to connect to the database and {dbplyr} <span class="citation" data-cites="R-dbplyr">(<a href="../references.html#ref-R-dbplyr" role="doc-biblioref">Wickham, Girlich, &amp; Ruiz, 2024</a>)</span> to query the database using the SQL language. Files from SPSS (<em>.sav</em>), SAS (<em>.sas7bdat</em>), and Stata (<em>.dta</em>) can be read into R using {haven} <span class="citation" data-cites="R-haven">(<a href="../references.html#ref-R-haven" role="doc-biblioref">Wickham, Miller, &amp; Smith, 2023</a>)</span>.</p>
<p>Software agnostic file formats include delimited files, such as CSV, TSV, <em>etc.</em>. These file formats lack the robust structural attributes of the other formats, but balance this shortcoming by storing structured data in more accessible, human-readable format. Delimited files are plain text files which use a delimiter, such as a comma (<code>,</code>), tab (<code>\t</code>), or pipe (<code>|</code>), to separate the columns and rows. For example, a CSV file is a delimited file where the columns and rows are separated by commas, as seen in <a href="#exm-curate-csv-example" class="quarto-xref">Example&nbsp;<span>6.5</span></a>.</p>
<div id="exm-curate-csv-example" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.5</strong></span> &nbsp;</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode numberSource xml number-lines code-with-copy"><code class="sourceCode xml"><span id="cb18-1"><a href="#cb18-1"></a>column_1,column_2,column_3</span>
<span id="cb18-2"><a href="#cb18-2"></a>row 1 value 1,row 1 value 2,row 1 value 3</span>
<span id="cb18-3"><a href="#cb18-3"></a>row 2 value 1,row 2 value 2,row 2 value 3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Given the accessibility of delimited files, they are a common format for sharing structured data in reproducible research. It is not surprising, then, that this is the format which we have chosen for the derived datasets in this book.</p>
</section><section id="orientation-1" class="level3"><h3 class="anchored" data-anchor-id="orientation-1">Orientation</h3>
<p>With an understanding of the various structured formats, we can now turn to considerations about how the original dataset is structured and how that structure is to be used for a given research project. As an example, we will work with the CABNC datasets acquired in <a href="5_acquire.html" class="quarto-xref"><span>Chapter 5</span></a>. The structure of the original dataset is shown in <a href="#def-curate-cabnc-structure" class="quarto-xref">Snippet&nbsp;<span>6.4</span></a>.</p>
<div id="def-curate-cabnc-structure" class="theorem definition">
<p><span class="theorem-title"><strong>Snippet 6.4</strong></span> Directory structure for the CABNC datasets</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="ex">data/</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="ex">├──</span> analysis/</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="ex">├──</span> derived/</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="ex">└──</span> original/</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="ex">├──</span> cabnc_do.csv</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="ex">└──</span> cabnc/</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>        <span class="ex">├──</span> participants.csv</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>        <span class="ex">├──</span> token_types.csv</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>        <span class="ex">├──</span> tokens.csv</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>        <span class="ex">├──</span> transcripts.csv</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>        <span class="ex">└──</span> utterances.csv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In addition to other important information, the data origin file <em>cabnc_do.csv</em> shown in <a href="#tbl-curate-cabnc-do" class="quarto-xref">Table&nbsp;<span>6.3</span></a> informs us the the datasets are related by a common variable.</p>
<div class="cell" data-tbl-colwidths="[25,75]">
<div id="tbl-curate-cabnc-do" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-curate-cabnc-do-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.3: Data origin: CABNC datasets
</figcaption><div aria-describedby="tbl-curate-cabnc-do-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead><tr class="header">
<th>attribute</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Resource name</td>
<td>CABNC.</td>
</tr>
<tr class="even">
<td>Data source</td>
<td>
<a href="https://ca.talkbank.org/access/CABNC.html" class="uri">https://ca.talkbank.org/access/CABNC.html</a>, <a href="doi:10.21415/T55Q5R" class="uri">doi:10.21415/T55Q5R</a>
</td>
</tr>
<tr class="odd">
<td>Data sampling frame</td>
<td>Over 400 British English Speakers from across the UK stratified age, gender, social group, and region, and recording their language output over a set period of time.</td>
</tr>
<tr class="even">
<td>Data collection date(s)</td>
<td><ol start="1992" type="1">
<li>
</li></ol></td>
</tr>
<tr class="odd">
<td>Data format</td>
<td>CSV Files</td>
</tr>
<tr class="even">
<td>Data schema</td>
<td>The recordings are linked by <code>filename</code> and the participants are linked by <code>who</code>.</td>
</tr>
<tr class="odd">
<td>License</td>
<td>CC BY NC SA 3.0</td>
</tr>
<tr class="even">
<td>Attribution</td>
<td>Saul Albert, Laura E. de Ruiter, and J.P. de Ruiter (2015) CABNC: the Jeffersonian transcription of the Spoken British National Corpus. https://saulalbert.github.io/CABNC/.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The CABNC datasets are structured in a relational format, which means that the data is stored in multiple tables that are related to each other. The tables are related by a common column or set of columns, which are called a keys. A key is used to join the tables together to create a single dataset. There are two keys in the CABNC datasets, <code>filename</code> and <code>who</code>. Each variable corresponds to recording- and/ or participant-oriented datasets.</p>
<p>Now, let’s envision a scenario in which we are preparing our data for a study that aims to investigate the relationship between speaker demographics and utterances. In their original format, the CABNC datasets separate information about utterances and speakers in separate datasets, <code>cabnc_utterances</code> and <code>cabnc_participants</code>, respectively. Ideally, we would like to curate these datasets such that the information about the utterances and the speakers are ready to be joined as part of the dataset transformation process, while still retaining the relevant original structure. This usually involves removing redundant and/ or uninformative variables and/ or adjusting variable names and writing these datasets and their documentation files to disk.</p>
</section><section id="tidy-the-dataset" class="level3"><h3 class="anchored" data-anchor-id="tidy-the-dataset">Tidy the dataset</h3>
<p>With these goals in mind, let’s start the process of curation by reading the relevant datasets into an R session. Since we are working with CSV files will will use the <code>read_csv()</code> function, as seen in <a href="#exm-curate-cabnc-read" class="quarto-xref">Example&nbsp;<span>6.6</span></a>.</p>
<div id="exm-curate-cabnc-read" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.6</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># Read the relevant datasets</span></span>
<span id="cb20-2"><a href="#cb20-2"></a>cabnc_utterances <span class="ot">&lt;-</span></span>
<span id="cb20-3"><a href="#cb20-3"></a>  <span class="fu">read_csv</span>(<span class="st">"data/cabnc/original/utterances.csv"</span>)</span>
<span id="cb20-4"><a href="#cb20-4"></a>cabnc_participants <span class="ot">&lt;-</span></span>
<span id="cb20-5"><a href="#cb20-5"></a>  <span class="fu">read_csv</span>(<span class="st">"data/cabnc/original/participants.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>The next step is to inspect the structure of the datasets. We can use the <code>glimpse()</code> function for this task.</p>
<div id="exm-curate-cabnc-glimpse" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.7</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="co"># Preview the structure of the datasets</span></span>
<span id="cb21-2"><a href="#cb21-2"></a><span class="fu">glimpse</span>(cabnc_utterances)</span>
<span id="cb21-3"><a href="#cb21-3"></a><span class="fu">glimpse</span>(cabnc_participants)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 235,901
Columns: 10
$ filename  &lt;chr&gt; "KB0RE000", "KB0RE000", "KB0RE000", "KB0RE000", "KB0RE000", …
$ path      &lt;chr&gt; "ca/CABNC/KB0/KB0RE000", "ca/CABNC/KB0/KB0RE000", "ca/CABNC/…
$ utt_num   &lt;dbl&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17…
$ who       &lt;chr&gt; "PS002", "PS006", "PS002", "PS006", "PS002", "PS006", "PS002…
$ role      &lt;chr&gt; "Unidentified", "Unidentified", "Unidentified", "Unidentifie…
$ postcodes &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ gems      &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ utterance &lt;chr&gt; "You enjoyed yourself in America", "Eh", "did you", "Oh I co…
$ startTime &lt;dbl&gt; 0.208, 2.656, 2.896, 3.328, 5.088, 6.208, 8.320, 8.480, 10.2…
$ endTime   &lt;dbl&gt; 2.67, 2.90, 3.33, 5.26, 6.02, 8.50, 9.31, 11.23, 14.34, 15.9…
Rows: 6,190
Columns: 13
$ filename  &lt;chr&gt; "KB0RE004", "KB0RE004", "KB0RE004", "KB0RE006", "KB0RE006", …
$ path      &lt;chr&gt; "ca/CABNC/0missing/KB0RE004", "ca/CABNC/0missing/KB0RE004", …
$ who       &lt;chr&gt; "PS008", "PS009", "KB0PSUN", "PS007", "PS008", "PS009", "KB0…
$ name      &lt;chr&gt; "John", "Gethyn", "Unknown_speaker", "Alan", "John", "Gethyn…
$ role      &lt;chr&gt; "Unidentified", "Unidentified", "Unidentified", "Unidentifie…
$ language  &lt;chr&gt; "eng", "eng", "eng", "eng", "eng", "eng", "eng", "eng", "eng…
$ monthage  &lt;dbl&gt; 481, 481, 13, 949, 481, 481, 13, 637, 565, 13, 637, 565, 13,…
$ age       &lt;chr&gt; "40;01.01", "40;01.01", "1;01.01", "79;01.01", "40;01.01", "…
$ sex       &lt;chr&gt; "male", "male", "male", "male", "male", "male", "male", "mal…
$ numwords  &lt;dbl&gt; 28, 360, 156, 1610, 791, 184, 294, 93, 3, 0, 128, 24, 0, 150…
$ numutts   &lt;dbl&gt; 1, 9, 27, 7, 5, 7, 6, 5, 1, 0, 11, 6, 0, 110, 74, 96, 12, 1,…
$ avgutt    &lt;dbl&gt; 28.00, 40.00, 5.78, 230.00, 158.20, 26.29, 49.00, 18.60, 3.0…
$ medianutt &lt;dbl&gt; 28, 39, 5, 84, 64, 9, 3, 15, 3, 0, 9, 3, 0, 7, 6, 4, 3, 12, …</code></pre>
</div>
</div>
</div>
<p>From visual inspection of the output of <a href="#exm-curate-cabnc-glimpse" class="quarto-xref">Example&nbsp;<span>6.7</span></a> we can see that there are common variables in both datasets. In particular, we see the <code>filename</code> and <code>who</code> variables mentioned in the data origin file <em>cabnc_do.csv</em>.</p>
<p>The next step is to consider the variables that will be useful for future analysis. Since we are creating a curated dataset, the goal will be to retain as much information as possible from the original datasets. There are cases, however, in which there may be variables that are not informative and thus, will not prove useful for any analysis. These removable variables tend to be of one of two types: variables which show no variation across observations and variables where the information is redundant.</p>
<p>As an example case, let’s look at the <code>cabnc_participants</code> data frame. We can use the <code>skim()</code> function from {skimr} to get a summary of the variables in the dataset. We can add the <code>yank()</code> function to look at variable types one at a time. We will start with the character variables, as seen in <a href="#exm-curate-cabnc-skim-character" class="quarto-xref">Example&nbsp;<span>6.8</span></a>.</p>
<div id="exm-curate-cabnc-skim-character" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.8</strong></span> &nbsp;</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="co"># Load package</span></span>
<span id="cb23-2"><a href="#cb23-2"></a><span class="fu">library</span>(skimr)</span>
<span id="cb23-3"><a href="#cb23-3"></a></span>
<span id="cb23-4"><a href="#cb23-4"></a><span class="co"># Summarize character variables</span></span>
<span id="cb23-5"><a href="#cb23-5"></a>cabnc_participants <span class="sc">|&gt;</span></span>
<span id="cb23-6"><a href="#cb23-6"></a>  <span class="fu">skim</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-7"><a href="#cb23-7"></a>  <span class="fu">yank</span>(<span class="st">"character"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
── Variable type: character ────────────────────────────────────────────────────
  skim_variable n_missing complete_rate min max empty n_unique whitespace
1 filename              0             1   8   8     0     2020          0
2 path                  0             1  21  26     0     2020          0
3 who                   0             1   4   7     0      581          0
4 name                  0             1   3  25     0      269          0
5 role                  0             1  12  12     0        1          0
6 language              0             1   3   3     0        1          0
7 age                   0             1   7   8     0       83          0
8 sex                   0             1   4   6     0        2          0</code></pre>
</div>
</div>
</div>
<p>We see from the output in <a href="#exm-curate-cabnc-skim-character" class="quarto-xref">Example&nbsp;<span>6.8</span></a>, that the variables <code>role</code> and <code>language</code> have a single unique value. This means that these variables do not show any variation across observations. We will remove these variables from the dataset.</p>
<p>Continuing on, let’s look for redundant variables. We see that the variables <code>filename</code> and <code>path</code> have the same number unique values. And if we combine this with the visual summary in <a href="#exm-curate-cabnc-glimpse" class="quarto-xref">Example&nbsp;<span>6.7</span></a>, we can see that the <code>path</code> variable is redundant. We will remove this variable from the dataset.</p>
<p>Another potentially redundant set of variables are <code>who</code> and <code>name</code> –both of which are speaker identifiers. The <code>who</code> variable is a unique identifier, but there may be some redundancy with the <code>name</code> variable, that is there may be two speakers with the same name. We can check this by looking at the number of unique values in the <code>who</code> and <code>name</code> variables from the <code>skim()</code> output in <a href="#exm-curate-cabnc-skim-character" class="quarto-xref">Example&nbsp;<span>6.8</span></a>. <code>who</code> has 568 unique values and <code>name</code> has 269 unique values. This suggests that there are multiple speakers with the same name.</p>
<p>Another way to explore this is to look at the number of unique values in the <code>who</code> variable for each unique value in the <code>name</code> variable. We can do this using the <code>group_by()</code> and <code>summarize()</code> functions from {dplyr}. For each value of <code>name</code>, we will count the number of unique values in <code>who</code> with <code>n_distinct()</code> and then sort the results in descending order.</p>
<div id="exm-curate-cabnc-who-name" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.9</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a>cabnc_participants <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2"></a>  <span class="fu">group_by</span>(name) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n_distinct</span>(who)) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 269 × 2
   name                          n
   &lt;chr&gt;                     &lt;int&gt;
 1 None                         59
 2 Unknown_speaker              59
 3 Group_of_unknown_speakers    21
 4 Chris                         9
 5 David                         9
 6 Margaret                      8
 7 Ann                           7
 8 John                          7
 9 Alan                          6
10 Jackie                        5
# ℹ 259 more rows</code></pre>
</div>
</div>
</div>
<p>It is good that we performed the check in <a href="#exm-curate-cabnc-who-name" class="quarto-xref">Example&nbsp;<span>6.9</span></a> beforehand. In addition to speakers with the same name, such as ‘Chris’ and ‘David’, we also have multiple speakers with generic codes, such as ‘None’ and ‘Unknown_speaker’. It is clear that <code>name</code> is redundant and we can safely remove it from the dataset.</p>
<p>With this in mind, we can then safely remove the following variables from the dataset: <code>role</code>, <code>language</code>, <code>name</code>, and <code>path</code>. To drop variables from a data frame we can use the <code>select()</code> function in combination with the <code>-</code> operator. The <code>-</code> operator tells the <code>select()</code> function to drop the variables that follow it.</p>
<div id="exm-curate-cabnc-drop-vars" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.10</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co"># Drop variables</span></span>
<span id="cb27-2"><a href="#cb27-2"></a>cabnc_participants <span class="ot">&lt;-</span></span>
<span id="cb27-3"><a href="#cb27-3"></a>  cabnc_participants <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4"></a>  <span class="fu">select</span>(<span class="sc">-</span>role, <span class="sc">-</span>language, <span class="sc">-</span>name, <span class="sc">-</span>path)</span>
<span id="cb27-5"><a href="#cb27-5"></a></span>
<span id="cb27-6"><a href="#cb27-6"></a><span class="co"># Preview the dataset</span></span>
<span id="cb27-7"><a href="#cb27-7"></a><span class="fu">glimpse</span>(cabnc_participants)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,190
Columns: 9
$ filename  &lt;chr&gt; "KB0RE004", "KB0RE004", "KB0RE004", "KB0RE006", "KB0RE006", …
$ who       &lt;chr&gt; "PS008", "PS009", "KB0PSUN", "PS007", "PS008", "PS009", "KB0…
$ monthage  &lt;dbl&gt; 481, 481, 13, 949, 481, 481, 13, 637, 565, 13, 637, 565, 13,…
$ age       &lt;chr&gt; "40;01.01", "40;01.01", "1;01.01", "79;01.01", "40;01.01", "…
$ sex       &lt;chr&gt; "male", "male", "male", "male", "male", "male", "male", "mal…
$ numwords  &lt;dbl&gt; 28, 360, 156, 1610, 791, 184, 294, 93, 3, 0, 128, 24, 0, 150…
$ numutts   &lt;dbl&gt; 1, 9, 27, 7, 5, 7, 6, 5, 1, 0, 11, 6, 0, 110, 74, 96, 12, 1,…
$ avgutt    &lt;dbl&gt; 28.00, 40.00, 5.78, 230.00, 158.20, 26.29, 49.00, 18.60, 3.0…
$ medianutt &lt;dbl&gt; 28, 39, 5, 84, 64, 9, 3, 15, 3, 0, 9, 3, 0, 7, 6, 4, 3, 12, …</code></pre>
</div>
</div>
</div>
<p>Now we have a frame with 9 more informative variables which describe the participants. We would then repeat this process for the <code>cabnc_utterances</code> dataset to remove redundant and uninformative variables.</p>
<p>Another, optional step, is to rename and/ or organize the order the variables to make the dataset more understandable. Let’s organize the columns to read left to right from most general to most specific. Again, we turn to the <code>select()</code> function, this time including the variables in the order we want them to appear in the dataset. We will take this opportunity to rename some of the variable names so that they are more informative.</p>
<div id="exm-curate-cabnc-rename-vars" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.11</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># Rename variables</span></span>
<span id="cb29-2"><a href="#cb29-2"></a>cabnc_participants <span class="ot">&lt;-</span></span>
<span id="cb29-3"><a href="#cb29-3"></a>  cabnc_participants <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4"></a>  <span class="fu">select</span>(</span>
<span id="cb29-5"><a href="#cb29-5"></a>    <span class="at">doc_id =</span> filename,</span>
<span id="cb29-6"><a href="#cb29-6"></a>    <span class="at">part_id =</span> who,</span>
<span id="cb29-7"><a href="#cb29-7"></a>    <span class="at">part_age =</span> monthage,</span>
<span id="cb29-8"><a href="#cb29-8"></a>    <span class="at">part_sex =</span> sex,</span>
<span id="cb29-9"><a href="#cb29-9"></a>    <span class="at">num_words =</span> numwords,</span>
<span id="cb29-10"><a href="#cb29-10"></a>    <span class="at">num_utts =</span> numutts,</span>
<span id="cb29-11"><a href="#cb29-11"></a>    <span class="at">avg_utt_len =</span> avgutt,</span>
<span id="cb29-12"><a href="#cb29-12"></a>    <span class="at">median_utt_len =</span> medianutt</span>
<span id="cb29-13"><a href="#cb29-13"></a>  )</span>
<span id="cb29-14"><a href="#cb29-14"></a></span>
<span id="cb29-15"><a href="#cb29-15"></a><span class="co"># Preview the dataset</span></span>
<span id="cb29-16"><a href="#cb29-16"></a><span class="fu">glimpse</span>(cabnc_participants)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,190
Columns: 8
$ doc_id         &lt;chr&gt; "KB0RE004", "KB0RE004", "KB0RE004", "KB0RE006", "KB0RE0…
$ part_id        &lt;chr&gt; "PS008", "PS009", "KB0PSUN", "PS007", "PS008", "PS009",…
$ part_age       &lt;dbl&gt; 481, 481, 13, 949, 481, 481, 13, 637, 565, 13, 637, 565…
$ part_sex       &lt;chr&gt; "male", "male", "male", "male", "male", "male", "male",…
$ num_words      &lt;dbl&gt; 28, 360, 156, 1610, 791, 184, 294, 93, 3, 0, 128, 24, 0…
$ num_utts       &lt;dbl&gt; 1, 9, 27, 7, 5, 7, 6, 5, 1, 0, 11, 6, 0, 110, 74, 96, 1…
$ avg_utt_len    &lt;dbl&gt; 28.00, 40.00, 5.78, 230.00, 158.20, 26.29, 49.00, 18.60…
$ median_utt_len &lt;dbl&gt; 28, 39, 5, 84, 64, 9, 3, 15, 3, 0, 9, 3, 0, 7, 6, 4, 3,…</code></pre>
</div>
</div>
</div>
<p>The variable order is organized after running <a href="#exm-curate-cabnc-rename-vars" class="quarto-xref">Example&nbsp;<span>6.11</span></a>. Now let’s sort the rows by <code>doc_id</code> and <code>part_id</code> so that the dataset is sensibly organized. The <code>arrange()</code> function takes a data frame and a list of variables to sort by, in the order they are listed.</p>
<!-- [ ] tmp fmt -->
<div style="page-break-after: always;"></div>
<div id="exm-curate-cabnc-sort-rows" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.12</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># Sort rows</span></span>
<span id="cb31-2"><a href="#cb31-2"></a>cabnc_participants <span class="ot">&lt;-</span></span>
<span id="cb31-3"><a href="#cb31-3"></a>  cabnc_participants <span class="sc">|&gt;</span></span>
<span id="cb31-4"><a href="#cb31-4"></a>  <span class="fu">arrange</span>(doc_id, part_id)</span>
<span id="cb31-5"><a href="#cb31-5"></a></span>
<span id="cb31-6"><a href="#cb31-6"></a><span class="co"># Preview the dataset</span></span>
<span id="cb31-7"><a href="#cb31-7"></a>cabnc_participants <span class="sc">|&gt;</span></span>
<span id="cb31-8"><a href="#cb31-8"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 8
   doc_id   part_id part_age part_sex num_words num_utts avg_utt_len
   &lt;chr&gt;    &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;
 1 KB0RE000 KB0PSUN       13 male             2        2        1   
 2 KB0RE000 PS002        721 female         759       74       10.3 
 3 KB0RE000 PS006        601 male           399       64        6.23
 4 KB0RE001 KB0PSUN       13 male             7        3        2.33
 5 KB0RE001 PS005        481 female         257       32        8.03
 6 KB0RE001 PS007        949 male           284       29        9.79
 7 KB0RE002 KB0PSUN       13 male             0        0        0   
 8 KB0RE002 PS003        601 female         379       30       12.6 
 9 KB0RE002 PS007        949 male            98       29        3.38
10 KB0RE003 KB0PSUN       13 male             0        0        0   
# ℹ 1 more variable: median_utt_len &lt;dbl&gt;</code></pre>
</div>
</div>
</div>
<p>Applying the sorting in <a href="#exm-curate-cabnc-sort-rows" class="quarto-xref">Example&nbsp;<span>6.12</span></a>, we can see that the utterances are now our desired order, a dataset that reads left to right from document to participant-oriented attributes and top to bottom by document and participant.</p>
</section></section><section id="semi-structured" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="semi-structured">
<span class="header-section-number">6.3</span> Semi-structured</h2>
<p>Between unstructured and structured data falls semi-structured data. And as the name suggests, it is a hybrid data format. This means that there will be important structured metadata included with unstructured elements. The file formats and approaches to encoding the structured aspects of the data vary widely from resource to resource and therefore often requires more detailed attention to the structure of the data and often includes more sophisticated programming strategies to curate the data to produce a tidy dataset.</p>
<section id="reading-data-1" class="level3"><h3 class="anchored" data-anchor-id="reading-data-1">Reading data</h3>
<p>The file formats associated with semi-structured data include a wide range. These include file formats conducive to more structured-leaning data, such as XML, HTML, and JSON, and file formats with more unstructured-leaning data, such as annotated TXT files. Annotated TXT files may in fact appear with the <em>.txt</em> extension, but may also appear with other, sometimes resource-specific, extensions, such as <em>.utt</em> for the Switchboard Dialog Act Corpus or <em>.cha</em> for the CHILDES corpus annotation files, for example.</p>
<p>The more structured file formats use standard conventions and therefore can be read into an R session with format-specific functions. Say, for example, we are working with data in a JSON file format. We can read the data into an R session with the <code>read_json()</code> function from {jsonlite} <span class="citation" data-cites="R-jsonlite">(<a href="../references.html#ref-R-jsonlite" role="doc-biblioref">Ooms, 2023</a>)</span>. For XML and HTML files, {rvest} <span class="citation" data-cites="R-rvest">(<a href="../references.html#ref-R-rvest" role="doc-biblioref">Wickham, 2024</a>)</span> provides the <code>read_xml()</code> and <code>read_html()</code> functions.</p>
<p>Semi-structured data in TXT files can be read either as a file or by lines. The choice of which approach to take depends on the structure of the data. If the data structure is line-based, then <code>read_lines()</code> often makes more sense than <code>read_file()</code>. However, in some cases, the data may be structured in a way that requires the entire file to be read into an R session and then subsequently parsed.</p>
</section><section id="sec-curate-semi-structured-orientation" class="level3"><h3 class="anchored" data-anchor-id="sec-curate-semi-structured-orientation">Orientation</h3>
<p>To provide an example of the curation process using semi-structured data, we will work with the ENNTT corpus <span class="citation" data-cites="Nisioi2016">(<a href="../references.html#ref-Nisioi2016" role="doc-biblioref">Nisioi, Rabinovich, Dinu, &amp; Wintner, 2016</a>)</span>. The ENNTT corpus contains native and translated English drawn from European Parliament proceedings. Let’s look at the directory structure for the ENNTT corpus in <a href="#def-curate-enntt-structure" class="quarto-xref">Snippet&nbsp;<span>6.5</span></a>.</p>
<div id="def-curate-enntt-structure" class="theorem definition">
<p><span class="theorem-title"><strong>Snippet 6.5</strong></span> Data directory structure for the ENNTT corpus</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="ex">data/</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="ex">├──</span> analysis/</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="ex">├──</span> derived/</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="ex">└──</span> original/</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="ex">├──</span> enntt_do.csv</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="ex">└──</span> enntt/</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>        <span class="ex">├──</span> natives.dat</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>        <span class="ex">├──</span> natives.tok</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>        <span class="ex">├──</span> nonnatives.dat</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>        <span class="ex">├──</span> nonnatives.tok</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>        <span class="ex">├──</span> translations.dat</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>        <span class="ex">└──</span> translations.tok</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We now inspect the data origin file for the ENNTT corpus, <em>enntt_do.csv</em>, in <a href="#tbl-curate-enntt-do" class="quarto-xref">Table&nbsp;<span>6.4</span></a>.</p>
<div class="cell" data-tbl-colwidths="[25,75]">
<div id="tbl-curate-enntt-do" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-curate-enntt-do-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.4: Data origin file for the ENNTT corpus.
</figcaption><div aria-describedby="tbl-curate-enntt-do-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead><tr class="header">
<th>attribute</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Resource name</td>
<td>Europarl corpus of Native, Non-native and Translated Texts - ENNTT</td>
</tr>
<tr class="even">
<td>Data source</td>
<td>https://github.com/senisioi/enntt-release</td>
</tr>
<tr class="odd">
<td>Data sampling frame</td>
<td>English, European Parliament texts, transcribed discourse, political genre</td>
</tr>
<tr class="even">
<td>Data collection date(s)</td>
<td>Not specified in the repository</td>
</tr>
<tr class="odd">
<td>Data format</td>
<td>.tok, .dat</td>
</tr>
<tr class="even">
<td>Data schema</td>
<td>
<em>.tok files contain the actual text; </em>.dat files contain the annotations corresponding to each line in the *.tok files.</td>
</tr>
<tr class="odd">
<td>License</td>
<td>Not specified. Contact the authors for more information.</td>
</tr>
<tr class="even">
<td>Attribution</td>
<td>Nisioi, S., Rabinovich, E., Dinu, L. P., &amp; Wintner, S. (2016). A corpus of native, non-native and translated texts. Proceedings of the Tenth International Conference on Language Resources and Evaluation (LREC 2016).</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>According to the data origin file, there are two important file types, <em>.dat</em> and <em>.tok</em>. The <em>.dat</em> files contain annotations and the <em>.tok</em> files contain the actual text. Let’s inspect the first couple of lines in the <em>.dat</em> file for the native speakers, <em>nonnatives.dat</em>, in <a href="#def-curate-enntt-nonnatives-dat" class="quarto-xref">Snippet&nbsp;<span>6.6</span></a>.</p>
<div id="def-curate-enntt-nonnatives-dat" class="theorem definition">
<p><span class="theorem-title"><strong>Snippet 6.6</strong></span> Example <em>.dat</em> file for the non-native speakers</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode xml code-with-copy"><code class="sourceCode xml"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>&lt;<span class="kw">LINE</span><span class="ot"> STATE=</span><span class="st">"Poland"</span><span class="ot"> MEPID=</span><span class="st">"96779"</span><span class="ot"> LANGUAGE=</span><span class="st">"EN"</span><span class="ot"> NAME=</span><span class="st">"Danuta Hübner,"</span><span class="ot"> SEQ_SPEAKER_ID=</span><span class="st">"184"</span><span class="ot"> SESSION_ID=</span><span class="st">"ep-05-11-17"</span>/&gt;</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>&lt;<span class="kw">LINE</span><span class="ot"> STATE=</span><span class="st">"Poland"</span><span class="ot"> MEPID=</span><span class="st">"96779"</span><span class="ot"> LANGUAGE=</span><span class="st">"EN"</span><span class="ot"> NAME=</span><span class="st">"Danuta Hübner,"</span><span class="ot"> SEQ_SPEAKER_ID=</span><span class="st">"184"</span><span class="ot"> SESSION_ID=</span><span class="st">"ep-05-11-17"</span>/&gt;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We see that the <em>.dat</em> file contains annotations for various session and speaker attributes. The format of the annotations is XML-like. XML is a form of markup language, such as YAML, JSON, <em>etc.</em> <strong>Markup languages</strong> are used to annotate text with additional information about the structure, meaning, and/ or presentation of text. In XML, structure is built up by nesting of nodes. The nodes are named with tags, which are enclosed in angle brackets, <code>&lt;</code> and <code>&gt;</code>. Nodes are opened with <code>&lt;TAG&gt;</code> and closed with <code>&lt;/TAG&gt;</code>. In <a href="#def-curate-xml" class="quarto-xref">Snippet&nbsp;<span>6.7</span></a> we see an example of a simple XML file structure.</p>
<!-- [ ] tmp fmt -->
<div style="page-break-after: always;"></div>
<div id="def-curate-xml" class="theorem definition">
<p><span class="theorem-title"><strong>Snippet 6.7</strong></span> Example <em>.xml</em> file structure</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode xml code-with-copy"><code class="sourceCode xml"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">&lt;?xml</span><span class="ot"> version=</span><span class="st">"1.0"</span><span class="ot"> encoding=</span><span class="st">"UTF-8"</span><span class="fu">?&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>&lt;<span class="kw">book</span><span class="ot"> category=</span><span class="st">"fiction"</span>&gt;</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  &lt;<span class="kw">title</span><span class="ot"> lang=</span><span class="st">"en"</span>&gt;The Catcher in the Rye&lt;/<span class="kw">title</span>&gt;</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  &lt;<span class="kw">author</span>&gt;J.D. Salinger&lt;/<span class="kw">author</span>&gt;</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  &lt;<span class="kw">year</span>&gt;1951&lt;/<span class="kw">year</span>&gt;</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>&lt;/<span class="kw">book</span>&gt;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <a href="#def-curate-xml" class="quarto-xref">Snippet&nbsp;<span>6.7</span></a> there are four nodes, three of which are nested inside of the <code>&lt;book&gt;</code> node. The <code>&lt;book&gt;</code> node in this example is the root node. XML files require a root node. Nodes can also have attributes, such as the <code>category</code> attribute in the <code>&lt;book&gt;</code> node, but they are not required. Furthermore, XML files also require a declaration, which is the first line in <a href="#def-curate-xml" class="quarto-xref">Snippet&nbsp;<span>6.7</span></a>. The declaration specifies the version of XML used and the encoding.</p>
<p>So the <em>.dat</em> file is not strict XML, but is similar in that it contains nodes and attributes. An XML variant you a likely familiar with, HTML, has more relaxed rules than XML. HTML is a markup language used to annotate text with information about the organization and presentation of text on the web that does not require a root node or a declaration –much like our <em>.dat</em> file. So suffice it to say that the <em>.dat</em> file can safely be treated as HTML.</p>
<p>And the <em>.tok</em> file for the native speakers, <em>nonnatives.tok</em>, in <a href="#def-curate-enntt-nonnatives-tok" class="quarto-xref">Snippet&nbsp;<span>6.8</span></a>, shows the actual text for each line in the corpus.</p>
<div id="def-curate-enntt-nonnatives-tok" class="theorem definition">
<p><span class="theorem-title"><strong>Snippet 6.8</strong></span> Example <em>.tok</em> file for the non-native speakers</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode xml code-with-copy"><code class="sourceCode xml"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>The Commission is following with interest the planned construction of a nuclear power plant in Akkuyu , Turkey and recognises the importance of ensuring that the construction of the new plant follows the highest internationally accepted nuclear safety standards .</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>According to our information , the decision on the selection of a bidder has not been taken yet .</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In a study in which we are interested in contrasting the language of natives and non-natives, we will want to combine the <em>.dat</em> and <em>.tok</em> files for these groups of speakers.</p>
<p>The question is what attributes we want to include in the curated dataset. Given the research focus, we will not need the <code>LANGUAGE</code> or <code>NAME</code> attributes. We may want to modify the attribute names so they are a bit more descriptive.</p>
<p>An idealized version of the curated dataset based on this criteria is shown in <a href="#tbl-curate-enntt-ideal" class="quarto-xref">Table&nbsp;<span>6.5</span></a>.</p>
<div id="tbl-curate-enntt-ideal" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-curate-enntt-ideal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.5: Idealized structure for the curated ENNTT Corpus datasets
</figcaption><div aria-describedby="tbl-curate-enntt-ideal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 17%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>variable</th>
<th>name</th>
<th>type</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>session_id</td>
<td>Session ID</td>
<td>character</td>
<td>Unique identifier for each session.</td>
</tr>
<tr class="even">
<td>speaker_id</td>
<td>Speaker ID</td>
<td>integer</td>
<td>Unique identifier for each speaker.</td>
</tr>
<tr class="odd">
<td>state</td>
<td>State</td>
<td>character</td>
<td>The political state of the speaker.</td>
</tr>
<tr class="even">
<td>type</td>
<td>Type</td>
<td>character</td>
<td>Indicates whether the text is native or non-native</td>
</tr>
<tr class="odd">
<td>session_seq</td>
<td>Session Sequence</td>
<td>integer</td>
<td>The sequence of the text in the session.</td>
</tr>
<tr class="even">
<td>text</td>
<td>Text</td>
<td>character</td>
<td>Contains the text of the line, and maintains the structure of the original data.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section><section id="tidy-the-data-1" class="level3"><h3 class="anchored" data-anchor-id="tidy-the-data-1">Tidy the data</h3>
<p>Now that we have a better understanding of the corpus data and our target curated dataset structure, let’s work to extract and organize the data from the native and non-native files.</p>
<p>The general approach we will take is, for native and then non-natives, to read in the <em>.dat</em> file as an HTML file and then extract the line nodes and their attributes combining them into a data frame. Then we’ll read in the <em>.tok</em> file as a text file and then combine the two into a single data frame.</p>
<p>Starting with the natives, we use {rvest} to read in the <em>.dat</em> file as an XML file with the <code>read_html()</code> function and then extract the line nodes with the <code>html_elements()</code> function as in <a href="#exm-curate-enntt-read-xml" class="quarto-xref">Example&nbsp;<span>6.13</span></a>.</p>
<div id="exm-curate-enntt-read-xml" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.13</strong></span> &nbsp;</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="co"># Load packages</span></span>
<span id="cb37-2"><a href="#cb37-2"></a><span class="fu">library</span>(rvest)</span>
<span id="cb37-3"><a href="#cb37-3"></a></span>
<span id="cb37-4"><a href="#cb37-4"></a><span class="co"># Read in *.dat* file as HTML</span></span>
<span id="cb37-5"><a href="#cb37-5"></a>ns_dat_lines <span class="ot">&lt;-</span></span>
<span id="cb37-6"><a href="#cb37-6"></a>  <span class="fu">read_html</span>(<span class="st">"../data/original/enntt/natives.dat"</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-7"><a href="#cb37-7"></a>  <span class="fu">html_elements</span>(<span class="st">"line"</span>)</span>
<span id="cb37-8"><a href="#cb37-8"></a></span>
<span id="cb37-9"><a href="#cb37-9"></a><span class="co"># Inspect</span></span>
<span id="cb37-10"><a href="#cb37-10"></a><span class="fu">class</span>(ns_dat_lines)</span>
<span id="cb37-11"><a href="#cb37-11"></a><span class="fu">typeof</span>(ns_dat_lines)</span>
<span id="cb37-12"><a href="#cb37-12"></a><span class="fu">length</span>(ns_dat_lines)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "xml_nodeset"
[1] "list"
[1] 116341</code></pre>
</div>
</div>
</div>
<p>When can see that the <code>ns_dat_lines</code> object is a special type of list, <code>xml_nodeset</code> which contains 116,341 line nodes. Let’s now jump out of sequence and read in the <em>.tok</em> file as a text file, in <a href="#exm-curate-enntt-read-lines" class="quarto-xref">Example&nbsp;<span>6.14</span></a>, again by lines using <code>read_lines()</code>, and compare the two to make sure that our approach will work.</p>
<div id="exm-curate-enntt-read-lines" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.14</strong></span> &nbsp;</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="co"># Read in *.tok* file by lines</span></span>
<span id="cb39-2"><a href="#cb39-2"></a>ns_tok_lines <span class="ot">&lt;-</span></span>
<span id="cb39-3"><a href="#cb39-3"></a>  <span class="fu">read_lines</span>(<span class="st">"../data/enntt/original/natives.tok"</span>)</span>
<span id="cb39-4"><a href="#cb39-4"></a></span>
<span id="cb39-5"><a href="#cb39-5"></a><span class="co"># Inspect</span></span>
<span id="cb39-6"><a href="#cb39-6"></a><span class="fu">class</span>(ns_tok_lines)</span>
<span id="cb39-7"><a href="#cb39-7"></a><span class="fu">typeof</span>(ns_tok_lines)</span>
<span id="cb39-8"><a href="#cb39-8"></a><span class="fu">length</span>(ns_tok_lines)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"
[1] "character"
[1] 116341</code></pre>
</div>
</div>
</div>
<p>We do, in fact, have the same number of lines in the <em>.dat</em> and <em>.tok</em> files. So we can proceed with extracting the attributes from the line nodes and combining them with the text from the <em>.tok</em> file.</p>
<p>Let’s start by listing the attributes of the first line node in the <code>ns_dat_lines</code> object. To do this we will draw on the <code>pluck()</code> function from {purrr} <span class="citation" data-cites="R-purrr">(<a href="../references.html#ref-R-purrr" role="doc-biblioref">Wickham &amp; Henry, 2023</a>)</span> to extract the first line node. Then, we use the <code>html_attrs()</code> function to get the attribute names and the values, as in <a href="#exm-curate-enntt-list-attributes" class="quarto-xref">Example&nbsp;<span>6.15</span></a>.</p>
<div id="exm-curate-enntt-list-attributes" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.15</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a><span class="co"># Load package</span></span>
<span id="cb41-2"><a href="#cb41-2"></a><span class="fu">library</span>(purrr)</span>
<span id="cb41-3"><a href="#cb41-3"></a></span>
<span id="cb41-4"><a href="#cb41-4"></a><span class="co"># List attributes line node 1</span></span>
<span id="cb41-5"><a href="#cb41-5"></a>ns_dat_lines <span class="sc">|&gt;</span></span>
<span id="cb41-6"><a href="#cb41-6"></a>  <span class="fu">pluck</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb41-7"><a href="#cb41-7"></a>  <span class="fu">html_attrs</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            state             mepid          language              name 
 "United Kingdom"            "2099"              "EN" "Evans, Robert J" 
   seq_speaker_id        session_id 
              "2"     "ep-00-01-17" </code></pre>
</div>
</div>
</div>
<p>No surprise here, these are the same attributes we saw in the <em>.dat</em> file preview in <a href="#def-curate-enntt-nonnatives-dat" class="quarto-xref">Snippet&nbsp;<span>6.6</span></a>. At this point, it’s good to make a plan on how to associate the attribute names with the column names in our curated dataset.</p>
<!-- [ ] tmp fmt -->
<div style="page-break-after: always;"></div>
<ul>
<li>
<code>session_id</code> = <code>session_id</code>
</li>
<li>
<code>speaker_id</code> = <code>MEPID</code>
</li>
<li>
<code>state</code> = <code>state</code>
</li>
<li>
<code>session_seq</code> = <code>seq_speaker_id</code>
</li>
</ul>
<p>We can do this one attribute at a time using the <code>html_attr()</code> function and then combine them into a data frame with the <code>tibble()</code> function as in <a href="#exm-curate-enntt-extract-attributes" class="quarto-xref">Example&nbsp;<span>6.16</span></a>.</p>
<div id="exm-curate-enntt-extract-attributes" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.16</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="co"># Extract attributes from first line node</span></span>
<span id="cb43-2"><a href="#cb43-2"></a>session_id <span class="ot">&lt;-</span> ns_dat_lines <span class="sc">|&gt;</span> <span class="fu">pluck</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="fu">html_attr</span>(<span class="st">"session_id"</span>)</span>
<span id="cb43-3"><a href="#cb43-3"></a>speaker_id <span class="ot">&lt;-</span> ns_dat_lines <span class="sc">|&gt;</span> <span class="fu">pluck</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="fu">html_attr</span>(<span class="st">"mepid"</span>)</span>
<span id="cb43-4"><a href="#cb43-4"></a>state <span class="ot">&lt;-</span> ns_dat_lines <span class="sc">|&gt;</span> <span class="fu">pluck</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="fu">html_attr</span>(<span class="st">"state"</span>)</span>
<span id="cb43-5"><a href="#cb43-5"></a>session_seq <span class="ot">&lt;-</span> ns_dat_lines <span class="sc">|&gt;</span> <span class="fu">pluck</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="fu">html_attr</span>(<span class="st">"seq_speaker_id"</span>)</span>
<span id="cb43-6"><a href="#cb43-6"></a></span>
<span id="cb43-7"><a href="#cb43-7"></a><span class="co"># Combine into data frame</span></span>
<span id="cb43-8"><a href="#cb43-8"></a><span class="fu">tibble</span>(session_id, speaker_id, state, session_seq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  session_id  speaker_id state          session_seq
  &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;          &lt;chr&gt;      
1 ep-00-01-17 2099       United Kingdom 2          </code></pre>
</div>
</div>
</div>
<p>The results from <a href="#exm-curate-enntt-extract-attributes" class="quarto-xref">Example&nbsp;<span>6.16</span></a> show that the attributes have been extracted and mapped to our idealized column names, but this would be tedious to do for each line node. A function to extract attributes and values from a line and add them to a data frame would help simplify this process. The function in <a href="#exm-curate-enntt-extract-attributes-function" class="quarto-xref">Example&nbsp;<span>6.17</span></a> does just that.</p>
<div id="exm-curate-enntt-extract-attributes-function" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.17</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="co"># Function to extract attributes from line node</span></span>
<span id="cb45-2"><a href="#cb45-2"></a>extract_dat_attrs <span class="ot">&lt;-</span> <span class="cf">function</span>(line_node) {</span>
<span id="cb45-3"><a href="#cb45-3"></a>  session_id <span class="ot">&lt;-</span> line_node <span class="sc">|&gt;</span> <span class="fu">html_attr</span>(<span class="st">"session_id"</span>)</span>
<span id="cb45-4"><a href="#cb45-4"></a>  speaker_id <span class="ot">&lt;-</span> line_node <span class="sc">|&gt;</span> <span class="fu">html_attr</span>(<span class="st">"mepid"</span>)</span>
<span id="cb45-5"><a href="#cb45-5"></a>  state <span class="ot">&lt;-</span> line_node <span class="sc">|&gt;</span> <span class="fu">html_attr</span>(<span class="st">"state"</span>)</span>
<span id="cb45-6"><a href="#cb45-6"></a>  session_seq <span class="ot">&lt;-</span> line_node <span class="sc">|&gt;</span> <span class="fu">html_attr</span>(<span class="st">"seq_speaker_id"</span>)</span>
<span id="cb45-7"><a href="#cb45-7"></a></span>
<span id="cb45-8"><a href="#cb45-8"></a>  <span class="fu">tibble</span>(session_id, speaker_id, state, session_seq)</span>
<span id="cb45-9"><a href="#cb45-9"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>It’s a good idea to test out the function to verify that it works as expected. We can do this by passing the various indices to the <code>ns_dat_lines</code> object to the function as in <a href="#exm-curate-enntt-test-extract-attributes-function" class="quarto-xref">Example&nbsp;<span>6.18</span></a>.</p>
<!-- [ ] tmp fmt -->
<div style="page-break-after: always;"></div>
<div id="exm-curate-enntt-test-extract-attributes-function" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.18</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="co"># Test function</span></span>
<span id="cb46-2"><a href="#cb46-2"></a>ns_dat_lines <span class="sc">|&gt;</span> <span class="fu">pluck</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="fu">extract_dat_attrs</span>()</span>
<span id="cb46-3"><a href="#cb46-3"></a>ns_dat_lines <span class="sc">|&gt;</span> <span class="fu">pluck</span>(<span class="dv">20</span>) <span class="sc">|&gt;</span> <span class="fu">extract_dat_attrs</span>()</span>
<span id="cb46-4"><a href="#cb46-4"></a>ns_dat_lines <span class="sc">|&gt;</span> <span class="fu">pluck</span>(<span class="dv">100</span>) <span class="sc">|&gt;</span> <span class="fu">extract_dat_attrs</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  session_id  speaker_id state          session_seq
  &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;          &lt;chr&gt;      
1 ep-00-01-17 2099       United Kingdom 2          
# A tibble: 1 × 4
  session_id  speaker_id state          session_seq
  &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;          &lt;chr&gt;      
1 ep-00-01-17 1309       United Kingdom 40         
# A tibble: 1 × 4
  session_id  speaker_id state          session_seq
  &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;          &lt;chr&gt;      
1 ep-00-01-18 4549       United Kingdom 28         </code></pre>
</div>
</div>
</div>
<p>Looks like the <code>extract_dat_attrs()</code> function is ready for prime-time. Let’s now apply it to all of the line nodes in the <code>ns_dat_lines</code> object using the <code>map_dfr()</code> function from {purrr} as in <a href="#exm-curate-enntt-extract-attributes-all" class="quarto-xref">Example&nbsp;<span>6.19</span></a>.</p>
<div id="exm-curate-enntt-extract-attributes-all" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.19</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="co"># Extract attributes from all line nodes</span></span>
<span id="cb48-2"><a href="#cb48-2"></a>ns_dat_attrs <span class="ot">&lt;-</span></span>
<span id="cb48-3"><a href="#cb48-3"></a>  ns_dat_lines <span class="sc">|&gt;</span></span>
<span id="cb48-4"><a href="#cb48-4"></a>  <span class="fu">map_dfr</span>(extract_dat_attrs)</span>
<span id="cb48-5"><a href="#cb48-5"></a></span>
<span id="cb48-6"><a href="#cb48-6"></a><span class="co"># Inspect</span></span>
<span id="cb48-7"><a href="#cb48-7"></a><span class="fu">glimpse</span>(ns_dat_attrs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 116,341
Columns: 4
$ session_id  &lt;chr&gt; "ep-00-01-17", "ep-00-01-17", "ep-00-01-17", "ep-00-01-17"…
$ speaker_id  &lt;chr&gt; "2099", "2099", "2099", "4548", "4548", "4541", "4541", "4…
$ state       &lt;chr&gt; "United Kingdom", "United Kingdom", "United Kingdom", "Uni…
$ session_seq &lt;chr&gt; "2", "2", "2", "4", "4", "12", "12", "12", "12", "12", "12…</code></pre>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-medal" aria-label="medal"></i> Dive deeper</strong></p>
<p>The <code>map*()</code> functions from {purrr} are a family of functions that apply a function to each element of a vector, list, or data frame. The <code>map_dfr()</code> function is a variant of the <code>map()</code> function that returns a data frame that is the result of row-binding the results, hence <code>_dfr</code>.</p>
</div>
</div>
</div>
<p>We can see that the <code>ns_dat_attrs</code> object is a data frame with 116,341 rows and 4 columns, just has we expected. We can now combine the <code>ns_dat_attrs</code> data frame with the <code>ns_tok_lines</code> vector to create a single data frame with the attributes and the text. This is done with the <code>mutate()</code> function assigning the <code>ns_tok_lines</code> vector to a new column named <code>text</code> as in <a href="#exm-curate-enntt-combine-attributes-text" class="quarto-xref">Example&nbsp;<span>6.20</span></a>.</p>
<div id="exm-curate-enntt-combine-attributes-text" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.20</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="co"># Combine attributes and text</span></span>
<span id="cb50-2"><a href="#cb50-2"></a>ns_dat <span class="ot">&lt;-</span></span>
<span id="cb50-3"><a href="#cb50-3"></a>  ns_dat_attrs <span class="sc">|&gt;</span></span>
<span id="cb50-4"><a href="#cb50-4"></a>  <span class="fu">mutate</span>(<span class="at">text =</span> ns_tok_lines)</span>
<span id="cb50-5"><a href="#cb50-5"></a></span>
<span id="cb50-6"><a href="#cb50-6"></a><span class="co"># Inspect</span></span>
<span id="cb50-7"><a href="#cb50-7"></a><span class="fu">glimpse</span>(ns_dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 116,341
Columns: 5
$ session_id  &lt;chr&gt; "ep-00-01-17", "ep-00-01-17", "ep-00-01-17", "ep-00-01-17"…
$ speaker_id  &lt;chr&gt; "2099", "2099", "2099", "4548", "4548", "4541", "4541", "4…
$ state       &lt;chr&gt; "United Kingdom", "United Kingdom", "United Kingdom", "Uni…
$ session_seq &lt;chr&gt; "2", "2", "2", "4", "4", "12", "12", "12", "12", "12", "12…
$ text        &lt;chr&gt; "You will be aware from the press and television that ther…</code></pre>
</div>
</div>
</div>
<p>This is the data for the native speakers. We can now repeat this process for the non-native speakers, or we can create a function to do it for us.</p>
<div class="halfsize callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-lightbulb" aria-label="lightbulb"></i> Consider this</strong></p>
<p>Using the previous code as a guide, consider what steps you would need to take to create a function to combine the <em>.dat</em> and <em>.tok</em> files for the non-native speakers (and/ or the translations). What arguments would the function take? What would the function return? What would the processing steps be? In what order would the steps be executed?</p>
</div>
</div>
</div>
<p>After applying the curation steps to both the native and non-native datasets, we will have two data frames, <code>enntt_ns_df</code> and <code>enntt_nns_df</code>, respectively that meet the idealized structure for the curated ENNTT Corpus datasets, as shown in <a href="#tbl-curate-enntt-ideal" class="quarto-xref">Table&nbsp;<span>6.5</span></a>. The <code>enntt_ns_df</code> and <code>enntt_nns_df</code> data frames are ready to be written to disk and documented.</p>
</section></section><section id="documentation" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="documentation">
<span class="header-section-number">6.4</span> Documentation</h2>
<p>After applying the curation steps to our data, we will now want to write the dataset to disk and to do our best to document the process and the resulting dataset.</p>
<p>Since data frames are a tabular, we will have various options for the file type to write. Many of these formats are software-specific, such as <code>*.xlsx</code> for Microsoft Excel, <code>*.sav</code> for SPSS, <code>*.dta</code> for Stata, and <code>*.rds</code> for R. We will use the <code>*.csv</code> format since it is a common format that can be read by many software packages. We will use the <code>write_csv()</code> function from {readr} to write the dataset to disk.</p>
<p>Now the question is where to save our CSV file. Since our dataset is derived by our work, we will added it to the <em>derived/</em> directory. If you are working with multiple data sources within the same project, it is a good idea to create a subdirectory for each dataset. This will help keep the project organized and make it easier to find and access the datasets.</p>
<p>The final step, as always, is to provide documentation. For datasets the documentation is a data dictionary, as discussed in <a href="../part_2/2_data.html#sec-data-data-dictionaries" class="quarto-xref"><span>Section 2.3.2</span></a>. As with data origin files, you can use spreadsheet software to create and edit the data dictionary.</p>
<div class="halfsize callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-hand-point-up" aria-label="hand-point-up"></i> Tip</strong></p>
<p>The <code>create_data_dictionary()</code> function from {qtkit} provides a rudimentary data dictionary template by default. However, the <code>model</code> argument let’s you take advantage of OpenAI’s text generation models to generate a more detailed data dictionary for you to edit. See the function documentation for more information.</p>
</div>
</div>
</div>
<p>In {qtkit} we have a function, <code>create_data_dictionary()</code> that will generate the scaffolding for a data dictionary. The function takes two arguments, <code>data</code> and <code>file_path</code>. It reads the dataset columns and provides a template for the data dictionary.</p>
<p>An example of a data dictionary, a data dictionary for the <code>enntt_ns_df</code> dataset is shown in <a href="#tbl-curate-unstructured-data-dictionary-example" class="quarto-xref">Table&nbsp;<span>6.6</span></a>.</p>
<div class="cell" data-tbl-colwidths="[15,15,15,55]">
<div id="tbl-curate-unstructured-data-dictionary-example" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-curate-unstructured-data-dictionary-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.6: Data dictionary for the <code>enntt_ns_df</code> dataset
</figcaption><div aria-describedby="tbl-curate-unstructured-data-dictionary-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 55%">
</colgroup>
<thead><tr class="header">
<th>variable</th>
<th>name</th>
<th>type</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>session_id</td>
<td>Session ID</td>
<td>categorical</td>
<td>Unique identifier for each session</td>
</tr>
<tr class="even">
<td>speaker_id</td>
<td>Speaker ID</td>
<td>categorical</td>
<td>Unique identifier for each speaker</td>
</tr>
<tr class="odd">
<td>state</td>
<td>State</td>
<td>categorical</td>
<td>Name of the state or country the session is linked to</td>
</tr>
<tr class="even">
<td>session_seq</td>
<td>Session Sequence</td>
<td>ordinal</td>
<td>Sequence number in the session</td>
</tr>
<tr class="odd">
<td>text</td>
<td>Text</td>
<td>categorical</td>
<td>Text transcript of the session</td>
</tr>
<tr class="even">
<td>type</td>
<td>Type</td>
<td>categorical</td>
<td>The type of the speaker, whether native or nonnative</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section><section id="activities" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="activities">Activities</h2>
<p>The following activities build on your skills and knowledge to use R to read, inspect, and write data and datasets in R. In these activities you will have an opportunity to learn and apply your skills and knowledge to the task of curating datasets. This is a vital component of text analysis research that uses unstructured and semi-structured data.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-file-code" aria-label="file-code"></i> Recipe</strong></p>
<p><strong>What</strong>: Organizing and documenting datasets<br><strong>How</strong>: Read Recipe 6, complete comprehension check, and prepare for Lab 6.<br><strong>Why</strong>: To rehearse methods for deriving tidying datasets to use a the base for further project-specific purposes. We will explore how regular expressions are helpful in developing strategies for matching, extracting, and/ or replacing patterns in character sequences and how to organize datasets in rows and columns. We will also explore how to document datasets in a data dictionary.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-flask" aria-label="flask"></i> Lab</strong></p>
<p><strong>What</strong>: Taming data<br><strong>How</strong>: Fork, clone, and complete the steps in Lab 6.<br><strong>Why</strong>: To gain experience working with coding strategies to manipulate data using tidyverse functions and regular expressions, to practice reading/ writing data from/ to disk, and to implement organizational strategies for organizing and documenting a dataset in reproducible fashion.</p>
</div>
</div>
</div>
</section><section id="summary" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<p>In this chapter we looked at the process of structuring data into a dataset. This included a discussion on three main types of data –unstructured, structured, and semi-structured. The level of structure of the original data(set) will vary from resource to resource and by the same token so will the file format used to support the level of metadata included. The results from data curation results in a dataset that is saved separate from the original data to maintain modularity between what the data(set) looked like before we intervene and afterwards. Since there can be multiple analysis approaches applied the original data in a research project, this curated dataset serves as the point of departure for each of the subsequent datasets derived from the transformational steps. In addition to the code we use to derive the curated dataset’s structure, we also include a data dictionary which documents the curated dataset.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Ackoff1989" class="csl-entry" role="listitem">
Ackoff, R. L. (1989). From data to wisdom. <em>Journal of Applied Systems Analysis</em>, <em>16</em>(1), 3–9.
</div>
<div id="ref-R-languageR" class="csl-entry" role="listitem">
Baayen, R. H., &amp; Shafaei-Bajestan, E. (2019). <em><span class="nocase">languageR</span>: Analyzing linguistic data: A practical introduction to statistics</em>. Retrieved from <a href="https://CRAN.R-project.org/package=languageR">https://CRAN.R-project.org/package=languageR</a>
</div>
<div id="ref-R-readtext" class="csl-entry" role="listitem">
Benoit, K., &amp; Obeng, A. (2024). <em><span class="nocase">readtext</span>: Import and handling for plain and formatted text files</em>. Retrieved from <a href="https://CRAN.R-project.org/package=readtext">https://CRAN.R-project.org/package=readtext</a>
</div>
<div id="ref-Koehn2005" class="csl-entry" role="listitem">
Koehn, P. (2005). Europarl: A parallel corpus for statistical machine translation. <em>MT Summit X</em>, 12–16.
</div>
<div id="ref-Nisioi2016" class="csl-entry" role="listitem">
Nisioi, S., Rabinovich, E., Dinu, L. P., &amp; Wintner, S. (2016). A corpus of native, non-native and translated texts. In <em>Proceedings of the tenth international conference on language resources and evaluation (<span>LREC</span> 2016)</em>. Portoro<span>z̆</span>, Slovenia: European Language Resources Association (ELRA).
</div>
<div id="ref-R-jsonlite" class="csl-entry" role="listitem">
Ooms, J. (2023). <em><span class="nocase">jsonlite</span>: A simple and robust <span>JSON</span> parser and generator for <span>R</span></em>. Retrieved from <a href="https://jeroen.r-universe.dev/jsonlite">https://jeroen.r-universe.dev/jsonlite</a>
</div>
<div id="ref-R-DBI" class="csl-entry" role="listitem">
R Special Interest Group on Databases (R-SIG-DB), Wickham, H., &amp; Müller, K. (2024). <em><span>DBI</span>: R database interface</em>. Retrieved from <a href="https://dbi.r-dbi.org">https://dbi.r-dbi.org</a>
</div>
<div id="ref-Rowley2007" class="csl-entry" role="listitem">
Rowley, J. (2007). The wisdom hierarchy: <span>Representations</span> of the <span>DIKW</span> hierarchy. <em>Journal of Information Science</em>, <em>33</em>(2), 163–180. doi:<a href="https://doi.org/10.1177/0165551506070706">10.1177/0165551506070706</a>
</div>
<div id="ref-R-janeaustenr" class="csl-entry" role="listitem">
Silge, J. (2022). <em><span class="nocase">janeaustenr</span>: Jane <span>A</span>usten’s complete novels</em>. Retrieved from <a href="https://github.com/juliasilge/janeaustenr">https://github.com/juliasilge/janeaustenr</a>
</div>
<div id="ref-R-rvest" class="csl-entry" role="listitem">
Wickham, H. (2024). <em><span class="nocase">rvest</span>: Easily harvest (scrape) web pages</em>. Retrieved from <a href="https://rvest.tidyverse.org/">https://rvest.tidyverse.org/</a>
</div>
<div id="ref-R-dbplyr" class="csl-entry" role="listitem">
Wickham, H., Girlich, M., &amp; Ruiz, E. (2024). <em><span class="nocase">dbplyr</span>: A dplyr back end for databases</em>. Retrieved from <a href="https://dbplyr.tidyverse.org/">https://dbplyr.tidyverse.org/</a>
</div>
<div id="ref-R-purrr" class="csl-entry" role="listitem">
Wickham, H., &amp; Henry, L. (2023). <em><span class="nocase">purrr</span>: Functional programming tools</em>. Retrieved from <a href="https://purrr.tidyverse.org/">https://purrr.tidyverse.org/</a>
</div>
<div id="ref-R-haven" class="csl-entry" role="listitem">
Wickham, H., Miller, E., &amp; Smith, D. (2023). <em><span class="nocase">haven</span>: Import and export <span>SPSS</span>, <span>Stata</span> and <span>SAS</span> files</em>. Retrieved from <a href="https://haven.tidyverse.org">https://haven.tidyverse.org</a>
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../part_3/5_acquire.html" class="pagination-link" aria-label="Acquire">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Acquire</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../part_3/7_transform.html" class="pagination-link" aria-label="Transform">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Transform</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/qtalr/book/blob/main/part_3/6_curate.qmd" target="_blank" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/qtalr/book/edit/main/part_3/6_curate.qmd" target="_blank" class="toc-action"><i class="bi empty"></i>Edit this page</a></li><li><a href="https://github.com/qtalr/book/issues" target="_blank" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>