<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>An Introduction to Quantitative Text Analysis for Linguistics - 7&nbsp; Transform</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../part_4/index.html" rel="next">
<link href="../part_3/6_curate.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../assets/css/mini.css">
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span id="sec-transform-chapter" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Transform</span></span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">An Introduction to Quantitative Text Analysis for Linguistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/qtalr/book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../qtalr-manuscript.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part_1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Orientation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_1/1_text.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Text analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part_2/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_2/2_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_2/3_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_2/4_research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Research</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part_3/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preparation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_3/5_acquire.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Acquire</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_3/6_curate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Curate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_3/7_transform.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Transform</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part_4/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_4/8_explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Explore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_4/9_predict.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Predict</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_4/10_infer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part_5/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Communication</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part_5/11_contribute.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Contribute</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#sec-td-preparation" id="toc-sec-td-preparation" class="nav-link active" data-scroll-target="#sec-td-preparation"><span class="header-section-number">7.1</span> Preparation</a>
  <ul class="collapse">
<li><a href="#sec-td-normalization" id="toc-sec-td-normalization" class="nav-link" data-scroll-target="#sec-td-normalization">Normalization</a></li>
  <li><a href="#sec-td-tokenization" id="toc-sec-td-tokenization" class="nav-link" data-scroll-target="#sec-td-tokenization">Tokenization</a></li>
  </ul>
</li>
  <li>
<a href="#sec-td-enrichment" id="toc-sec-td-enrichment" class="nav-link" data-scroll-target="#sec-td-enrichment"><span class="header-section-number">7.2</span> Enrichment</a>
  <ul class="collapse">
<li><a href="#sec-td-generation" id="toc-sec-td-generation" class="nav-link" data-scroll-target="#sec-td-generation">Generation</a></li>
  <li><a href="#sec-td-recoding" id="toc-sec-td-recoding" class="nav-link" data-scroll-target="#sec-td-recoding">Recoding</a></li>
  <li><a href="#sec-td-integration" id="toc-sec-td-integration" class="nav-link" data-scroll-target="#sec-td-integration">Integration</a></li>
  </ul>
</li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/qtalr/book/blob/main/part_3/7_transform.qmd" target="_blank" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/qtalr/book/edit/main/part_3/7_transform.qmd" target="_blank" class="toc-action"><i class="bi empty"></i>Edit this page</a></li><li><a href="https://github.com/qtalr/book/issues" target="_blank" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title d-none d-lg-block"><span id="sec-transform-chapter" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Transform</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><blockquote class="blockquote">
<p>Nothing is lost. Everything is transformed.</p>
<p>— Michael Ende, The Neverending Story</p>
</blockquote>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-list-alt" aria-label="list-alt"></i> Outcomes</strong></p>
<!-- Remember and understand verbs: https://tips.uark.edu/blooms-taxonomy-verb-chart/ -->
<ul>
<li>Understand the role of data transformation in a text analysis project.</li>
<li>Identify the main types of transformations used to prepare datasets for analysis.</li>
<li>Recognize the importance of planning and documenting the transformation process.</li>
</ul>
</div>
</div>
</div>
<p>In this chapter, we will focus on transforming curated datasets to refine and possibly expand their relational characteristics to align with our research. I will approach the transformation process by breaking it down into two sub-processes: preparation and enrichment. The preparation process involves normalizing and tokenizing text. The enrichment process involves recoding, generating, and integrating variables. These processes are not sequential but may occur in any order based on the researcher’s evaluation of the dataset characteristics and the desired outcome.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-terminal" aria-label="terminal"></i> Lessons</strong></p>
<p><strong>What</strong>: <a href="https://github.com/qtalr/lessons">Reshape Datasets by Rows, Reshape datasets by Columns</a><br><strong>How</strong>: In an R console, load <code>swirl</code>, run <code>swirl()</code>, and follow prompts to select the lesson.<br><strong>Why</strong>: Explore data preprocessing skills to manipulate rows and columns using powerful packages like <code>dplyr</code> and <code>tidytext</code> to normalization, tokenize, and integrate datasets equipping you with the essential techniques to structure datasets for analysis.</p>
</div>
</div>
</div>
<section id="sec-td-preparation" class="level2" data-number="7.1"><h2 data-number="7.1" class="anchored" data-anchor-id="sec-td-preparation">
<span class="header-section-number">7.1</span> Preparation</h2>
<p>In this section we will cover the processes of normalization and tokenization. These processes are particularly relevant for text analysis, as text conventions can introduce unwanted variability in the data and the unit of observation may need to be adjusted to align with the research question.</p>
<p>To illustrate these processes, we will use a curated version of the Europarl Corpus <span class="citation" data-cites="Koehn2005">(<a href="../references.html#ref-Koehn2005" role="doc-biblioref">Koehn 2005</a>)</span>. This dataset contains transcribed source language (Spanish) and translated target language (English) from the proceedings of the European Parliament. The unit of observation is the <code>lines</code> variable whose values are lines of dialog. We will use this dataset to explore the normalization and tokenization processes.</p>
<p>The contents of the data dictionary for this dataset appears in <a href="#tbl-td-europarl-dd" class="quarto-xref">Table&nbsp;<span>7.1</span></a>.</p>
<div class="cell">
<div id="tbl-td-europarl-dd" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-td-europarl-dd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.1: Data dictionary for the curated Europarl Corpus.
</figcaption><div aria-describedby="tbl-td-europarl-dd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 60%">
</colgroup>
<thead><tr class="header">
<th>variable</th>
<th>name</th>
<th>variable_type</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>doc_id</td>
<td>Document ID</td>
<td>numeric</td>
<td>Unique identification number for each document</td>
</tr>
<tr class="even">
<td>type</td>
<td>Document Type</td>
<td>categorical</td>
<td>Type of document; either ‘Source’ (Spanish) or ‘Target’ (English)</td>
</tr>
<tr class="odd">
<td>line_id</td>
<td>Line ID</td>
<td>numeric</td>
<td>Unique identification number for each line in each document type</td>
</tr>
<tr class="even">
<td>lines</td>
<td>Lines</td>
<td>categorical</td>
<td>Content of the lines in the document</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Let’s read in the dataset CSV file with <code>read_csv()</code> and inspect the first lines of the dataset with <code>slice_head()</code> in <a href="#exm-tb-europarl-preview" class="quarto-xref">Example&nbsp;<span>7.1</span></a>.</p>
<div id="exm-tb-europarl-preview" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.1</strong></span> &nbsp;</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Read in the dataset</span></span>
<span><span class="va">europarl_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">read_csv</span><span class="op">(</span>file <span class="op">=</span> <span class="st">"../data/derived/europarl_curated.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Preview the first 10 lines</span></span>
<span><span class="va">europarl_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">slice_head</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 10 × 4
&gt;     doc_id type   line_id lines                                                 
&gt;      &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;                                                 
&gt;  1 1965735 Source       1 "Reanudación del período de sesiones"                 
&gt;  2       1 Target       1 "Resumption of the session"                           
&gt;  3 1965736 Source       2 "Declaro reanudado el período de sesiones del Parlame…
&gt;  4       2 Target       2 "I declare resumed the session of the European Parlia…
&gt;  5 1965737 Source       3 "Como todos han podido comprobar, el gran \"efecto de…
&gt;  6       3 Target       3 "Although, as you will have seen, the dreaded 'millen…
&gt;  7 1965738 Source       4 "Sus Señorías han solicitado un debate sobre el tema …
&gt;  8       4 Target       4 "You have requested a debate on this subject in the c…
&gt;  9 1965739 Source       5 "A la espera de que se produzca, de acuerdo con mucho…
&gt; 10       5 Target       5 "In the meantime, I should like to observe a minute' …</code></pre>
</div>
</div>
</div>
<p>This dataset includes 3,931,468 observations and four variables. The key variable for our purposes is the <code>lines</code> variable. This variable contains the text we will be working with. The other variables are metadata that may be of interest for our analyses.</p>
<section id="sec-td-normalization" class="level3"><h3 class="anchored" data-anchor-id="sec-td-normalization">Normalization</h3>
<p>The process of normalizing datasets in essence is to sanitize the values of variable or set of variables such that there are no artifacts that will contaminate subsequent processing. It may be the case that non-linguistic metadata may require normalization but more often than not linguistic information is the most common target for normalization as text often includes artifacts from the acquisition process which will not be desired in the analysis.</p>
<p>Simply looking at the first 10 lines of the dataset from <a href="#exm-tb-europarl-preview" class="quarto-xref">Example&nbsp;<span>7.1</span></a> gives us a clearer sense of the dataset structure, but, in terms of normalization procedures we might apply, it is likely not sufficient. We want to get a sense of any potential inconsistencies in the dataset, in particular in the <code>lines</code> variable. Since this is a large dataset with 3,931,468 observations, we will need to explore the dataset in more detail using procedures for summarizing and filtering data.</p>
<p>After exploring variations in the <code>lines</code> variable, I identified a number of artifacts in this dataset that we will want to consider addressing. These are included in <a href="#tbl-td-europarl-normalization" class="quarto-xref">Table&nbsp;<span>7.2</span></a>.</p>
<div id="tbl-td-europarl-normalization" class="sm striped quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-td-europarl-normalization-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.2: Characteristics of the Europarl Corpus dataset that may require normalization.
</figcaption><div aria-describedby="tbl-td-europarl-normalization-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-sm table-striped small table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Examples</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Non-speech annotations</td>
<td style="text-align: left;">
<code>(Abucheos)</code>, <code>(A4-0247/98)</code>, <code>(The sitting was opened at 09:00)</code>
</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inconsistent whitespace</td>
<td style="text-align: left;">
<code>5 % ,</code>, <code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>, <code>Palacio' s</code>
</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-sentence punctuation</td>
<td style="text-align: left;"><code>-</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Abbreviations</td>
<td style="text-align: left;">
<code>Mr.</code>, <code>Sr.</code>, <code>Mme.</code>, <code>Mr</code>, <code>Sr</code>, <code>Mme</code>, <code>Mister</code>, <code>Señor</code>, <code>Madam</code>
</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Text case</td>
<td style="text-align: left;">
<code>The</code>, <code>the</code>, <code>White</code>, <code>white</code>
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>These artifacts either may not be of interest or may introduce unwanted variability in the that could prove problematic for subsequent processing (<em>e.g</em> tokenization, calculating frequencies, <em>etc.</em>).</p>
<p>Identifying our normalization goals is an important first step. In this case, let’s just focus on removing parlimentary session descriptions for demonstration purposes. The next step is to identify the procedures that will accomplish this goal.</p>
<p>The majority of text normalization procedures incorporate the <code>stringr</code> package <span class="citation" data-cites="R-stringr">(<a href="../references.html#ref-R-stringr" role="doc-biblioref">Wickham 2023</a>)</span>. This package provides a number of functions for manipulating text strings. The workhorse functions we will use for our tasks are the <code><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove()</a></code> and <code><a href="https://stringr.tidyverse.org/reference/str_replace.html">str_replace()</a></code> functions. As the these functions give us the ability to remove or replace text based on literal strings and Regular Expressions.</p>
<p>Our first step, however, is to identify the patterns we want to remove or replace. For this, we can call on either the <code><a href="https://stringr.tidyverse.org/reference/str_view.html">str_view()</a></code> function or the <code><a href="https://stringr.tidyverse.org/reference/str_detect.html">str_detect()</a></code> function inside a <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function to identify the lines that contain the patterns we want to remove. We can also use the <code><a href="https://stringr.tidyverse.org/reference/str_extract.html">str_extract()</a></code> and/ or <code><a href="https://stringr.tidyverse.org/reference/str_extract.html">str_extract_all()</a></code> functions inside a <code>mutate()</code> function to extract the text that matches the pattern. In any of these cases, it can be helpful to use the <code>slice_sample()</code> function work with a small sample of the dataset to get a sense of the patterns we are working with as we develop a search pattern that does not over- or under-generalize the text we want to remove or replace. If we are too general, we may end up removing or replacing text that we want to keep. If we are too specific, we may not remove or replace all the text we want to remove or replace.</p>
<p>Let’s start by identifying non-parlimentary speech. In <a href="#exm-td-europarl-search-non-speech" class="quarto-xref">Example&nbsp;<span>7.2</span></a>, we use <code><a href="https://stringr.tidyverse.org/reference/str_detect.html">str_detect()</a></code> which detects a pattern in a character vector and returns a logical vector, <code>TRUE</code> if the pattern is detected and <code>FALSE</code> if it is not. In combination with <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> we can identify a variable with rows that match a pattern.</p>
<p>From the examples above, we can see that these instances are wrapped with parentheses <code>(</code> and <code>)</code>. The text within the parentheses can vary, so we need a Regular Expression to do the heavy lifting. To start out we can match any one or multiple characters with <code>.+</code>. But it is important to recognize the <code>+</code> (and also the <code>*</code>) operators are ‘greedy’, meaning that if there are multiple matches, the longest match will be returned. In this case, we want to match the shortest match. To do this we can use the <code>?</code> operator to make the <code>+</code> operator ‘lazy’. This will match the shortest match.</p>
<div id="exm-td-europarl-search-non-speech" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.2</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load package</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://stringr.tidyverse.org">stringr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Identify non-speech lines</span></span>
<span><span class="va">europarl_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_detect.html">str_detect</a></span><span class="op">(</span><span class="va">lines</span>, <span class="st">"\\(.+?\\)"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">slice_sample</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 10 × 4
&gt;     doc_id type   line_id lines                                                 
&gt;      &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;                                                 
&gt;  1 3225772 Source 1260038 (PT) Señor Presidente, quisiera plantear dos pregunta…
&gt;  2 3715842 Source 1750108 (El Parlamento decide la devolución a la Comisión)    
&gt;  3 1961715 Target 1961715 (Parliament adopted the resolution)                   
&gt;  4 1429470 Target 1429470 27, originally Greens/EFA amendment in FEMM); binding…
&gt;  5   51632 Target   51632 Question No 8 by (H-0376/00):                         
&gt;  6 2482671 Source  516937 La Comisión propone proporcionar a las Agencias nacio…
&gt;  7 1059628 Target 1059628 (The President cut off the speaker)                   
&gt;  8 1507254 Target 1507254 in writing. - (LT) I welcomed this document, because …
&gt;  9 2765325 Source  799591 (Aplausos)                                            
&gt; 10 2668536 Source  702802 &nbsp;&nbsp; Las preguntas que, por falta de tiempo, no han rec…</code></pre>
</div>
</div>
</div>
<p>The results from <a href="#exm-td-europarl-search-non-speech" class="quarto-xref">Example&nbsp;<span>7.2</span></a> show that we have identified the lines that contain at least one of the parliamentary session description annotations. A more targeted search to identify specific instances of the parliamentary session descriptions can be accomplished adding the <code><a href="https://stringr.tidyverse.org/reference/str_extract.html">str_extract_all()</a></code> function as seen in <a href="#exm-td-europarl-search-non-speech-2" class="quarto-xref">Example&nbsp;<span>7.3</span></a>.</p>
<div id="exm-td-europarl-search-non-speech-2" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.3</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Extract non-speech fragments</span></span>
<span><span class="va">europarl_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_detect.html">str_detect</a></span><span class="op">(</span><span class="va">lines</span>, <span class="st">"\\(.+?\\)"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>non_speech <span class="op">=</span> <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_extract.html">str_extract_all</a></span><span class="op">(</span><span class="va">lines</span>, <span class="st">"\\(.+?\\)"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">slice_sample</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 10 × 5
&gt;     doc_id type   line_id lines                                       non_speech
&gt;      &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;                                       &lt;list&gt;    
&gt;  1 3225772 Source 1260038 (PT) Señor Presidente, quisiera plantear d… &lt;chr [1]&gt; 
&gt;  2 3715842 Source 1750108 (El Parlamento decide la devolución a la C… &lt;chr [1]&gt; 
&gt;  3 1961715 Target 1961715 (Parliament adopted the resolution)         &lt;chr [1]&gt; 
&gt;  4 1429470 Target 1429470 27, originally Greens/EFA amendment in FEM… &lt;chr [1]&gt; 
&gt;  5   51632 Target   51632 Question No 8 by (H-0376/00):               &lt;chr [1]&gt; 
&gt;  6 2482671 Source  516937 La Comisión propone proporcionar a las Age… &lt;chr [2]&gt; 
&gt;  7 1059628 Target 1059628 (The President cut off the speaker)         &lt;chr [1]&gt; 
&gt;  8 1507254 Target 1507254 in writing. - (LT) I welcomed this documen… &lt;chr [1]&gt; 
&gt;  9 2765325 Source  799591 (Aplausos)                                  &lt;chr [1]&gt; 
&gt; 10 2668536 Source  702802 &nbsp;&nbsp; Las preguntas que, por falta de tiempo,… &lt;chr [1]&gt;</code></pre>
</div>
</div>
</div>
<p>OK, that might not be what you expected. The <code><a href="https://stringr.tidyverse.org/reference/str_extract.html">str_extract_all()</a></code> function returns a list of character vectors. This is because for any given line in <code>lines</code> there may be a different number of matches. To maintain the data frame as rectangular, a list is returned for each value of <code>non_speech</code>. We could expand the list into a data frame with the <code>unnest()</code> function from the <code>tidyr</code> package if our goal were to work with these matches. But that is not our aim. Rather, we want to know if we have multiple matches per line. Note that the information provided for the <code>non_speech</code> column by the tibble object tells use that we have some lines with muliple matches, as we can see in line 6 of our small sample. So good thing we checked!</p>
<p>Let’s now remove these parliamentary session description annotations from each line in the <code>lines</code> column. We turn to <code><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove_all()</a></code>, a variant of <code><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove()</a></code>, that, as you expect, will remove multiple matches in a single line. We will use the <code>mutate()</code> function to overwrite the <code>lines</code> column with the modified text. The code is seen in <a href="#exm-td-europarl-remove-non-speech" class="quarto-xref">Example&nbsp;<span>7.4</span></a>.</p>
<div id="exm-td-europarl-remove-non-speech" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.4</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Remove non-speech fragments</span></span>
<span><span class="va">europarl_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">europarl_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>lines <span class="op">=</span> <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove_all</a></span><span class="op">(</span><span class="va">lines</span>, <span class="st">"\\(.+?\\)"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>I recommend spot checking the results of this normalization step by running the code in <a href="#exm-td-europarl-search-non-speech" class="quarto-xref">Example&nbsp;<span>7.2</span></a> again, if nothing appears we’ve done our job.</p>
<p>When you are content with the results, drop the observations that have no text in the <code>lines</code> column given the entire line was non-speech. This can be done with the <code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code> function and the <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function as seen in <a href="#exm-td-europarl-drop-empty-lines" class="quarto-xref">Example&nbsp;<span>7.5</span></a>.</p>
<div id="exm-td-europarl-drop-empty-lines" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.5</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Drop empty lines</span></span>
<span><span class="va">europarl_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">europarl_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">lines</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>Normalization goals will vary from dataset to dataset but the procedures often follow a similar line of attack to those outlined in this section. There are cases, however, in which normalization procedures are more easily accomplished after subsequent transformation steps or need to be post-poned to further the goals of other transformation steps. For example, standardizing abbreviated forms may be more easily accomplished after tokenization when each token is a word. Another example is the case of case conversion. Even if we are not directly interested in the case differences between words, certain generation procedures, Named Entity Recognition (NER) for example, may use case information to identify the names of people, locations, organizations, <em>etc.</em>. In these cases, it may be better to leave the case as is until after the generation step.</p>
</section><section id="sec-td-tokenization" class="level3"><h3 class="anchored" data-anchor-id="sec-td-tokenization">Tokenization</h3>
<p>Another common transformation process that is particularly relevant for preparing text for analysis is tokenization. Tokenization is the process of segmenting units of language into components relevant for the research question. This includes breaking text in curated datasets into smaller units, such as words, <span class="math inline">\(n\)</span>-grams, sentences, <em>etc.</em> or combining text into larger units relative to the original text.</p>
<p>The process of tokenization is fundamentally row-wise. By scaling the text units up or down, we change the unit of observation. It is important both for the research and the text processing to operationalize our language units. For example, while it may appear obvious to you what ‘word’ or ‘sentence’ means, a computer, and your reproducible research, needs a definition. This can prove tricker than it seems. For example, in English, we can segment text into words by splitting on whitespace. This works fairly well but there are some cases where this is not ideal. For example, in the case of contractions, such as <code>don't</code>, <code>won't</code>, <code>can't</code>, <em>etc.</em> the apostrophe is not a whitespace character. If we want to consider these contractions as separate words, then we need to consider a different tokenization strategy.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-lightbulb" aria-label="lightbulb"></i> Consider this</strong></p>
<p>Consider the following paragraph:</p>
<blockquote class="blockquote">
<p>“As the sun dipped below the horizon, the sky was set ablaze with shades of orange-red, illuminating the landscape. It’s a sight Mr.&nbsp;Johnson, a long-time observer, never tired of. On the lakeside, he’d watch with friends, enjoying the ever-changing hues—especially those around 6:30 p.m.—and reflecting on nature’s grand display. Even in the half-light, the water’s glimmer, coupled with the echo of distant laughter, created a timeless scene. The so-called ‘magic hour’ was indeed magical, yet fleeting, like a well-crafted poem; it was the essence of life itself.”</p>
</blockquote>
<p>What text conventions would pose issues for word tokenization based on a whitespace critieron?</p>
</div>
</div>
</div>
<p>Furthermore, tokenization strategies can vary between languages. For German words are often compounded together, meaning many ‘words’ will not be captured by the whitespace convention. Whitespace may not even be relevant for word tokenization in logographic writing systems such as Chinese. The take home message is there is no one-size-fits-all tokenization strategy.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-medal" aria-label="medal"></i> Dive deeper</strong></p>
<p>For processing Chinese text, including tokenization, see the <code>jiebaR</code> package <span class="citation" data-cites="R-jiebaR">(<a href="../references.html#ref-R-jiebaR" role="doc-biblioref">Wenfeng and Yanyi 2019</a>)</span> and the <code>gibasa</code> package <span class="citation" data-cites="R-gibasa">(<a href="../references.html#ref-R-gibasa" role="doc-biblioref">Kato, Ichinose, and Kudo 2024</a>)</span>.</p>
</div>
</div>
</div>
<p>Let’s say we continue to work with the Europarl Corpus dataset. We have already removed non-speech annotations from the <code>lines</code> variable. Now we want to tokenize the text. We will start by tokenizing the text into words. If we envision what this should look like, we might imagine something like <a href="#tbl-td-europarl-tokenization-words-example" class="quarto-xref">Table&nbsp;<span>7.3</span></a>.</p>
<div id="tbl-td-europarl-tokenization-words-example" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-td-europarl-tokenization-words-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.3: Example of tokenizing the <code>lines</code> variable into word tokens.
</figcaption><div aria-describedby="tbl-td-europarl-tokenization-words-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead><tr class="header">
<th>doc_id</th>
<th>type</th>
<th>line_id</th>
<th>token</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Target</td>
<td>2</td>
<td>I</td>
</tr>
<tr class="even">
<td>1</td>
<td>Target</td>
<td>2</td>
<td>declare</td>
</tr>
<tr class="odd">
<td>1</td>
<td>Target</td>
<td>2</td>
<td>resumed</td>
</tr>
<tr class="even">
<td>1</td>
<td>Target</td>
<td>2</td>
<td>the</td>
</tr>
<tr class="odd">
<td>1</td>
<td>Target</td>
<td>2</td>
<td>session</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Comparing <a href="#tbl-td-europarl-tokenization-words-example" class="quarto-xref">Table&nbsp;<span>7.3</span></a> to the fourth row of the output of <a href="#exm-tb-europarl-preview" class="quarto-xref">Example&nbsp;<span>7.1</span></a>, we can see that we want to segment the words in <code>lines</code> and then have each segment appear as a separate observation, retaining the relevant metadata variables.</p>
<p>This is a very common strategy in text analysis. So common, in fact, that the <code>tidytext</code> package <span class="citation" data-cites="R-tidytext">(<a href="../references.html#ref-R-tidytext" role="doc-biblioref">Robinson and Silge 2023</a>)</span> includes a function, <code><a href="https://rdrr.io/pkg/tidytext/man/unnest_tokens.html">unnest_tokens()</a></code> that tokenizes text in just such a way. Various tokenization types can be specified including ‘characters’, ‘words’, ‘ngrams’, ‘sentences’ among others. We will use the ‘word’ tokenization type to recreate the structure we envisioned in <a href="#tbl-td-europarl-tokenization-words-example" class="quarto-xref">Table&nbsp;<span>7.3</span></a>.</p>
<p>In <a href="#exm-td-europarl-tokenization-words-tidytext" class="quarto-xref">Example&nbsp;<span>7.6</span></a>, we see set our output variable to <code>token</code> and our input variable to <code>lines</code>.</p>
<div id="exm-td-europarl-tokenization-words-tidytext" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.6</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load package</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/juliasilge/tidytext">tidytext</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Tokenize the lines into words</span></span>
<span><span class="va">europarl_unigrams_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">europarl_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tidytext/man/unnest_tokens.html">unnest_tokens</a></span><span class="op">(</span></span>
<span>    output <span class="op">=</span> <span class="va">token</span>,</span>
<span>    input <span class="op">=</span> <span class="va">lines</span>,</span>
<span>    token <span class="op">=</span> <span class="st">"words"</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>Let’s preview the very same lines we modeled in <a href="#tbl-td-europarl-tokenization-words-example" class="quarto-xref">Table&nbsp;<span>7.3</span></a> to see the results of our tokenization.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Preview</span></span>
<span><span class="va">europarl_unigrams_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">type</span> <span class="op">==</span> <span class="st">"Target"</span>, <span class="va">line_id</span> <span class="op">==</span> <span class="fl">2</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">slice_head</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 10 × 4
&gt;    doc_id type   line_id token     
&gt;     &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;     
&gt;  1      2 Target       2 i         
&gt;  2      2 Target       2 declare   
&gt;  3      2 Target       2 resumed   
&gt;  4      2 Target       2 the       
&gt;  5      2 Target       2 session   
&gt;  6      2 Target       2 of        
&gt;  7      2 Target       2 the       
&gt;  8      2 Target       2 european  
&gt;  9      2 Target       2 parliament
&gt; 10      2 Target       2 adjourned</code></pre>
</div>
</div>
<p>The <code>token</code> column now contains our word tokens. One thing to note, however, is that text is lowercased by default. If we want to retain the original case, keep the original variable, or change the tokenization strategy, we can update the <code>to_lower</code>, <code>drop</code>, and <code>token</code> parameters, respectively.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-medal" aria-label="medal"></i> Dive deeper</strong></p>
<p><code><a href="https://rdrr.io/pkg/tidytext/man/unnest_tokens.html">unnest_tokens()</a></code> approaches tokenization from a segmentation point of view. That is, the context separating our tokens is targeted and is removed. In some cases, it may be more feasible to turn the approach around and instead target the tokens to extract. The <code><a href="https://stringr.tidyverse.org/reference/str_extract.html">str_extract_all()</a></code> can be used for this purpose. Note, however, the former approach is often more effective and effecient. The later requires a regular expression, or set of, which can be tricky to develop for some tokenization tasks.</p>
</div>
</div>
</div>
<p>As we derive datasets to explore, let’s also create bigram tokens. We can do this by changing the <code>token</code> parameter to <code>"ngrams"</code> and specifying the value for <span class="math inline">\(n\)</span> with the <code>n</code> parameter. I will assign the result to <code>europarl_bigrams_tbl</code> as we will have two-word tokens, as seen in <a href="#exm-td-europarl-tokenization-bigrams-tidytext" class="quarto-xref">Example&nbsp;<span>7.7</span></a>.</p>
<div id="exm-td-europarl-tokenization-bigrams-tidytext" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.7</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Tokenize the lines into bigrams</span></span>
<span><span class="va">europarl_bigrams_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">europarl_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tidytext/man/unnest_tokens.html">unnest_tokens</a></span><span class="op">(</span></span>
<span>    output <span class="op">=</span> <span class="va">token</span>,</span>
<span>    input <span class="op">=</span> <span class="va">lines</span>,</span>
<span>    token <span class="op">=</span> <span class="st">"ngrams"</span>,</span>
<span>    n <span class="op">=</span> <span class="fl">2</span></span>
<span>  <span class="op">)</span></span>
<span><span class="co"># Preview</span></span>
<span><span class="va">europarl_bigrams_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">type</span> <span class="op">==</span> <span class="st">"Target"</span>, <span class="va">line_id</span> <span class="op">==</span> <span class="fl">2</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">slice_head</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 10 × 4
&gt;    doc_id type   line_id token               
&gt;     &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;               
&gt;  1      2 Target       2 i declare           
&gt;  2      2 Target       2 declare resumed     
&gt;  3      2 Target       2 resumed the         
&gt;  4      2 Target       2 the session         
&gt;  5      2 Target       2 session of          
&gt;  6      2 Target       2 of the              
&gt;  7      2 Target       2 the european        
&gt;  8      2 Target       2 european parliament 
&gt;  9      2 Target       2 parliament adjourned
&gt; 10      2 Target       2 adjourned on</code></pre>
</div>
</div>
</div>
<p>The two-word token sequences for lines appear as observations in the <code>europarl_bigrams_tbl</code> dataset.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-medal" aria-label="medal"></i> Dive deeper</strong></p>
<p>The <code>tidytext</code> package is one of a number of packages that provide tokenization functions. Some other notable packages include <code>tokenizers</code> <span class="citation" data-cites="R-tokenizers">(<a href="../references.html#ref-R-tokenizers" role="doc-biblioref">Mullen 2022</a>)</span> and <code>textrecipes</code> <span class="citation" data-cites="R-textrecipes">(<a href="../references.html#ref-R-textrecipes" role="doc-biblioref">Hvitfeldt 2023</a>)</span>. In fact, the functions from the <code>tokenizers</code> package are used under the hood in the <code>tidytext</code> package. The <code>textrecipes</code> package is part of the <code>tidymodels</code> framework and is designed to work with the <code>tidymodels</code> suite of packages. It is particularly useful for integrating tokenization with other preprocessing steps and machine learning models, as we will see in <a href="../part_4/9_predict.html" class="quarto-xref"><span>Chapter 9</span></a>.</p>
</div>
</div>
</div>
<p>The most common tokenization strategy is to segment text into smaller units, often words. However, there are times when we may want text segements to be larger than the existing token unit, effectively collapsing over rows. For example, if we are working with a curated dataset which is tokenized by words, we may want to group the words into sentences. A couple considerations are in order, however. First, we need to be clear about what we mean by ‘sentence’ and how we will group the words into sentences. In some cases key cues for sentence boundaries, such as sentencial punctuation have been stripped from the text, making a simple defnition of a sentence difficult or impossible to be performed computationally. Second, we also need to be clear how we will handle the metadata variables. In other words, when we collapse over rows, we need to be aware and intentional about how we group these new units of observation.</p>
</section></section><section id="sec-td-enrichment" class="level2" data-number="7.2"><h2 data-number="7.2" class="anchored" data-anchor-id="sec-td-enrichment">
<span class="header-section-number">7.2</span> Enrichment</h2>
<p>Where preparation steps are focused on sanitizing and segmenting the text, enrichment steps are aimed towards augmenting the dataset either through recoding, generating, or integrating variables. These processes can prove invaluable for aligning the dataset with the research question and facilitating the analysis.</p>
<p>As a pratical example of these types of transformations, we’ll posit that we are conducting translation research. Specifically, we will set up an investigation into the effect of translation on the syntactic simplification of text. The basic notion is that when translators translate text from one language to another, they subconsciously simplify the text, relative to native texts <span class="citation" data-cites="Liu2021">(<a href="../references.html#ref-Liu2021" role="doc-biblioref">Liu and Afzaal 2021</a>)</span>.</p>
<p>To address this research question, we will use the ENNTT corpus, introduced in <a href="6_curate.html#sec-cd-semi-structured-orientation" class="quarto-xref"><span>Section 6.3.2</span></a>. This data contains European Parliament proceedings and the type of text (native, non-native, or translation) from which the text was extracted. There is one curated dataset for each of the text types.</p>
<p>The data dictionary for the curated native dataset appears in <a href="#tbl-td-enntt-native-dd" class="quarto-xref">Table&nbsp;<span>7.4</span></a>.</p>
<div class="cell">
<div id="tbl-td-enntt-native-dd" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-td-enntt-native-dd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.4: Data dictionary for the curated native ENNTT dataset.
</figcaption><div aria-describedby="tbl-td-enntt-native-dd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 48%">
</colgroup>
<thead><tr class="header">
<th>variable</th>
<th>name</th>
<th>variable_type</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>session_id</td>
<td>Session ID</td>
<td>categorical</td>
<td>Unique identifier for each session</td>
</tr>
<tr class="even">
<td>speaker_id</td>
<td>Speaker ID</td>
<td>categorical</td>
<td>Unique identifier for each speaker</td>
</tr>
<tr class="odd">
<td>state</td>
<td>State</td>
<td>categorical</td>
<td>The country or region the speaker is from</td>
</tr>
<tr class="even">
<td>session_seq</td>
<td>Session Sequence</td>
<td>ordinal</td>
<td>The order in which the session occurred</td>
</tr>
<tr class="odd">
<td>text</td>
<td>Text</td>
<td>categorical</td>
<td>The spoken text during the session</td>
</tr>
<tr class="even">
<td>type</td>
<td>Type</td>
<td>categorical</td>
<td>The type of speaker. Natives in this dataset.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>All three curated datasets have the same variables. The unit of observation for each dataset is the <code>text</code> variable.</p>
<p>Before we get started, let’s consider what the transformed dataset might look like and what its variables mean. First, we will need to operationalize what we mean by syntactic simplification There are many measures of syntactic complexity <span class="citation" data-cites="Szmrecsanyi2004">(<a href="../references.html#ref-Szmrecsanyi2004" role="doc-biblioref">Szmrecsanyi 2004</a>)</span>. For our purposes, we will focus on two measures of syntactic complexity: number of T-units and sentence length (in words). A T-unit is a main clause and all of its subordinate clauses. To calculate the number of T-units, we will need to identify the main clauses and their subordinate clauses. The sentence length is straightforward to calculate after word tokenization.</p>
<p>An idealized transformed dataset dictionary for this investigation should look something like <a href="#tbl-td-generation-idealized" class="quarto-xref">Table&nbsp;<span>7.5</span></a>.</p>
<div class="cell" data-tbl-colwidths="[10,17,19,54]">
<div id="tbl-td-generation-idealized" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-td-generation-idealized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.5: Idealized transformed dataset for the syntactic simplification investigation.
</figcaption><div aria-describedby="tbl-td-generation-idealized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 19%">
<col style="width: 54%">
</colgroup>
<thead><tr class="header">
<th>variable</th>
<th>variable_name</th>
<th>variable_type</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>doc_id</td>
<td>Document ID</td>
<td>integer</td>
<td>Unique identifier for each document.</td>
</tr>
<tr class="even">
<td>type</td>
<td>Type</td>
<td>character</td>
<td>Type of text (native or translated).</td>
</tr>
<tr class="odd">
<td>t_units</td>
<td>T-units</td>
<td>integer</td>
<td>Number of T-units in the text.</td>
</tr>
<tr class="even">
<td>word_len</td>
<td>Word Length</td>
<td>integer</td>
<td>Number of words in the text.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We will be using the the native and translated datasets for our purposes so let’s go ahead and read in these datasets.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Read in curated natives</span></span>
<span><span class="va">enntt_natives_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">read_csv</span><span class="op">(</span><span class="st">"data/enntt_natives_curated.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Read in curated translations</span></span>
<span><span class="va">enntt_translations_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">read_csv</span><span class="op">(</span><span class="st">"data/enntt_translations_curated.csv"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="sec-td-generation" class="level3"><h3 class="anchored" data-anchor-id="sec-td-generation">Generation</h3>
<p>The process of generation involves the addition of information to a dataset. This differs from other transformation procedures in that instead of manipulating, classifying, and/ or deriving information based on characteristics explicit in a dataset, generation involves deriving new information based on characteristics implicit in a dataset.</p>
<p>The most common type of operation involved in the generation process is the addition of linguistic annotation. This process can be accomplished manually by a researcher or research team or automatically through the use of pre-trained linguistic resources and/ or software. Ideally, the annotation of linguistic information can be conducted automatically. It is important to note, however, that the quality of the annotations is contingent on the quality of the pre-trained resources, their alignment with the language variety and register to be annotated, and the quality of the text to be annotated. To be clear, no annotation method, whether manual or automatic is guaranteed to be perfectly accurate, but we must be aware of the limitations of the annotation method we choose.</p>
<p>To identify the main clauses and their subordinate clauses in our datasets, we will need to derive syntactic annotation information from the ENNTT <code>text</code> variable.</p>
<p>As fun as it would be to hand-annotate the ENNTT corpus, we will instead turn to automatic linguistic annotation. Specifically, we will use the <code>udpipe</code> package <span class="citation" data-cites="R-udpipe">(<a href="../references.html#ref-R-udpipe" role="doc-biblioref">Wijffels 2023</a>)</span> which provides an interface for annotating text using pre-trained models from the <a href="https://universaldependencies.org/">Universal Dependencies</a> (UD) project <span class="citation" data-cites="Nivre2020">(<a href="../references.html#ref-Nivre2020" role="doc-biblioref">Nivre et al. 2020</a>)</span>. The UD project is an effort to develop cross-linguistically consistent treebank annotation for a variety of languages.</p>
<p>Our first step, then, is to peruse the available pre-trained models for the languages we are interested in and selected the most register-aligned models. The models, model names, and licensing information are documented in the <code>udpipe</code> package and can be accessed by running <code>?udpipe::udpipe_download_model()</code> in the R console. For illustrative purposes, the <code>english</code> treebank model from the <em>https://github.com/bnosac/udpipe.models.ud</em> repository which is released under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA license</a>. This model is trained on various sources including news, Wikipedia, and web data of various genres.</p>
<p>Let’s set the stage by providing an overview of the annotation process.</p>
<ol type="1">
<li>Load the <code>udpipe</code> package.</li>
<li>Select the pre-trained model to use and the directory where the model will be stored in your local environment.</li>
<li>Prepare the dataset to be annotated (if necessary). This includes ensuring that the dataset has a column of text to be annotated and a grouping column. By default, the names of these columns are expected to be <code>text</code> and <code>doc_id</code>, respectively. The <code>text</code> column needs to be a character vector and the <code>doc_id</code> column needs to be a unique index for each text to be annotated.</li>
<li>Annotate the dataset. The result returns a data frame.</li>
</ol>
<p>Steps 3 and 4 are repeated for the <code>enntt_natives_tbl</code> and the <code>enntt_translations_tbl</code> datasets. For brevity, I will only show the code for the dataset for the natives. Additionally, I will subset the dataset to 10,000 randomly selected lines for both datasets, as in <a href="#exm-td-generation-subset-natives" class="quarto-xref">Example&nbsp;<span>7.8</span></a> for the natives. Syntactic annotation is a computationally expensive operation and the natives and translations datasets contain 116,341 and 738,597 observations, respectively.</p>
<div id="exm-td-generation-subset-natives" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.8</strong></span> &nbsp;</p>
</div>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-medal" aria-label="medal"></i> Dive deeper</strong> Computational Performance</p>
<p>In your own research computationally expensive cannot be avoided, but it can be managed. One strategy is to work with a subset of the data until your code is working as expected. Once you are confident that your code is working as expected, then you can scale up to the full dataset.</p>
<p>If you are using Quarto, you can use the <code>cache: true</code> metadata field in your code blocks to cache the results of computationally expensive code blocks. This will allow you to run your code once and then use the cached results for subsequent runs.</p>
<p>Parallel processing is another strategy for managing computationally expensive code. Some packages, such as <code>udpipe</code>, have built-in support for parallel processing. Other packages, such as <code>tidytext</code>, do not. In these cases, you can use the <code>future</code> package <span class="citation" data-cites="R-future">(<a href="../references.html#ref-R-future" role="doc-biblioref">Bengtsson 2023</a>)</span> to parallelize your code.</p>
</div>
</div>
</div>
<p>With the subsetted <code>enntt_natives_tbl</code> object, let’s execute steps 1-4, as seen in <a href="#exm-td-generation-udpipe-natives" class="quarto-xref">Example&nbsp;<span>7.9</span></a>.</p>
<div id="exm-td-generation-udpipe-natives" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.9</strong></span> &nbsp;</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load package</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://bnosac.github.io/udpipe/en/index.html">udpipe</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Model and directory</span></span>
<span><span class="va">model</span> <span class="op">&lt;-</span> <span class="st">"english"</span></span>
<span><span class="va">model_dir</span> <span class="op">&lt;-</span> <span class="st">"../data/"</span></span>
<span></span>
<span><span class="co"># Prepare the dataset to be annotated</span></span>
<span><span class="va">enntt_natives_prepped_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">enntt_natives_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>doc_id <span class="op">=</span> <span class="fu">row_number</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">doc_id</span>, <span class="va">text</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Annotate the dataset</span></span>
<span><span class="va">enntt_natives_ann_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/udpipe/man/udpipe.html">udpipe</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">enntt_natives_prepped_tbl</span>,</span>
<span>    object <span class="op">=</span> <span class="va">model</span>,</span>
<span>    model_dir <span class="op">=</span> <span class="va">model_dir</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">tibble</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Preview</span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">enntt_natives_ann_tbl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&gt; Rows: 264,124
&gt; Columns: 17
&gt; $ doc_id        &lt;chr&gt; "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "…
&gt; $ paragraph_id  &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
&gt; $ sentence_id   &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
&gt; $ sentence      &lt;chr&gt; "It is extremely important that action is taken to ensur…
&gt; $ start         &lt;int&gt; 1, 4, 7, 17, 27, 32, 39, 42, 48, 51, 58, 63, 66, 73, 77,…
&gt; $ end           &lt;int&gt; 2, 5, 15, 25, 30, 37, 40, 46, 49, 56, 61, 64, 71, 75, 82…
&gt; $ term_id       &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
&gt; $ token_id      &lt;chr&gt; "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11",…
&gt; $ token         &lt;chr&gt; "It", "is", "extremely", "important", "that", "action", …
&gt; $ lemma         &lt;chr&gt; "it", "be", "extremely", "important", "that", "action", …
&gt; $ upos          &lt;chr&gt; "PRON", "AUX", "ADV", "ADJ", "SCONJ", "NOUN", "AUX", "VE…
&gt; $ xpos          &lt;chr&gt; "PRP", "VBZ", "RB", "JJ", "IN", "NN", "VBZ", "VBN", "TO"…
&gt; $ feats         &lt;chr&gt; "Case=Nom|Gender=Neut|Number=Sing|Person=3|PronType=Prs"…
&gt; $ head_token_id &lt;chr&gt; "4", "4", "4", "0", "8", "8", "8", "4", "10", "8", "13",…
&gt; $ dep_rel       &lt;chr&gt; "expl", "cop", "advmod", "root", "mark", "nsubj:pass", "…
&gt; $ deps          &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
&gt; $ misc          &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …</code></pre>
</div>
</div>
</div>
<p>There is quite a bit of information which is returned from <code><a href="https://rdrr.io/pkg/udpipe/man/udpipe.html">udpipe()</a></code>. Note that the input lines have been tokenized by word. Each token includes the <code>token</code>, <code>lemma</code>, part of speech (<code>upos</code> and <code>xpos</code>), morphological features (<code>feats</code>), and syntactic relationships (<code>head_token_id</code> and <code>dep_rel</code>). The <code>token_id</code> keeps track of the token’s position in the sentence and the <code>sentence_id</code> keeps track of the sentence’s position in the original text. Finally, the <code>doc_id</code> column and its values correspond to the <code>doc_id</code> in the <code>enntt_natives_tbl</code> dataset.</p>
<p>The number of variables in the <code><a href="https://rdrr.io/pkg/udpipe/man/udpipe.html">udpipe()</a></code> annotation output is quite overwhelming. However, these attributes come in handy for manipulating, extracting, and plotting information based on lexical and syntactic patterns. See the dependency tree in <a href="#fig-td-generation-udpipe-english-plot-tree" class="quarto-xref">Figure&nbsp;<span>7.1</span></a> for an example of the syntactic information that can be extracted from the <code><a href="https://rdrr.io/pkg/udpipe/man/udpipe.html">udpipe()</a></code> annotation output.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-td-generation-udpipe-english-plot-tree" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-td-generation-udpipe-english-plot-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="7_transform_files/figure-html/fig-td-generation-udpipe-english-plot-tree-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-td-generation-udpipe-english-plot-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Plot of the syntactic tree for a sentence in the ENNTT natives dataset.
</figcaption></figure>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-medal" aria-label="medal"></i> Dive deeper</strong></p>
<p>The plot in <a href="#fig-td-generation-udpipe-english-plot-tree" class="quarto-xref">Figure&nbsp;<span>7.1</span></a> was created using the <code>rsyntax</code> package <span class="citation" data-cites="R-rsyntax">(<a href="../references.html#ref-R-rsyntax" role="doc-biblioref">Welbers and van Atteveldt 2022</a>)</span>. In addition to creating dependency tree plots, the <code>rsyntax</code> package can be used to extract syntactic patterns from the <code><a href="https://rdrr.io/pkg/udpipe/man/udpipe.html">udpipe()</a></code> annotation output. <a href="https://github.com/vanatteveldt/rsyntax">See the documentation for more information</a>.</p>
</div>
</div>
</div>
<p>In <a href="#fig-td-generation-udpipe-english-plot-tree" class="quarto-xref">Figure&nbsp;<span>7.1</span></a> we see the syntactic tree for a sentence in the ENNTT natives dataset. Each node is labeled with the <code>token_id</code> which provides the linear ordering of the sentence. Above the nodes the <code>dep_relation</code>, or dependency relationship label is provided. These labels are based on the UD project’s <a href="https://universaldependencies.org/u/dep/index.html">dependency relations</a>. We can see that the ‘ROOT’ relation is at the top of the tree and corresponds to the verb ‘brought’. ‘ROOT’ relations mark predicates in the sentence. Not seen in the example tree, ‘cop’ relation is a copular, or non-verbal predicate and should be included. These are the key syntactic pattern we will use to identify main clauses for T-units.</p>
</section><section id="sec-td-recoding" class="level3"><h3 class="anchored" data-anchor-id="sec-td-recoding">Recoding</h3>
<p>Recoding processes can be characterized by the creation of structural changes which are derived from values in variables effectively recasting values as new variables to enable more direct access in our analyses.</p>
<p>Specifically, we will need to identify and count the main clauses and their subordinate clauses to create a variable <code>t_units</code> from our natives and translations annotations objects. In the UD project’s listings, the relations ‘ccomp’ (clausal complement), ‘xcomp’ (open clausal complement), and ‘acl:relcl’ (relative clause), as seen in <a href="#fig-td-generation-udpipe-english-plot-tree" class="quarto-xref">Figure&nbsp;<span>7.1</span></a> are subordinate clauses. Furthermore, we will also need to count the number of words in each sentence to create a variable <code>word_len</code>.</p>
<p>To calculate T-units and words per sentence we turn to the <code>dplyr</code> package. We will use the <code>group_by()</code> function to group the dataset by <code>doc_id</code> and <code>sentence_id</code> and then use the <code>summarize()</code> function to calculate the number of T-units and words per sentence, where a T-unit is the combination of the sum of main clauses and sum of subordinante clauses. The code is seen in <a href="#exm-td-generation-udpipe-natives-tunits-words" class="quarto-xref">Example&nbsp;<span>7.10</span></a>.</p>
<div id="exm-td-generation-udpipe-natives-tunits-words" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.10</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculate the number of T-units and words per sentence</span></span>
<span><span class="va">enntt_natives_syn_comp_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">enntt_natives_ann_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">doc_id</span>, <span class="va">sentence_id</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span></span>
<span>    main_clauses <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">dep_rel</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ROOT"</span>, <span class="st">"cop"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    subord_clauses <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">dep_rel</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ccomp"</span>, <span class="st">"xcomp"</span>, <span class="st">"acl:relcl"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    t_units <span class="op">=</span> <span class="va">main_clauses</span> <span class="op">+</span> <span class="va">subord_clauses</span>,</span>
<span>    word_len <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">ungroup</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Preview</span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">enntt_natives_syn_comp_tbl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; Rows: 10,199
&gt; Columns: 6
&gt; $ doc_id         &lt;chr&gt; "1", "10", "100", "1000", "10000", "1001", "1002", "100…
&gt; $ sentence_id    &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
&gt; $ main_clauses   &lt;int&gt; 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 1, 1, 1, 0, 2, 0, 1, 1, 1…
&gt; $ subord_clauses &lt;int&gt; 3, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 0, 3, 2, 0, 4, 2, 1, 1…
&gt; $ t_units        &lt;int&gt; 4, 2, 1, 0, 3, 2, 1, 2, 1, 2, 2, 1, 4, 2, 2, 4, 3, 2, 2…
&gt; $ word_len       &lt;int&gt; 21, 25, 27, 15, 40, 43, 29, 23, 13, 30, 33, 9, 68, 35, …</code></pre>
</div>
</div>
</div>
<p>A quick spot check of some sentences calculations <code>enntt_natives_syn_comp_tbl</code> dataset against the <code>enntt_natives_ann_tbl</code> is good to ensure that the calculation is working as expected. In <a href="#fig-td-generation-udpipe-natives-tunits" class="quarto-xref">Figure&nbsp;<span>7.2</span></a> we see a sentence that has a word length of 13 and a T-unit value of 5.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-td-generation-udpipe-natives-tunits" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-td-generation-udpipe-natives-tunits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="7_transform_files/figure-html/fig-td-generation-udpipe-natives-tunits-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-td-generation-udpipe-natives-tunits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.2: Sentence with a word length of 13 and a T-unit value of 5.
</figcaption></figure>
</div>
</div>
</div>
<p>Now we can drop the intermediate columns we created to calculate our key syntactic complexity measures using <code>select()</code> to indicate those that we do want to keep, as seen in <a href="#exm-td-generation-udpipe-natives-tunits-words-select" class="quarto-xref">Example&nbsp;<span>7.11</span></a>.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-lightbulb" aria-label="lightbulb"></i> Consider this</strong></p>
<p>As confident as we may be in our recoding process, it is always a good idea to perform some data checks to ensure that the recoding process was successful. In the process, we can also gain some insight into the data. Considering the structure in the transformed ENNTT Corpus dataset, what are some data checks we might want to perform? What are some insights we might gain from these data checks?</p>
</div>
</div>
</div>
<div id="exm-td-generation-udpipe-natives-tunits-words-select" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.11</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Select columns</span></span>
<span><span class="va">enntt_natives_syn_comp_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">enntt_natives_syn_comp_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">doc_id</span>, <span class="va">sentence_id</span>, <span class="va">t_units</span>, <span class="va">word_len</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>Now we can repeat the process for the ENNTT translated dataset. I will assign the result to <code>enntt_translations_syn_comp_tbl</code>. The next step is to join the <code>sentences</code> from the annotated data frames into our datasets so that we have the information we set out to generate for both datasets. Then we will combine the native and translations datasets into a single dataset. These steps are part of the transformation process and will be covered in the next section.</p>
</section><section id="sec-td-integration" class="level3"><h3 class="anchored" data-anchor-id="sec-td-integration">Integration</h3>
<p>One final class of transformations that can be applied to curated datasets to enhance their informativeness for a research project is the process of integrating two or more datasets. There are two primary types of integrations: joins and concatenation. <strong>Joins</strong> can be row- or column-wise operations that combine datasets based on a common attribute or set of attributes. <strong>Concatenation</strong> is exclusively a row-wise operation that combines datasets that share the same attributes.</p>
<p>Of the two types, joins are the most powerful and sometimes more difficult to understand. When two datasets are joined at least one common variable must be shared between the two datasets. The common variable(s) are referred to as <strong>keys</strong>. The keys are used to match observations in one dataset with observations in another dataset by serving as an index.</p>
<p>There are a number of join types. The most common are left, full, semi, and anti. The type of join determines which observations are retained in the resulting dataset. Let’s see this in practice. First, let’s create two datasets to join with a common variable <code>key</code>, as seen in <a href="#exm-td-merging-join-dfs" class="quarto-xref">Example&nbsp;<span>7.12</span></a>.</p>
<div id="exm-td-merging-join-dfs" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.12</strong></span> &nbsp;</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">a_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">tibble</span><span class="op">(</span></span>
<span>    key <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">5</span>, <span class="fl">8</span><span class="op">)</span>,</span>
<span>    a <span class="op">=</span> <span class="va">letters</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">5</span><span class="op">]</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">a_tbl</span></span>
<span><span class="va">b_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">tibble</span><span class="op">(</span></span>
<span>    key <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">4</span>, <span class="fl">6</span>, <span class="fl">8</span><span class="op">)</span>,</span>
<span>    b <span class="op">=</span> <span class="va">letters</span><span class="op">[</span><span class="fl">6</span><span class="op">:</span><span class="fl">10</span><span class="op">]</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">b_tbl</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-layout-panel" data-layout="[50, 50]">
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="first" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 5 × 2
&gt;     key a    
&gt;   &lt;dbl&gt; &lt;chr&gt;
&gt; 1     1 a    
&gt; 2     2 b    
&gt; 3     3 c    
&gt; 4     5 d    
&gt; 5     8 e</code></pre>
</div>
</div>
</div>
<div id="second" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 5 × 2
&gt;     key b    
&gt;   &lt;dbl&gt; &lt;chr&gt;
&gt; 1     1 f    
&gt; 2     2 g    
&gt; 3     4 h    
&gt; 4     6 i    
&gt; 5     8 j</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The <code>a_tbl</code> and the <code>b_tbl</code> datasets share the <code>key</code> variable, but the values in the <code>key</code> variable are not identical. The two datasets share values <code>1</code>, <code>2</code>, and <code>8</code>. The <code>a_tbl</code> dataset has values <code>3</code> and <code>5</code> in the <code>key</code> variable and the <code>b_tbl</code> dataset has values <code>4</code> and <code>6</code> in the <code>key</code> variable.</p>
<p>If we apply a left join to the <code>a_tbl</code> and <code>b_tbl</code> datasets, the result will be a dataset that retains all of the observations in the <code>a_tbl</code> dataset and only those observations in the <code>b_tbl</code> dataset that have a match in the <code>a_tbl</code> dataset. The result is seen in <a href="#exm-td-merging-join-left" class="quarto-xref">Example&nbsp;<span>7.13</span></a>.</p>
<div id="exm-td-merging-join-left" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.13</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">left_join</span><span class="op">(</span>x <span class="op">=</span> <span class="va">a_tbl</span>, y <span class="op">=</span> <span class="va">b_tbl</span>, by <span class="op">=</span> <span class="st">"key"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 5 × 3
&gt;     key a     b    
&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;
&gt; 1     1 a     f    
&gt; 2     2 b     g    
&gt; 3     3 c     &lt;NA&gt; 
&gt; 4     5 d     &lt;NA&gt; 
&gt; 5     8 e     j</code></pre>
</div>
</div>
</div>
<p>Now, if the key variable has the same name, R will recognize and assume that this is the variable to join on and we don’t need the <code>by =</code> argument, but if there are multiple potential key variables, we use <code>by =</code> to specify which one to use.</p>
<p>A full join retains all observations in both datasets, as seen in <a href="#exm-td-merging-join-full" class="quarto-xref">Example&nbsp;<span>7.14</span></a>.</p>
<div id="exm-td-merging-join-full" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.14</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">full_join</span><span class="op">(</span>x <span class="op">=</span> <span class="va">a_tbl</span>, y <span class="op">=</span> <span class="va">b_tbl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 7 × 3
&gt;     key a     b    
&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;
&gt; 1     1 a     f    
&gt; 2     2 b     g    
&gt; 3     3 c     &lt;NA&gt; 
&gt; 4     5 d     &lt;NA&gt; 
&gt; 5     8 e     j    
&gt; 6     4 &lt;NA&gt;  h    
&gt; 7     6 &lt;NA&gt;  i</code></pre>
</div>
</div>
</div>
<p>Left and full joins maintain or increase the number of observations. On the other hand, semi and anti joins aim to decrease the number of observations. A semi join retains only those observations in the left dataset that have a match in the right dataset, as seen in <a href="#exm-td-merging-join-semi" class="quarto-xref">Example&nbsp;<span>7.15</span></a>.</p>
<div id="exm-td-merging-join-semi" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.15</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">semi_join</span><span class="op">(</span>x <span class="op">=</span> <span class="va">a_tbl</span>, y <span class="op">=</span> <span class="va">b_tbl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 3 × 2
&gt;     key a    
&gt;   &lt;dbl&gt; &lt;chr&gt;
&gt; 1     1 a    
&gt; 2     2 b    
&gt; 3     8 e</code></pre>
</div>
</div>
</div>
<p>And an anti join retains only those observations in the left dataset that do not have a match in the right dataset, as seen in <a href="#exm-td-merging-join-anti" class="quarto-xref">Example&nbsp;<span>7.16</span></a>.</p>
<div id="exm-td-merging-join-anti" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.16</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">anti_join</span><span class="op">(</span>x <span class="op">=</span> <span class="va">a_tbl</span>, y <span class="op">=</span> <span class="va">b_tbl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 2 × 2
&gt;     key a    
&gt;   &lt;dbl&gt; &lt;chr&gt;
&gt; 1     3 c    
&gt; 2     5 d</code></pre>
</div>
</div>
</div>
<p>Of these join types, the left join and the anti join are some of the most common to encounter in research projects.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-lightbulb" aria-label="lightbulb"></i> Consider this</strong></p>
<p>In addition to datasets that are part of an acquired resource or derived from a corpus resource, there are also a number of datasets that are included in R packages that are particularly relevant for text analysis. For example, the <code>tidytext</code> package includes <code>sentiments</code> and <code>stop_words</code> datasets. The <code>lexicon</code> package <span class="citation" data-cites="R-lexicon">(<a href="../references.html#ref-R-lexicon" role="doc-biblioref">Rinker 2019</a>)</span> includes large number of datasets that include sentiment lexicons, stopword lists, contractions, and more.</p>
</div>
</div>
</div>
<p>With this in mind, let’s return to our syntactic simplification investigation. Recall that we started with two curated ENNTT datasets: the natives and translations. We manipulated these datasets subsetting them to 10,000 randomly selected lines, prepped them for annotation by adding a <code>doc_id</code> column and dropping all columns except <code>text</code>, and then annotated them using the <code>udpipe</code> package. We then calculated the number of T-units and words per sentence and created the variables <code>t_units</code> and <code>word_len</code> for each.</p>
<p>These steps produced two datasets for both the natives and for the translations. The first dataset for each is the annotated data frame. The second is the data frame with the sytactic complexity measures we calculated. The annotated data frames are named <code>enntt_natives_ann_tbl</code> and <code>enntt_translations_ann_tbl</code>. The data frames with the syntactic complexity measures are named <code>enntt_natives_syn_comp_tbl</code> and <code>enntt_translations_syn_comp_tbl</code>.</p>
<p>In the end, we want a dataset that looks something like <a href="#tbl-td-integration-idealized" class="quarto-xref">Table&nbsp;<span>7.6</span></a>.</p>
<div id="tbl-td-integration-idealized" class="sm striped quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-td-integration-idealized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.6: Idealized integrated dataset for the syntactic simplification investigation.
</figcaption><div aria-describedby="tbl-td-integration-idealized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-sm table-striped small table">
<colgroup>
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 62%">
</colgroup>
<thead><tr class="header">
<th>doc_id</th>
<th>type</th>
<th>t_units</th>
<th>word_len</th>
<th>text</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>natives</td>
<td>1</td>
<td>5</td>
<td>I am happy right now.</td>
</tr>
<tr class="even">
<td>2</td>
<td>translation</td>
<td>3</td>
<td>11</td>
<td>I think that John believes that Mary is a good person.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>To create this unified dataset, we will need to apply joins and concatenation. First, we will join the prepped datasets with the annotated datasets. Then, we will concatenate the two resulting datasets.</p>
<p>Let’s start by joining the annotated datasets (<code>enntt_natives_ann_tbl</code> and <code>enntt_translations_ann_tbl</code>) with the datasets with the syntactic complexity calculations (<code>enntt_natives_syn_comp_tbl</code> and <code>enntt_translations_syn_comp_tbl</code>). In these joins, we can see that the prepped and calculated datasets share a couple variables, <code>doc_id</code> and <code>sentence_id</code>, in <a href="#exm-td-merging-join-prepped-syn-comp" class="quarto-xref">Example&nbsp;<span>7.17</span></a>.</p>
<div id="exm-td-merging-join-prepped-syn-comp" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.17</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Preview datasets to join</span></span>
<span><span class="va">enntt_natives_ann_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">slice_head</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 3 × 17
&gt;   doc_id paragraph_id sentence_id sentence    start   end term_id token_id token
&gt;   &lt;chr&gt;         &lt;int&gt;       &lt;int&gt; &lt;chr&gt;       &lt;int&gt; &lt;int&gt;   &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;
&gt; 1 1                 1           1 It is extr…     1     2       1 1        It   
&gt; 2 1                 1           1 It is extr…     4     5       2 2        is   
&gt; 3 1                 1           1 It is extr…     7    15       3 3        extr…
&gt; # ℹ 8 more variables: lemma &lt;chr&gt;, upos &lt;chr&gt;, xpos &lt;chr&gt;, feats &lt;chr&gt;,
&gt; #   head_token_id &lt;chr&gt;, dep_rel &lt;chr&gt;, deps &lt;chr&gt;, misc &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">enntt_natives_syn_comp_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">slice_head</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 3 × 4
&gt;   doc_id sentence_id t_units word_len
&gt;   &lt;chr&gt;        &lt;int&gt;   &lt;int&gt;    &lt;int&gt;
&gt; 1 1                1       4       21
&gt; 2 10               1       2       25
&gt; 3 100              1       1       27</code></pre>
</div>
</div>
</div>
<p>The <code>doc_id</code> and <code>sentence_id</code> variables are both keys that we will use to join the datasets. The reason being that if we only use one of the two we will not align the two datasets at the sentence level. Only the combination of <code>doc_id</code> and <code>sentence_id</code> isolates the sentences for which we have syntactic complexity measures. Beyond a having common variable (or variables in our case), we must also ensure that join key variables are of the same vector type in both data frames and that we are aware of any differences in the values. From the output in <a href="#exm-td-merging-join-prepped-syn-comp" class="quarto-xref">Example&nbsp;<span>7.17</span></a>, we can see that the <code>doc_id</code> and <code>sentence_id</code> variables aligned in terms of vector type; <code>doc_id</code> is character and <code>sentence_id</code> is integer in both data frames. If they happened not to be, there types would need to be adjusted.</p>
<p>Now, we need to check for differences in the values. We can do this by using the <code><a href="https://rdrr.io/r/base/sets.html">setequal()</a></code> function. This function returns <code>TRUE</code> if the two vectors are equal and <code>FALSE</code> if they are not. If the two vectors are not equal, the function will return the values that are in one vector but not the other. So if one has <code>10001</code> and the other doesn’t we will get <code>FALSE</code>. Let’s see this in practice, as seen in <a href="#exm-td-merging-join-prepped-syn-comp-check" class="quarto-xref">Example&nbsp;<span>7.18</span></a>.</p>
<div id="exm-td-merging-join-prepped-syn-comp-check" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.18</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Check for differences in the values</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sets.html">setequal</a></span><span class="op">(</span></span>
<span>  <span class="va">enntt_natives_ann_tbl</span><span class="op">$</span><span class="va">doc_id</span>,</span>
<span>  <span class="va">enntt_natives_syn_comp_tbl</span><span class="op">$</span><span class="va">doc_id</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; [1] TRUE</code></pre>
</div>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sets.html">setequal</a></span><span class="op">(</span></span>
<span>  <span class="va">enntt_natives_ann_tbl</span><span class="op">$</span><span class="va">sentence_id</span>,</span>
<span>  <span class="va">enntt_natives_syn_comp_tbl</span><span class="op">$</span><span class="va">sentence_id</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; [1] TRUE</code></pre>
</div>
</div>
</div>
<p>So the values are the same. The final check is to see if the vectors are of the same length. We know the values are the same, but we don’t know if the values are repeated. We do this by simply comparing the length of the vectors, as seen in <a href="#exm-td-merging-join-prepped-syn-comp-length" class="quarto-xref">Example&nbsp;<span>7.19</span></a>.</p>
<div id="exm-td-merging-join-prepped-syn-comp-length" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.19</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Check for differences in the length</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">enntt_natives_ann_tbl</span><span class="op">$</span><span class="va">doc_id</span><span class="op">)</span> <span class="op">==</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">enntt_natives_syn_comp_tbl</span><span class="op">$</span><span class="va">doc_id</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; [1] FALSE</code></pre>
</div>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">enntt_natives_ann_tbl</span><span class="op">$</span><span class="va">sentence_id</span><span class="op">)</span> <span class="op">==</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">enntt_natives_syn_comp_tbl</span><span class="op">$</span><span class="va">sentence_id</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; [1] FALSE</code></pre>
</div>
</div>
</div>
<p>So they are not the same length. Using the <code><a href="https://rdrr.io/r/base/nrow.html">nrow()</a></code> function, I can see that the annotated dataset has 264,124 observations and the calculated dataset has 10,199 observations. The annotation data frames will have many more observations due to the fact that the unit of observations is word tokens. The recoded syntactic complexity data frames’ unit of observation is the sentence.</p>
<p>To appreciate the difference in the number of observations, let’s look at the first 10 observations of the natives annotated frame for just the columns of interest, as seen in <a href="#exm-td-merging-join-prepped-syn-comp-ann" class="quarto-xref">Example&nbsp;<span>7.20</span></a>.</p>
<div id="exm-td-merging-join-prepped-syn-comp-ann" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.20</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Preview the annotated dataset</span></span>
<span><span class="va">enntt_natives_ann_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">doc_id</span>, <span class="va">sentence_id</span>, <span class="va">sentence</span>, <span class="va">token</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">slice_head</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; # A tibble: 10 × 4
&gt;    doc_id sentence_id sentence                                             token
&gt;    &lt;chr&gt;        &lt;int&gt; &lt;chr&gt;                                                &lt;chr&gt;
&gt;  1 1                1 It is extremely important that action is taken to e… It   
&gt;  2 1                1 It is extremely important that action is taken to e… is   
&gt;  3 1                1 It is extremely important that action is taken to e… extr…
&gt;  4 1                1 It is extremely important that action is taken to e… impo…
&gt;  5 1                1 It is extremely important that action is taken to e… that 
&gt;  6 1                1 It is extremely important that action is taken to e… acti…
&gt;  7 1                1 It is extremely important that action is taken to e… is   
&gt;  8 1                1 It is extremely important that action is taken to e… taken
&gt;  9 1                1 It is extremely important that action is taken to e… to   
&gt; 10 1                1 It is extremely important that action is taken to e… ensu…</code></pre>
</div>
</div>
</div>
<p>The annotated data frames have a lot of redundancy in for the join variables and the <code>sentence</code> variable that we want to add to the calculated data frames. We can reduce the redundancy by using the <code>distinct()</code> function from the <code>dplyr</code> package. In this case we want all observations where <code>doc_id</code>, <code>sentence_id</code> and <code>sentence</code> are distinct. We then select these variables with <code>distinct()</code>, as seen in <a href="#exm-td-merging-annotation-distinct" class="quarto-xref">Example&nbsp;<span>7.21</span></a>.</p>
<div id="exm-td-merging-annotation-distinct" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.21</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Reduce annotated data frames to unique sentences</span></span>
<span><span class="va">enntt_natives_ann_distinct</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">enntt_natives_ann_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">distinct</span><span class="op">(</span><span class="va">doc_id</span>, <span class="va">sentence_id</span>, <span class="va">sentence</span><span class="op">)</span></span>
<span></span>
<span><span class="va">enntt_translations_ann_distinct</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">enntt_translations_ann_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">distinct</span><span class="op">(</span><span class="va">doc_id</span>, <span class="va">sentence_id</span>, <span class="va">sentence</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>We now have two datasets that are ready to be joined with the recoded datasets. The next step is to join the two. We will employ a left join where the syntactic complexity data frames are on the left and the join variables will be both the <code>doc_id</code> and <code>sentence_id</code> variables. The code is seen in <a href="#exm-td-merging-join-left-syn-comp" class="quarto-xref">Example&nbsp;<span>7.22</span></a>.</p>
<div id="exm-td-merging-join-left-syn-comp" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.22</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Join the native datasets</span></span>
<span><span class="va">enntt_natives_transformed_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">enntt_natives_syn_comp_tbl</span>,</span>
<span>    y <span class="op">=</span> <span class="va">enntt_natives_ann_distinct</span>,</span>
<span>    by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"doc_id"</span>, <span class="st">"sentence_id"</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># Preview</span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">enntt_natives_transformed_tbl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; Rows: 10,199
&gt; Columns: 5
&gt; $ doc_id      &lt;chr&gt; "1", "10", "100", "1000", "10000", "1001", "1002", "1003",…
&gt; $ sentence_id &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
&gt; $ t_units     &lt;int&gt; 4, 2, 1, 0, 3, 2, 1, 2, 1, 2, 2, 1, 4, 2, 2, 4, 3, 2, 2, 1…
&gt; $ word_len    &lt;int&gt; 21, 25, 27, 15, 40, 43, 29, 23, 13, 30, 33, 9, 68, 35, 16,…
&gt; $ sentence    &lt;chr&gt; "It is extremely important that action is taken to ensure …</code></pre>
</div>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Join the translations datasets</span></span>
<span><span class="va">enntt_translations_transformed_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">enntt_translations_syn_comp_tbl</span>,</span>
<span>    y <span class="op">=</span> <span class="va">enntt_translations_ann_distinct</span>,</span>
<span>    by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"doc_id"</span>, <span class="st">"sentence_id"</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># Preview</span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">enntt_translations_transformed_tbl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; Rows: 10,392
&gt; Columns: 5
&gt; $ doc_id      &lt;chr&gt; "1", "10", "100", "1000", "10000", "1001", "1002", "1003",…
&gt; $ sentence_id &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
&gt; $ t_units     &lt;int&gt; 0, 2, 0, 1, 3, 0, 3, 2, 3, 3, 2, 0, 1, 0, 3, 1, 0, 1, 2, 2…
&gt; $ word_len    &lt;int&gt; 24, 31, 5, 39, 44, 26, 67, 23, 46, 28, 24, 68, 19, 18, 36,…
&gt; $ sentence    &lt;chr&gt; "To my great surprise , on leaving the sitting , I found t…</code></pre>
</div>
</div>
</div>
<!-- Concatenation -->
<p>The two data frames now have the same columns and we are closer to our final dataset. The next step is to move toward concatenating the two datasets. Before we do that, we need to do some preparation. First, and most important, we need to add a <code>type</code> column to each dataset. This column will indicate whether the sentence is a native or a translation. The second is that our <code>doc_id</code> does not serve as a unique identifier for the sentences. Only in combination with <code>sentence_id</code> can we uniquely identify a sentence.</p>
<p>So our plan will be to add a <code>type</code> column to each dataset specifying the values for all the observations in the respective dataset. Then we will concatenate the two datasets. Note, if we combine them before, distiguishing the type will be more difficult. After we concatenate the two datasets, we will add a <code>doc_id</code> column that will serve as a unique identifier for the sentences and drop the <code>sentence_id</code> column. OK, that’s the plan. Let’s execute it in <a href="#exm-td-merging-concatenation" class="quarto-xref">Example&nbsp;<span>7.23</span></a>.</p>
<div id="exm-td-merging-concatenation" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.23</strong></span> &nbsp;</p>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Add a type column</span></span>
<span><span class="va">enntt_natives_transformed_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">enntt_natives_transformed_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>type <span class="op">=</span> <span class="st">"natives"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">enntt_translations_transformed_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">enntt_translations_transformed_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>type <span class="op">=</span> <span class="st">"translations"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Concatenate the datasets</span></span>
<span><span class="va">enntt_transformed_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">bind_rows</span><span class="op">(</span></span>
<span>    <span class="va">enntt_natives_transformed_tbl</span>,</span>
<span>    <span class="va">enntt_translations_transformed_tbl</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># Overwrite the doc_id column with a unique identifier</span></span>
<span><span class="va">enntt_transformed_tbl</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">enntt_transformed_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>doc_id <span class="op">=</span> <span class="fu">row_number</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">doc_id</span>, <span class="va">type</span>, <span class="va">t_units</span>, <span class="va">word_len</span>, text <span class="op">=</span> <span class="va">sentence</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Preview</span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">enntt_transformed_tbl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&gt; Rows: 20,591
&gt; Columns: 5
&gt; $ doc_id   &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…
&gt; $ type     &lt;chr&gt; "natives", "natives", "natives", "natives", "natives", "nativ…
&gt; $ t_units  &lt;int&gt; 4, 2, 1, 0, 3, 2, 1, 2, 1, 2, 2, 1, 4, 2, 2, 4, 3, 2, 2, 1, 1…
&gt; $ word_len &lt;int&gt; 21, 25, 27, 15, 40, 43, 29, 23, 13, 30, 33, 9, 68, 35, 16, 53…
&gt; $ text     &lt;chr&gt; "It is extremely important that action is taken to ensure tha…</code></pre>
</div>
</div>
</div>
<p>The output of <a href="#exm-td-merging-concatenation" class="quarto-xref">Example&nbsp;<span>7.23</span></a> now looks like <a href="#tbl-td-integration-idealized" class="quarto-xref">Table&nbsp;<span>7.6</span></a>. We have a dataset that has the syntactic complexity measures for both the natives and the translations. We can now write this dataset to disk and document it in the data dictionary.</p>
</section></section><section id="activities" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="activities">Activities</h2>
<p>In the following activities, you will review the concept of transforming data to prepare it for analysis and working to implement these steps with R. This includes preparation and enrichment of curated datasets using normalization, tokenization, recoding, generation, and/ or integration strategies.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-file-code" aria-label="file-code"></i> Recipe</strong></p>
<p><strong>What</strong>: <a href="https://qtalr.github.io/resources/recipes/recipe-07/">Transforming and documenting datasets</a><br><strong>How</strong>: Read Recipe 7, complete comprehension check, and prepare for Lab 7.<br><strong>Why</strong>: To work with to primary types of transformations, tokenization and joins. Tokenization is the process of recasting textual units as smaller textual units. The process of joining datasets aims to incorporate other datasets to augment or filter the dataset of interest.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-flask" aria-label="flask"></i> Lab</strong></p>
<p><strong>What</strong>: <a href="https://github.com/qtalr/lab-07">Dataset alchemy</a><br><strong>How</strong>: Fork, clone, and complete the steps in Lab 7.<br><strong>Why</strong>: To gain experience working with coding strategies for transforming datasets using tidyverse functions and regular expressions, practice reading/ writing data from/ to disk, and implement organizational strategies for organizing and documenting a dataset in reproducible fashion.</p>
</div>
</div>
</div>
</section><section id="summary" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<p>In this chapter we covered the process of transforming datasets. The goal is to manipulate the curated dataset to make it align better for analysis. We covered various types of transformation procedures from text normalization to data frame integrations. In any given research project some or all of these steps will be employed –but not necessarily in the order presented in this chapter. It is not uncommon to mix procedures as well. The etiology of the transformation is as unique as the data that you are working with.</p>
<p>Since you are applying techniques that have a significant factor on the shape and contents of your dataset(s) it is important to perform data checks to ensure that the transformations are working as expected. You may not catch everything, and some things may not be caught until later in the analysis process, but it is important to do as much as you can as early as you can.</p>
<p>In line with the reproducible research principles, it is important to write the transformed dataset to disk and to document it in the data dictionary. This is especially important if you are working with multiple datasets. Good naming conventions also come into play. Choosing descriptive names is so easily overlooked by your present self but so welcomed by your future self.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-R-future" class="csl-entry" role="listitem">
Bengtsson, Henrik. 2023. <em>Future: Unified Parallel and Distributed Processing in r for Everyone</em>. <a href="https://future.futureverse.org">https://future.futureverse.org</a>.
</div>
<div id="ref-R-textrecipes" class="csl-entry" role="listitem">
Hvitfeldt, Emil. 2023. <em>Textrecipes: Extra Recipes for Text Processing</em>. <a href="https://github.com/tidymodels/textrecipes">https://github.com/tidymodels/textrecipes</a>.
</div>
<div id="ref-R-gibasa" class="csl-entry" role="listitem">
Kato, Akiru, Shogo Ichinose, and Taku Kudo. 2024. <em>Gibasa: An Alternative ’Rcpp’ Wrapper of ’MeCab’</em>. <a href="https://CRAN.R-project.org/package=gibasa">https://CRAN.R-project.org/package=gibasa</a>.
</div>
<div id="ref-Koehn2005" class="csl-entry" role="listitem">
Koehn, P. 2005. <span>“Europarl: A Parallel Corpus for Statistical Machine Translation.”</span> <em>MT Summit X</em>, 12–16.
</div>
<div id="ref-Liu2021" class="csl-entry" role="listitem">
Liu, Kanglong, and Muhammad Afzaal. 2021. <span>“Syntactic Complexity in Translated and Non-Translated Texts: A Corpus-Based Study of Simplification.”</span> Edited by Diego Raphael Amancio. <em>PLOS ONE</em> 16 (6): e0253454. <a href="https://doi.org/10.1371/journal.pone.0253454">https://doi.org/10.1371/journal.pone.0253454</a>.
</div>
<div id="ref-R-tokenizers" class="csl-entry" role="listitem">
Mullen, Lincoln. 2022. <em>Tokenizers: Fast, Consistent Tokenization of Natural Language Text</em>. <a href="https://docs.ropensci.org/tokenizers/">https://docs.ropensci.org/tokenizers/</a>.
</div>
<div id="ref-Nivre2020" class="csl-entry" role="listitem">
Nivre, Joakim, Marie-Catherine De Marneffe, Filip Ginter, Jan Hajič, Christopher D. Manning, Sampo Pyysalo, Sebastian Schuster, Francis Tyers, and Daniel Zeman. 2020. <span>“Universal Dependencies V2: An Evergrowing Multilingual Treebank Collection.”</span> <em>arXiv Preprint arXiv:2004.10643</em>. <a href="https://arxiv.org/abs/2004.10643">https://arxiv.org/abs/2004.10643</a>.
</div>
<div id="ref-R-lexicon" class="csl-entry" role="listitem">
Rinker, Tyler. 2019. <em>Lexicon: Lexicons for Text Analysis</em>. <a href="https://github.com/trinker/lexicon">https://github.com/trinker/lexicon</a>.
</div>
<div id="ref-R-tidytext" class="csl-entry" role="listitem">
Robinson, David, and Julia Silge. 2023. <em>Tidytext: Text Mining Using Dplyr, Ggplot2, and Other Tidy Tools</em>. <a href="https://github.com/juliasilge/tidytext">https://github.com/juliasilge/tidytext</a>.
</div>
<div id="ref-Szmrecsanyi2004" class="csl-entry" role="listitem">
Szmrecsanyi, Benedikt. 2004. <span>“On Operationalizing Syntactic Complexity.”</span> In <em>Le Poids Des Mots. Proceedings of the 7th International Conference on Textual Data Statistical Analysis. Louvain-La-Neuve</em>, 2:1032–39.
</div>
<div id="ref-R-rsyntax" class="csl-entry" role="listitem">
Welbers, Kasper, and Wouter van Atteveldt. 2022. <em>Rsyntax: Extract Semantic Relations from Text by Querying and Reshaping Syntax</em>.
</div>
<div id="ref-R-jiebaR" class="csl-entry" role="listitem">
Wenfeng, Qin, and Wu Yanyi. 2019. <em>jiebaR: Chinese Text Segmentation</em>. <a href="https://CRAN.R-project.org/package=jiebaR">https://CRAN.R-project.org/package=jiebaR</a>.
</div>
<div id="ref-R-stringr" class="csl-entry" role="listitem">
Wickham, Hadley. 2023. <em>Stringr: Simple, Consistent Wrappers for Common String Operations</em>. <a href="https://stringr.tidyverse.org">https://stringr.tidyverse.org</a>.
</div>
<div id="ref-R-udpipe" class="csl-entry" role="listitem">
Wijffels, Jan. 2023. <em>Udpipe: Tokenization, Parts of Speech Tagging, Lemmatization and Dependency Parsing with the UDPipe ’NLP’ Toolkit</em>. <a href="https://bnosac.github.io/udpipe/en/index.html">https://bnosac.github.io/udpipe/en/index.html</a>.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../part_3/6_curate.html" class="pagination-link" aria-label="Curate">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Curate</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../part_4/index.html" class="pagination-link" aria-label="Analysis">
        <span class="nav-page-text">Analysis</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/qtalr/book/blob/main/part_3/7_transform.qmd" target="_blank" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/qtalr/book/edit/main/part_3/7_transform.qmd" target="_blank" class="toc-action"><i class="bi empty"></i>Edit this page</a></li><li><a href="https://github.com/qtalr/book/issues" target="_blank" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>