---
execute: 
  echo: true
  cache: true
---

# Collaboration {#sec-collaboration}

```{r}
#| label: setup-options
#| child: "_common.qmd"
```

::: callout-tip
## Swirl

**What**: [Compiling Research Projects](https://github.com/lin380/swirl)\
**How**: In the R Console pane load `swirl`, run `swirl()`, and follow prompts to select the lesson.\
**Why**: To ...
:::

Whether for other researchers or for your future self, creating research that is well-documented and reproducible is a fundamental part of conducting modern scientific inquiry. In this chapter we will emphasize the importance of this endeavor and outline strategies for ensuring your research project is reproducible. This will include directory and file structure, key documentation files as well as how to effectively use existing software resources and frameworks for publishing your research (either for private use, journal requirements, or general public consumption) on popular repositories such as GitHub and Open Science Framework (OSF).
