---
execute:
  echo: true
---

# Contribute {#sec-contributing}

```{r}
#| label: setup-options
#| child: "_common.qmd"
#| cache: false
```

::: {.callout-caution title="Caution"}
Under development.
:::

> The reproducibility of studies and the ability to follow up on the work of others is key for innovation in science and engineering.
>
> --- Leland Wilkinson

::: {.callout}
**{{< fa regular list-alt >}} Outcomes**

<!-- Remember and understand verbs: https://tips.uark.edu/blooms-taxonomy-verb-chart/ -->

- Identify the aims of audience-oriented and research-oriented communication
- Understand the overlapping and distinct elements and goals of research presentations and articles
- Comprehend the importance of and pinpoint the aspects of well-documented and reproducible research
:::

<!--
- Emphasizing the importance of effective communication for the impact and dissemination of research
- Overview of the chapter's focus on integrating advanced communication techniques with reproducible research practices
-->

We have discussed the design and implementation of research that is purposive, inquisitive, informed, and methodical. Now, we turn to the task of sharing research results in a manner that is communicable. There are two primary ways to communicate the results of research: audience-oriented and research-oriented. Audience facing research communication includes presentations, articles, and other forms of dissemination that are intended for audiences to become familiar with the research. Research-facing communication, on the other hand, targets other researchers, often working in same field, and focuses on the more technical aspects such as data, code, and documentation that enable other researchers to reproduce and/ or build upon the research. In this chapter, we will cover both aspects of research communication, providing guidelines for effective research reporting and strategies to ensure the reproducibility of your research project.

::: {.callout}
**{{< fa terminal >}} Lessons**

<!-- Remember and understand verbs: https://tips.uark.edu/blooms-taxonomy-verb-chart/ -->

**What**: [Computing environment](https://github.com/qtalr/lessons)\
**How**: In an R console, load `swirl`, run `swirl()`, and follow prompts to select the lesson.\
**Why**: To interact with the R package `renv` and learn how to manage package versions in a research project.
:::

## Audience oriented {#sec-contr-audience-oriented}

<!--
- Popular and scholarly dissemination
  - Presentations
  - Articles
  - Blog posts
  - Social media
-->

Dissemination of research findings is a critical part of the research process. Whether it is through presentations, articles, blog posts, or social media, the ability to effectively communicate the results of research is essential for the impact and dissemination of research. Furthermore, the act of composing a research document can help to develop and refine ideas and conclusions.

The two most common forms of research dissemination in academics are presentations and articles. Both share a common goal: to effectively communicate the research to an audience. However, they also have distinct purposes and require different approaches to achieve their goals. These purposes complement each other, with presentations often serving as a means to engage and elicit feedback from an audience, and articles serving as a more comprehensive and permanent record of the research.

First, let's focus on the common structural components.

| Component | Purpose |
|-----------|---------|
| Introduction | Provide context and rationale based on previous research |
| Methods | Describe the research design and procedures |
| Results | Present the findings including key statistics and table and/ or visual summaries |
| Discussion | Interpret the findings and discuss implications |
| Conclusion | Summarize the research and suggest future work |

: Common components of research presentations and articles {#tbl-c-common-components tbl-colwidths="[20, 80]"}

The components in @tbl-c-common-components reflect the typical structure for presenting research in the social sciences [@Gries2016; @Gries2020; @Sternberg2010]. Their combined purpose is to trace the research narrative from the rationale and goals to connecting the findings with the research questions and aims.

When research is connected to a well-designed plan, as described in @sec-framing-research, many of these components are already in place. The steps taken to identify an area and a problem or gap in the literature find themselves in the introduction. This section builds the case for the research and provides the context for the research question(s) and aim(s). The methods section describes the research design and procedures, including the data collection and analysis steps that are key to contextualize the findings. In the results section, the findings are presented in the appropriate manner given the research aim and the analysis performed.

The discussion and conclusions sections, however, are where the research narrative is brought together. Crafting these sections can be seen as an extension of the research process itself. Instead of elaborating on the planning steps and their implementation, the discussion focus on the interpretation of the findings in the light of the research questions and previous literature. At this stage, the act of articulating the implications of the findings is where insights are developed and refined. The conclusion, for its part, puts a finer point on the research, but also is an opportunity to extend suggestions to where subsequent research might go.

The research abstract is another important component of both presentations and articles. I have not included it in @tbl-c-common-components as it is a distillation of the entire research narrative. Furthermore, the purpose of the abstract is distinct between presentations and articles. In presentations, the abstract typically serves to provide conference referees and attendees with a summary of the research. In articles, the abstract helps readers decide whether the article is relevant to their interests and worth the time to read in full.

Understanding the roles of these common components play in contributing to the overall narrative is essential for effective research communication.

<!--
I think I want to introduce differences between presentations and articles. The main idea here is that presentations emphasize storytelling and relatability whereas articles emphasize nuance and detail.

But I also, at some point, want to address the role of tables and figures in research communication. That is, non-prose communication. Both presentations and articles use tables and figures to communicate findings. Knowing how to use these effectively is important for effective research communication. For example, tables and figures can be used to communicate complex findings in a way that is more accessible. By the same token, figures can communicate in a way that neither prose nor tables can. Figures speak to visual processing and when used effectively can highlight key findings that might be lost in prose or tables.

The question is how to integrate these two ideas while maintaining a logical flow. Here are a few ideas:

- Start with the common components of research presentations and articles
- Discuss the distinctive elements of research presentations, including storytelling and relatability, the "less is more" approach, visual aids and interactive elements, and engaging the audience through questions or interactive elements
- Discuss the distinctive elements of research articles, including the role of tables and figures in communicating complex findings, the importance of nuance and detail, and the role of the abstract in helping readers decide whether the article is relevant to their interests and worth the time to read in full
- Conclude with a discussion of the importance of effective research communication and the role of tables and figures in communicating complex findings

At some point I also want to point to the fact that the reproducible research structure, proposed in Chapter 4, and the use of literate programming support the effective communication of research findings in both presentations and articles. I think I want to show some of the ways that Quarto can create and integrate data, tables,and figures in a way that is seamless and reproducible.
 -->


Yet, presentations and articles are not the same. They have distinct elements and goals that are unique to each form of communication. So too, each form of communication has its own goals and the approach to achieve these goals colors the way the research is communicated. ....

... For example, presentations emphasize storytelling and relatability, the "less is more" approach, visual aids and interactive elements, and engaging the audience through questions or interactive elements. Articles, on the other hand, emphasize nuance and detail, the role of tables and figures in communicating complex findings, and the importance of the abstract in helping readers decide whether the article is relevant to their interests and worth the time to read in full.

 of the research there are also distinct elements that are unique to each form of communication.

 discuss the distinctive elements of research presentations, including storytelling and relatability, the "less is more" approach, visual aids and interactive elements, and engaging the audience through questions or interactive elements.


::: {.callout .halfsize}
**{{< fa medal >}} Dive deeper**

Quarto 1.4+ includes a 'manuscript' feature which provides a workflow for including source content, computations, and visualizations in a single document which links to these source documents. For more information, see the [Quarto documentation](https://quarto.org/docs/manuscripts/).
:::

<!--
- Structure and purpose
  - Articles
    - Typical sections in research articles
      - Abstract, introduction, methods, results, discussion, conclusion
        - The role of each section in contributing to the overall narrative of the research
        - Special attention to methods and results
  - Presentations
    - Distinctive elements
      - Storytelling and relatability
      - "Less is more" approach (i.e. avoiding information overload)
      - Visual aids and interactive elements
      - Engaging the audience through questions or interactive elements
- Advantages to Literate Programming/ Quarto
    - Incorporating data visualization, tables, and other R-generated content seamlessly
      - `ggplot2::ggsave()` for saving figures
      - `kableExtra::save_kable()` for saving tables
    - Apply formatting guidelines
    - Enhance the reproducibility of research
    - Facilitate the sharing of research findings
-->

## Research oriented {#sec-contr-research-oriented}

<!--
- Academic exchange
  - Technical/implementation disclosure
  - Scientific collaboration
  - Reproducible research
-->

Whether for other researchers or for your future self, creating research that is well-documented and reproducible is a fundamental part of conducting modern scientific inquiry. In this section, we will emphasize the importance of this endeavor and outline strategies for ensuring your research project is reproducible. This will include directory and file structure, key documentation files as well as how to effectively use existing software resources and frameworks for publishing your research.

- Importance of well-documented and reproducible research in modern scientific inquiry
  - Ensuring accuracy and reliability of results
  - Facilitating knowledge sharing and collaboration
    - Combining expertise from different fields.
    - Peer review and feedback.
  - Enhance the visibility and impact of research
- Elements
  - Research compendium
    - Using literate programming for transparency and documentation
    - Directory and file structure/ naming conventions
    - Modularization of scripts and files for specific analysis goals
    - Key documentation files: README, data origin, and data dictionaries
    - Implementing a 'main' script for coordinating project steps
  - Computing environment
    - Directory and file management
      - Open source formats, software, and tools
      - Version control
        - Tracking changes and collaboration
        - Ethical considerations (data privacy, security, etc.)
          - `.gitignore` for sensitive data
    - Software management
      - R and package management (`renv`)
    - System-level dependencies
      - Docker (or `rix`) for containerization
  - Publishing research
    - Popular repositories (e.g., GitHub, Open Science Framework)
    - Strategies for uploading and organizing research projects
    - Collaboration best practices
      - GitHub branches and pull requests
      - Code review and feedback (Issues, Discussions, etc.)
      - Licensing and citation attribution
        - appropriate licenses for code and data to ensure proper attribution and reuse

## Activities {.unnumbered}

::: {.callout}
**{{< fa regular file-code >}} Recipe**

<!-- Understand, apply, and analyze verbs: https://tips.uark.edu/blooms-taxonomy-verb-chart/ -->

**What**: [Manage project and computing environments](https://qtalr.github.io/qtalrkit/articles/recipe-11.html)\
**How**: Read Recipe 11, complete comprehension check, and prepare for Lab 11.\
**Why**: To follow the steps for managing a research project and computing environment for effective communication and reproducibility.
:::

::: {.callout}
**{{< fa flask >}} Lab**

<!-- Analyze, evaluate, and create verbs: https://tips.uark.edu/blooms-taxonomy-verb-chart/ -->

**What**: [Future-proof research](https://github.com/qtalr/lab-11)\
**How**: Clone, fork, and complete the steps in Lab 11.\
**Why**: To apply the strategies for ensuring that your research project is reproducible.
:::


## Summary {.unnumbered}

In this chapter, we have discussed the importance of clear and effective communication in research reporting, and the strategies for ensuring that your research project is reproducible. We have discussed the role of research presentations in academic and professional settings, highlighting the benefits of presenting one's work as a means to develop and refine ideas and conclusions. We then discussed the purpose of a research document, focusing on how its structure effectively conveys the project's rationale, goals, procedures, results, and findings. We also emphasized the importance of well-documented and reproducible research in modern scientific inquiry and outlined strategies for ensuring your research project is reproducible. This included directory and file structure, key documentation files as well as how to effectively use existing software resources and frameworks for publishing your research.


<!--


Lesson:

- Using `renv` for package management in a research project
  - Motivation/ problem
    - R package versions change over time
      - Introduces reproducibility issues
    - It would be nice to keep the same versions of packages that worked for a project.
    - CRAN keeps historical snapshots of packages by their version
    - `renv` is a package that helps manage package installation by versions
  - `renv` basics
    - Concepts: lockfile, snapshot, restore
  - `renv` in a research project
    - Initializing `renv` in a research project
    - Adding and removing packages
    - Snapshotting and restoring the environment

Recipe:

- Example of a structured academic article with integrated Quarto elements
- Demonstration of running a collaborative research project on GitHub following reproducible research principles
- Walkthrough of a complete reproducible research project setup, including documentation, modular scripts, and containerization with GitHub Actions

Lab:

- Add `renv` to a research project
- Create a Dockerfile for a research project
- Build Docker image for a research project using GitHub Actions

-->





<!--

Further reading:

- @Rodrigues2023
- @Gandrud2020
- @Blischak2019
- @Gentleman2007
- @Munafo2017
- Gries and Paquot (2020) "Writing up a corpus linguistic paper" DOI: 10.1007/987-3-030-46216-1

-->


