# Feedback {#feedback-appendix}

Thank you for taking the time to read through this book 🫶🏻. I really value your opinion and I would love to hear your thoughts as I continue to make progress.

### Where to review {.unnumbered}

Chapters that are ready for feedback will appear with the following callout.



Those that are not ready will appear with the following callout.

::: {.callout-caution title="Caution"}
Under development.
:::

In a few cases a chapter will be ready for review, but I'll still be working on the exercises, callouts, *etc.* In those cases, the items that are still under development will be marked with the {{< fa wrench >}} icon.

### What to look for {.unnumbered}

As you read over the draft, I'd appreciate your feedback in the following areas:

1. Clarity and Comprehensibility
I'd love to know if you think the content is clear and easy to understand. Do you think the concepts are broken down enough? Are the examples helpful? If anything seems too jargon-y or confusing, definitely let me know.

1. Consistency
It's pretty important to keep things smooth. So, keep an eye out for any inconsistent writing styles, terminology, or layout. If something seems off, I'd appreciate it if you point it out.

1. Relevance
Does the material match the current standards and knowledge? Will it the topics and questions be of interest to linguists? If something feels outdated or irrelevant, don't hesitate to mention it.

1. Engagement
​I​'m not looking to drop a boring read on people. So, as you're going through it, think about whether it holds your interest. Maybe ​the prose needs more life, the examples need to be more diverse, or the exercises could be more or less challenging. If you have any ideas, I'm all ears.

### How to submit feedback {.unnumbered}

Depending on your preference, you can submit feedback in one of three ways:

- [hypothes.is](https://hypothes.is/groups/wppaYKxy/qtal-feedback)
This is the easiest way to submit feedback. Join the "qtal_feedback" annotation group and just highlight the text you want to comment on and click the "Annotate" button. You can also add comments to the right sidebar.

- [GitHub issues](https://github.com/qtalr/book/issues)
This book is hosted on GitHub, so you can submit feedback directly through the issues page for the repository. Just click the "New issue" button and fill out the form. You'll need a GitHub account to do this.

- Email me at <francojc@wfu.edu>
If you'd rather not use the other options, you can always email me directly. Just make sure to try to include references to the specific parts of the book you're referring to. A link or section number will do.

### Thank yous! {.unnumbered}

I want to thank you beforehand for your willingness to help me out. I really appreciate it. I also want to thank you in print. Please give me the name you would like to appear in the [Acknowledgements](index.qmd#acknowledgements) section. If you'd rather not be acknowledged in the final version of the book, please let me know.