{
  "hash": "8673888ed77958c7025e39e185e7b7e2",
  "result": {
    "engine": "knitr",
    "markdown": "---\nexecute:\n  echo: true\n---\n\n\n# Explore {#sec-explore-chapter}\n\n\n\n\n\n\n> The data speaks for itself, but only if we are willing to listen.\n>\n> --- Nate Silver\n\n::: {.callout}\n**{{< fa regular list-alt >}} Outcomes**\n\n- Determine the suitability of exploratory data analysis for a research project.\n- Understand descriptive analysis and unsupervised learning methods, their strengths in pattern recognition and data summarization.\n- Interpret insights from data summarization and pattern recognition, considering their potential to guide further research.\n:::\n\n\n::: {.cell}\n\n:::\n\n\nIn this chapter, we examine a wide range of strategies for exploratory data analysis. The chapter outlines two main branches of exploratory data analysis: descriptive analysis which statistically and/ or visually summarizes a dataset and unsupervised learning which is a machine learning approach that does not assume any particular relationship between variables in a dataset. Either through descriptive or unsupervised learning methods, exploratory data analysis employs quantitative methods to summarize, reduce, and sort complex datasets and statistically and visually interrogate a dataset in order to provide the researcher novel perspective to be qualitatively assessed.\n\n::: {.callout}\n**{{< fa terminal >}} Lessons**\n\n**What**: Advanced objects\\\n**How**: In an R console, load `swirl`, run `swirl()`, and follow prompts to select the lesson.\\\n**Why**: To learn about advanced objects in R, including lists and matrices, and create, inspect, access, and manipulate these objects.\n:::\n\n## Orientation {#sec-eda-orientation}\n\nThe goal of exploratory data analysis is to discover, describe, and posit new hypotheses. This analysis approach is best-suited for research questions where the literature scarce, where the gap in knowledge is wide, or where new territories are being explored. The researcher may not know what to expect, but they are willing to let the data speak for itself. The researcher is open to new insights and new questions that may emerge from the analysis process.\n\nWhile exploratory data analysis allows flexibility, it is essential to have a guiding research question that provides a focus for the analysis. This question will help to determine the variables of interest and the methods to be used. The research question will also help to determine the relevance of the results and the potential for the results to be used in further research.\n\nThe general workflow for exploratory data analysis is shown in @tbl-eda-workflow.\n\n| Step | Name | Description |\n|:----:|:-----|:------------|\n| 1 | Identify | Consider the research question and identify variables of potential interest to provide insight into our question. |\n| 2 | Inspect | Check for missing data, outliers, *etc*. and check data distributions and transform if necessary. |\n| 3 | Interrogate | Submit the selected variables to descriptive (frequency, keyword, co-occurrence analysis, *etc.*) or unsupervised learning (clustering, dimensionality reduction, vector spacing modeling, *etc.*) methods to provide quantitative measures to evaluate. |\n| 4 | Interpret | Evaluate the results and determine if they are valid and meaningful to respond to the research question. |\n| 5 | Iterate (Optional) | Repeat steps 1-4 as new questions emerge from your interpretation. |\n\n: Workflow for exploratory data analysis {#tbl-eda-workflow tbl-colwidths=\"[5, 15, 80]\" .striped}\n\nLet's now demonstrate the workflow in practice.\n\n## Analysis {#sec-eda-analysis}\n\nTo frame our discussion of exploratory data analysis, let's tackle a task. The task will be to identify relevant materials for an English Language Learner (ELL) textbook. This will involve multiple research questions and allow us to illustrate some very fundamental concepts that emerge across text analysis research in both descriptive and unsupervised learning approaches.\n\nSince our task is geared towards English language use, we will want a representative data sample. For this, we will use the Manually Annotated Sub-Corpus (MASC) of the American National Corpus [@Ide2008].\n\nThe data dictionary for the dataset we will use as our point of departure is shown in @tbl-eda-masc-dd-show.\n\n<!-- Show data dictionary -->\n\n\n::: {#tbl-eda-masc-dd-show .cell tbl-cap='Data dictionary for the MASC dataset.' tbl-colwidths='[15,15,15,55]'}\n::: {.cell-output-display}\n\n+----------+----------------+-------------+------------------------------------------------------------------+\n| variable | name           | type        | description                                                      |\n+==========+================+=============+==================================================================+\n| doc_id   | Document ID    | numeric     | Unique identifier for each document                              |\n+----------+----------------+-------------+------------------------------------------------------------------+\n| modality | Modality       | categorical | The form in which the document is presented (written or spoken)  |\n+----------+----------------+-------------+------------------------------------------------------------------+\n| genre    | Genre          | categorical | The category or type of the document                             |\n+----------+----------------+-------------+------------------------------------------------------------------+\n| term_num | Term Number    | numeric     | Index number term per document                                   |\n+----------+----------------+-------------+------------------------------------------------------------------+\n| term     | Term           | categorical | Individual word forms in the document                            |\n+----------+----------------+-------------+------------------------------------------------------------------+\n| lemma    | Lemma          | categorical | Base or dictionary form of the term                              |\n+----------+----------------+-------------+------------------------------------------------------------------+\n| pos      | Part of Speech | categorical | Grammatical category of the term (modified PENN Treebank tagset) |\n+----------+----------------+-------------+------------------------------------------------------------------+\n:::\n:::\n\n\n<!-- Load the MASC dataset/ preview -->\n\nFirst, I'll read in and preview the dataset in @exm-eda-masc-read.\n\n::: {#exm-eda-masc-read}\n\n```r\n# Read the dataset\nmasc_tbl <-\n  read_csv(\"../data/masc/masc_transformed.csv\")\n\n# Preview the MASC dataset\nmasc_tbl |> glimpse()\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 591,036\nColumns: 7\n$ doc_id   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ modality <chr> \"Written\", \"Written\", \"Written\", \"Written\", \"Written\", \"Writt…\n$ genre    <chr> \"Letters\", \"Letters\", \"Letters\", \"Letters\", \"Letters\", \"Lette…\n$ term_num <dbl> 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…\n$ term     <chr> \"December\", \"1998\", \"Your\", \"contribution\", \"to\", \"Goodwill\",…\n$ lemma    <chr> \"december\", \"1998\", \"your\", \"contribution\", \"to\", \"goodwill\",…\n$ pos      <chr> \"NNP\", \"CD\", \"PRP$\", \"NN\", \"TO\", \"NNP\", \"MD\", \"VB\", \"JJR\", \"I…\n```\n\n\n:::\n:::\n\n:::\n\nFrom the output in @exm-eda-masc-read, we get some sense of the structure of the dataset. However, we also need to perform diagnostic and descriptive procedures. This will include checking for missing data and anomalies and assessing central tendency, dispersion, and/ or distributions of the variables. This may include using `skimr`, `dplyr`, `stringr`, `ggplot2`, *etc.* to identify the most relevant variables for our task and to identify any potential issues with the dataset.\n\n\n\n\n\n\n\nAfter a descriptive and diagnostic assessment of the dataset, I identified and addressed missing data and anomalies (including many non-words). I also recoded the `doc_id` variable to a character variable. The dataset now has 486,368 observations, a reduction from the original 591,036 observations. There are 392 documents, 2 modalities, 18 genres, almost 38k unique terms (which are words), almost 26k lemmas (word base forms), and 34 distinct part of speech (POS) tags.\n\n### Descriptive analysis {#sec-eda-descriptive}\n\nDescriptive analysis includes common techniques such as frequency analysis to determine the most frequent words or phrases, dispersion analysis to see how terms are distributed throughout a document or corpus, keyword analysis to identify distinctive terms, and/ or co-occurrence analysis to see what terms tend to appear together.\n\nUsing the MASC dataset, we will entertain questions such as:\n\n- What are the most common terms a beginning ELL should learn?\n- Are there term differences between spoken and written discourses that should be emphasized?\n- What are the most common verb particle constructions?\n\nAlong the way, we will introduce touch on frequency, dispersion, and co-occurrence measures. In addition, we will apply various descriptive analysis techniques and visualizations to explore the dataset and identify new questions and new variables of interest.\n\n#### Frequency analysis {#sec-eda-frequency}\n\n<!-- 4 I's: identify, inspect, interrogate, interpret -->\n\nAt its core, frequency analysis is a descriptive method that counts the number of times a linguistic unit occurs in a dataset. The results of frequency analysis can be used to describe the dataset and to identify terms that are linguistically distinctive or distinctive to a particular group or sub-group in the dataset.\n\n<!--- Raw frequency (counting) --->\n\n##### Raw frequency {#sec-eda-frequency-raw}\n\nLet's consider what the most common words in the MASC dataset are as a starting point to making inroads on our task by identifying relevant vocabulary for an ELL textbook.\n\nIn the `masc_tbl` data frame we have the linguistic unit `term` which corresponds to the word-level annotation of the MASC. The `lemma` corresponds to the base form of each term, for words with inflectional morphology, the lemma is the word sans the inflection (*e.g.* is - be, are - be). For other words, the `term` and the `lemma` will be the same (*e.g.* the - the, in - in). These two variables pose a choice point for us: do we consider words to be the actual forms or the base forms? There is an argument to be made for both. In this case, I will operationalize our linguistic unit as the `lemma` variable, as this will allow us to group words with distinct inflectional morphology together.\n\nTo perform a basic word frequency analysis, we can apply `summarize()` in combination with `n()` or the convenient `count()` function from the `dplyr` package. Our sorted lemma counts appear in @exm-eda-masc-count.\n\n::: {#exm-eda-masc-count}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Lemma count, sorted in descending order\nmasc_tbl |>\n  count(lemma, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 25,923 × 2\n   lemma     n\n   <chr> <int>\n 1 the   26137\n 2 be    19466\n 3 to    13548\n 4 and   12528\n 5 of    12005\n 6 a     10461\n 7 in     8374\n 8 i      7783\n 9 that   7082\n10 you    5276\n# ℹ 25,913 more rows\n```\n\n\n:::\n:::\n\n:::\n\nThe output of this frequency tabulation in @exm-eda-masc-count is a data frame with two columns: `lemma` and `n`.\n\nAs we discussed in @sec-aa-distributions, the frequency of linguistic units in a corpus tends to be highly right-skewed distribution, approximating the Zipf distribution. If we calculate the cumulative frequency of the lemmas in the `masc_tbl` data frame, we can see that the top 10 types account for around 25% of the lemmas used in the entire corpus --by 100 types that increases to near 50% and 1,000 around 75%, as seen in @exm-eda-masc-count-cumulative.\n\n::: {#exm-eda-masc-count-cumulative}\n\n::: {.cell}\n::: {.cell-output-display}\n![Cumulative frequency of lemmas in the MASC dataset](8_explore_files/figure-html/fig-eda-masc-count-cumulative-1.png){#fig-eda-masc-count-cumulative width=384}\n:::\n:::\n\n:::\n\nIf we look at the types that appear within the first 50 most frequent, you can likely also appreciate another thing about language use. Let's list the top 50 types in @exm-eda-masc-count-top-50.\n\n::: {#exm-eda-masc-count-top-50}\n\n::: {#tbl-eda-masc-count-top-50 .cell tbl-cap='Top 50 lemma types in the MASC dataset.' tbl-colwidths='[20,20,20,20,20]'}\n\n```{.r .cell-code}\n# Top 50 types\nlemma_cumul_freq |>\n  slice_head(n = 50) |>\n  pull(lemma) |>\n  matrix(ncol = 5) |>\n  kable(col.names = NULL)\n```\n\n::: {.cell-output-display}\n\n\n|     |     |     |     |      |\n|:----|:----|:----|:----|:-----|\n|the  |have |at   |your |all   |\n|be   |it   |from |an   |there |\n|to   |for  |he   |say  |me    |\n|and  |on   |but  |what |would |\n|of   |do   |by   |so   |about |\n|a    |with |will |his  |know  |\n|in   |we   |my   |if   |get   |\n|i    |as   |or   |'s   |make  |\n|that |this |n't  |can  |out   |\n|you  |not  |they |go   |up    |\n\n\n:::\n:::\n\n:::\n\n\nFor the most part, the most frequent words are not content words, but rather function words (*e.g.* determiners, prepositions, pronouns, auxiliary verbs). Function words include a closed class of relatively few words that are used to express grammatical relationships between content words. It then is no surprise that they are the comprise many of the most frequent words in a corpus.\n\nAnother key observation is that among the most frequency content words (*e.g.* nouns, verbs, adjectives, adverbs) are words that are quite semantically generic --that is, they are words that are used in a wide range of contexts and take a wide range of meanings.\n\nTake for example the adjective 'good'. It can be used to describe a wide range of nouns, such as 'good food', 'good people', 'good times', *etc*. A sometimes near-synonym of 'good', for example 'good student', is the word 'studious'. Yet, 'studious' is not as frequent as 'good' as it is used to describe a narrower range of nouns, such as 'studious student', 'studious scholar', 'studious researcher', *etc*. In this way, 'studious' is more semantically specific than 'good'.\n\n::: {.callout .halfsize}\n**{{< fa regular lightbulb >}} Consider this**\n\nBased on what you now know about the expected distribution of words in a corpus, what if your were asked to predict what the most frequency English word used is in each U.S. State? What would you predict? How confident would you be in your prediction? What if you were asked to predict what the most frequency word used is in the language of a given country? What would you want to know before making your prediction?\n:::\n\nSo common across corpus samples, in some analyses these usual suspects of the most common words are considered irrelvant and are filtered out. In our ELL materials task, however, we might exclude them for this simple fact that it will be a given that we will teach these words given their grammatical importance. If we want to focus on the most common content words, we can filter out the function words.\n\nOne approach to filtering out these words is to use a pre-determined list of **stopwords**. The `tidytext` package includes a data frame `stop_words` of stopword lexicons for English. We can select a lexicon from `stop_words` and use `anti_join()` to filter out the words that appear in the `word` variable from the `lemma` variable in the `masc_tbl` data frame.\n\nEliminating words in this fashion, however, may not always be the best approach. Available lists of stopwords vary in their contents and are determined by other researchers for other potential uses. We may instead opt to create our own stopword list that is tailored to the task, or we may opt to use a statistical approach based on their distribution in the dataset using frequency and/ or dispersion measures.\n\nFor our case, however, we have another available strategy. Since our task is to identify relevant vocabulary, beyond the fundamental function words in English, we can use the POS tags to reduce our dataset to just the content words, that is nouns, verbs, adjectives, and adverbs.\n\nWe need to consult the Penn Tagset again, to ensure we are selecting the correct tags. I will assign this data frame to `masc_content_tbl` to keep it separate from our main data frame `masc_tbl`, seen in @exm-eda-masc-filter-pos.\n\n::: {#exm-eda-masc-filter-pos}\n\n::: {#tbl-eda-masc-filter-pos .cell tbl-cap='Frequency of tokens in the MASC dataset after filtering out lemmas with POS tags that are not content words' tbl-colwidths='[20,20,20,20,20]'}\n\n```{.r .cell-code}\n# Penn Tagset for content words\n# Nouns: NN, NNS,\n# Verbs: VB, VBD, VBG, VBN, VBP, VBZ\n# Adjectives: JJ, JJR, JJS\n# Adverbs: RB, RBR, RBS\n\ncontent_pos <- c(\"NN\", \"NNS\", \"VB\", \"VBD\", \"VBG\", \"VBN\", \"VBP\", \"VBZ\", \"JJ\", \"JJR\", \"JJS\", \"RB\", \"RBR\", \"RBS\")\n\n# Select content words\nmasc_content_tbl <-\n  masc_tbl |>\n  filter(pos %in% content_pos)\n\n# Preview top 50\nmasc_content_tbl |>\n  count(lemma, sort = TRUE) |>\n  slice_head(n = 50) |>\n  pull(lemma) |>\n  matrix(ncol = 5) |>\n  kable(col.names = NULL)\n```\n\n::: {.cell-output-display}\n\n\n|     |       |      |      |      |\n|:----|:------|:-----|:-----|:-----|\n|be   |think  |work  |also  |t     |\n|have |more   |year  |need  |first |\n|do   |just   |come  |way   |help  |\n|not  |time   |use   |back  |day   |\n|n't  |so     |well  |here  |many  |\n|say  |other  |look  |new   |man   |\n|go   |see    |then  |find  |ask   |\n|know |people |right |give  |very  |\n|get  |take   |only  |thing |much  |\n|make |now    |want  |tell  |even  |\n\n\n:::\n:::\n\n:::\n\nThe resulting list in @tbl-eda-masc-filter-pos paints a different picture of the most frequent words in the dataset. The most frequent words are now content words, and included in most frequent words are more semantically specific words. We now have reduced the number of observations by 50% focusing on the content words. We are getting closer to identifying the vocabulary that we want to include in our ELL materials, but we will need some more tools to help us identify the most relevant vocabulary.\n\n##### Dispersion {#sec-eda-frequency-dispersion}\n\n**Dispersion** is a measure of how evenly distributed a linguistic unit is across a dataset. This is a key concept in text analysis, as important as frequency. It is important to recognize that frequency and dispersion are measures of different characteristics. We can have two words that occur with the same frequency, but one word may be more evenly distributed across a dataset than the other. Depending on the researcher's aims, this may be an important distinction to make. For our task, it is likely the case that we want to capture words that are well-dispersed across the dataset as words that have a high frequency and a low dispersion tend to be connected to a particular context, whether that be a particular genre, a particular speaker, a particular topic, *etc*. In other research, aim may be the reverse; to identify words that are highly frequent and highly concentrated in a particular context to identify words that are distinctive to that context.\n\nThere are a variety of measures that can be used to estimate the distribution of types across a corpus. Let's focus on three measures: document frequency ($df$), inverse document frequency ($idf$), and Gries' Deviation of Proportions ($dp$).\n\nThe most basic measure is **document frequency** ($df$). This is the number of documents in which a type appears at least once. For example, if a type appears in 10 documents, then the document frequency is 10. This is a very basic measure, but it is a good starting point.\n\nA nuanced version of document frequency is **inverse document frequency** ($idf$). This measure takes the total number of documents and divides it by the document frequency. This results in a measure that is inversely proportional to the document frequency. That is, the higher the document frequency, the lower the inverse document frequency. This measure is often log-transformed to spread out the values.\n\nOne thing to consider about $df$ and $idf$ is that niether takes into account the length of the documents in which the type appears nor the spread of the type within each document. To take these factors into account, we can use Gries' Deviation of Proportions ($dp$) measure [@Gries2023, pp. 87-88]. The $dp$ measure considers the proportion of a type's frequency in each document relative to its total frequency. This produces a measure that is more sensitive to the distribution of a type within and across documents in a corpus.\n\nLet's consider how these measures differ with three scenarios:\n\nImagine a type with a token frequency of 100 appears in each of the 10 documents in a corpus.\n\nA. Each of the documents is 100 words long. The type appears 10 times in each document.\\\nB. Each of the documents is 100 words long. But now the type appears once in 9 documents and 91 times in 1 document.\\\nC. Nine of the documents constitute 99% of the corpus. The type appears once in each of the 9 documents and 91 times in the 10th document.\n\nScenario A is the most dispersed, scenario B is less dispersed, and scenario C is the least dispersed. Yet, the type's $df$ and $idf$ scores will be the same. But the $dp$ score will reflect increasing concentration of the type's dispersion from A to B to C.\n\n::: {.callout .halfsize}\n**{{< fa medal >}} Dive deeper**\nDispersion measures\n\nYou may wonder why we would want to use $df$ or $idf$ at all. The answer is some combination of the fact that they are computationally less expensive to calculate, they are widely used (especially $idf$), and/ or in many practical situations they often highly correlated with $dp$.\n:::\n\nSo for our task we will use $dp$ as our measure of dispersion. The `qtkit` package includes the `calc_type_metrics()` function which calculates, among other metrics, the dispersion metrics $df$, $idf$, and/ or $dp$. Let's select `dp` and assign the result to `masc_lemma_disp`, as seen in @exm-eda-masc-dp.\n\n::: {#exm-eda-masc-dp}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load package\nlibrary(qtalrkit) # [ ] remove\nlibrary(qtkit)\n\n# Calculate deviance of proportions (DP)\nmasc_lemma_disp <-\n  masc_content_tbl |>\n  calc_type_metrics(\n    type = lemma,\n    documents = doc_id,\n    dispersion = \"dp\"\n  ) |>\n  arrange(dp)\n\n# Preview\nmasc_lemma_disp |>\n  slice_head(n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   type      n    dp\n   <chr> <dbl> <dbl>\n 1 be    19231 0.123\n 2 have   5136 0.189\n 3 not    2279 0.240\n 4 make   1149 0.266\n 5 other   882 0.269\n 6 more   1005 0.276\n 7 take    769 0.286\n 8 only    627 0.286\n 9 time    931 0.314\n10 see     865 0.327\n```\n\n\n:::\n:::\n\n:::\n\nWe would like to identify lemmas that are frequent and well-dispersed. But an important question arises, what is the threshold for frequency and dispersion that we should use to identify the lemmas that we want to include in our ELL materials?\n\nThere are statistical approaches to identifying natural breakpoints, including clustering, but a visual inspection is often good enough for practical purposes. Let's create a density plot to see if there is a natural break in the distribution of our dispersion measure, as seen in @fig-eda-masc-dp-density.\n\n::: {#exm-eda-masc-dp-density}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Density plot of dp\nmasc_lemma_disp |>\n  ggplot(aes(x = dp)) +\n  geom_density() +\n  scale_x_continuous(breaks = seq(0, 1, .1)) +\n  labs(x = \"Deviation of Proportions\")\n```\n\n::: {.cell-output-display}\n![Density plot of Deviation of Proportions for lemmas in the MASC dataset](8_explore_files/figure-html/fig-eda-masc-dp-density-1.png){#fig-eda-masc-dp-density width=384}\n:::\n:::\n\n:::\n\nWhat we are looking for is a distinctive bend in the distribution of dispersion measures. In @fig-eda-masc-dp-density, we can see one between 0.85 and 0.97. This bend is called an elbow, and using this approach to make informed decisions about thresholds is called the **elbow method**. We can split the difference and use this as a threshold to filter out lemmas that are less dispersed.\n\nIn @exm-eda-masc-dp-filter, I filter out lemmas that have a dispersion measure less than 0.91.\n\n::: {#exm-eda-masc-dp-filter}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for lemmas with dp <= 0.91\nmasc_lemma_disp_thr <-\n  masc_lemma_disp |>\n  filter(dp <= 0.91) |>\n  arrange(desc(n))\n```\n:::\n\n:::\n\nThen in @tbl-eda-masc-dp-filter-preview, I preview the top and bottom 50 lemmas in the dataset.\n\n\n::: {#tbl-eda-masc-dp-filter-preview .cell layout-nrow=\"2\" tbl-cap='Frequency of tokens in the MASC dataset after our dispersion threshold' tbl-subcap='[\"Top 50 lemmas\",\"Bottom 50 lemmas\"]' tbl-colwidths='[20,20,20,20,20]'}\n\n```{.r .cell-code}\n# Preview top\nmasc_lemma_disp_thr |>\n  slice_head(n = 50) |>\n  pull(type) |>\n  matrix(ncol = 5) |>\n  kable(col.names = NULL)\n```\n\n::: {.cell-output-display}\n\n\n|     |       |      |      |      |\n|:----|:------|:-----|:-----|:-----|\n|be   |think  |work  |also  |t     |\n|have |more   |year  |way   |first |\n|do   |just   |come  |need  |help  |\n|not  |time   |use   |back  |day   |\n|n't  |so     |well  |here  |many  |\n|say  |other  |look  |new   |man   |\n|go   |see    |then  |find  |ask   |\n|know |people |right |give  |very  |\n|get  |take   |only  |thing |much  |\n|make |now    |want  |tell  |even  |\n\n\n:::\n\n```{.r .cell-code}\n# Preview bottom\nmasc_lemma_disp_thr |>\n  slice_tail(n = 50) |>\n  pull(type) |>\n  matrix(ncol = 5) |>\n  kable(col.names = NULL)\n```\n\n::: {.cell-output-display}\n\n\n|           |           |           |             |             |\n|:----------|:----------|:----------|:------------|:------------|\n|dump       |tuition    |blur       |wound        |accidentally |\n|instrument |awaken     |litigation |devote       |protective   |\n|triumph    |hook       |resistance |alright      |preside      |\n|harsh      |fetch      |absurd     |evolutionary |rethink      |\n|ignorance  |brave      |qualify    |envy         |strictly     |\n|sting      |unleash    |liberty    |nostalgic    |wax          |\n|mainstream |prosperous |going      |shy          |faith-based  |\n|wildly     |buzz       |awkward    |proximity    |decidedly    |\n|dismiss    |presume    |afterwards |sandy        |resolute     |\n|liability  |summarize  |eve        |interfere    |evidently    |\n\n\n:::\n:::\n\n\nWe now have a good candidate list of common vocabulary that is spread well across the corpus.\n\n##### Relative frequency {#sec-eda-frequency-relative}\n\nGauging frequency and dispersion across the entire corpus is a good starting point for any frequency analysis, but it is often the case that we want to compare the frequency and dispersion of linguistic units across corpora or sub-corpora.\n\nIn the case of the MASC dataset, for example, we may want to compare metrics across the two modalities or the various genres. Simply comparing frequency counts across these sub-corpora is not a good approach, and can be misleading, as the sub-corpora may vary in size. For example, if one sub-corpus is twice as large as another sub-corpus, then, all else being equal, the frequency counts will be twice as large in the larger sub-corpus. This is why we use relative frequency measures, which are normalized by the size of the sub-corpus.\n\n::: {.callout .halfsize}\n**{{< fa regular lightbulb >}} Consider this**\n\nA variable in the MASC dataset that has yet to be used is the `pos` POS variable. How could we use this variable to refine our frequency and dispersion analysis of lemma types?\n\nHint: consider lemma forms that may be tagged with different parts-of-speech.\n:::\n\nTo normalize the frequency of linguistic units across sub-corpora, we can use the **relative frequency** measure. This is the frequency of a linguistic unit divided by the total number of linguistic units in the sub-corpus. This bakes in the size of the sub-corpus into the measure. The notion of relative frequency is key to all research working with text, as it is the basis for the statistical approach to text analysis where comparisons are made.\n\nThere are some field-specific terms that are used to refer to relative frequency measures. For example, in information retrieval and Natural Language Processing, the relative frequency measure is often referred to as the **term frequency**. In corpus linguistics, the relative frequency measure is often modified slightly to include a constant (*e.g.* $rf * 100$) which is known as the **observed relative frequency**. Athough the observed relative frequency per number of tokens is not strictly necessary, it is often used to make the values more interpretable as we can now talk about an observed relative frequency of 1.5 as a linguistic unit that occurs 1.5 times per 100 linguistic units.\n\nLet's consider how we might compare the frequency and dispersion of lemmas across the two modalities in the MASC dataset, spoken and written. To make this a bit more interesting and more relevant, let's add the `pos` variable to our analysis. The intent, then, will be to identify lemmas tagged with particular parts of speech that are particularly indicative of each of the modaliites.\n\nWe can do this by collapsing the `lemma` and `pos` variables into a single variable, `lemma_pos`, with the `str_c()` function, as seen in @exm-eda-masc-type.\n\n::: {#exm-eda-masc-type}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Collapse lemma and pos into type\nmasc_content_tbl <-\n  masc_content_tbl |>\n  mutate(lemma_pos = str_c(lemma, pos, sep = \"_\"))\n\n# Preview\nmasc_content_tbl |>\n  slice_head(n = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 8\n  doc_id modality genre   term_num term         lemma        pos   lemma_pos    \n  <chr>  <chr>    <chr>      <dbl> <chr>        <chr>        <chr> <chr>        \n1 1      Written  Letters        3 contribution contribution NN    contribution…\n2 1      Written  Letters        7 mean         mean         VB    mean_VB      \n3 1      Written  Letters        8 more         more         JJR   more_JJR     \n4 1      Written  Letters       12 know         know         VB    know_VB      \n5 1      Written  Letters       15 help         help         VB    help_VB      \n```\n\n\n:::\n:::\n\n:::\n\nNow this will increase the number of lemma types in the dataset as we are now considering lemmas where the same lemma form is tagged with different parts-of-speech.\n\nGetting back to calculating the frequency and dispersion of lemmas in each modality, we can use the `calc_type_metrics()` function with `lemma_pos` as our type argument. We will, however, need to apply this function to each sub-corpus independently and then concatenate the two data frames. This function returns a (raw) frequency measure by default, but we can specify the`frequency` argument to `rf` to calculate the relative frequency of the linguistic units as in @exm-eda-masc-metrics-modality.\n\n::: {#exm-eda-masc-metrics-modality}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate relative frequency\n# Spoken\nmasc_spoken_metrics <-\n  masc_content_tbl |>\n  filter(modality == \"Spoken\") |>\n  calc_type_metrics(\n    type = lemma_pos,\n    documents = doc_id,\n    frequency = \"rf\",\n    dispersion = \"dp\"\n  ) |>\n  mutate(modality = \"Spoken\") |>\n  arrange(desc(n))\n\n# Written\nmasc_written_metrics <-\n  masc_content_tbl |>\n  filter(modality == \"Written\") |>\n  calc_type_metrics(\n    type = lemma_pos,\n    documents = doc_id,\n    frequency = \"rf\",\n    dispersion = \"dp\"\n  ) |>\n  mutate(modality = \"Written\") |>\n  arrange(desc(n))\n\n# Concatenate spoken and written metrics\nmasc_metrics <-\n  bind_rows(masc_spoken_metrics, masc_written_metrics)\n\n# Preview\nmasc_metrics |>\n  slice_head(n = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  type         n     rf     dp modality\n  <chr>    <dbl>  <dbl>  <dbl> <chr>   \n1 be_VBZ    2612 0.0489 0.0843 Spoken  \n2 be_VBP    1282 0.0240 0.111  Spoken  \n3 be_VBD    1020 0.0191 0.300  Spoken  \n4 n't_RB     829 0.0155 0.139  Spoken  \n5 have_VBP   766 0.0143 0.152  Spoken  \n```\n\n\n:::\n:::\n\n:::\n\nWith the `rf` measure, we are now in a position to compare 'apples to apples', as you might say. We can now compare the relative frequency of lemmas across the two modalities. Let's preview the top 5 lemmas in each modality, as seen in @exm-eda-masc-relative-frequency-top.\n\n::: {#exm-eda-masc-relative-frequency-top}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Preview top 10 lemmas in each modality\nmasc_metrics |>\n  group_by(modality) |>\n  slice_max(n = 10, order_by = rf) |>\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 5\n   type         n      rf     dp modality\n   <chr>    <dbl>   <dbl>  <dbl> <chr>   \n 1 be_VBZ    2612 0.0489  0.0843 Spoken  \n 2 be_VBP    1282 0.0240  0.111  Spoken  \n 3 be_VBD    1020 0.0191  0.300  Spoken  \n 4 n't_RB     829 0.0155  0.139  Spoken  \n 5 have_VBP   766 0.0143  0.152  Spoken  \n 6 do_VBP     728 0.0136  0.180  Spoken  \n 7 be_VB      655 0.0123  0.147  Spoken  \n 8 not_RB     638 0.0119  0.137  Spoken  \n 9 just_RB    404 0.00757 0.267  Spoken  \n10 so_RB      387 0.00725 0.357  Spoken  \n11 be_VBZ    4745 0.0249  0.230  Written \n12 be_VBD    3317 0.0174  0.366  Written \n13 be_VBP    2617 0.0137  0.237  Written \n14 be_VB     1863 0.00976 0.218  Written \n15 not_RB    1640 0.00859 0.259  Written \n16 have_VBP  1227 0.00643 0.291  Written \n17 n't_RB     905 0.00474 0.540  Written \n18 have_VBD   859 0.00450 0.446  Written \n19 have_VBZ   777 0.00407 0.335  Written \n20 say_VBD    710 0.00372 0.609  Written \n```\n\n\n:::\n:::\n\n:::\n\nWe can appreciate, now, that there are similarities and a few differences between the most frequent lemmas for each modality. First, there are similar lemmas in written and spoken modalities, such as 'be', 'have', and 'not'. Second, the top 10 include verbs and adverbs. Now we are looking at the most frequent types, so it is not surprising that we see more in common than not. However, looking close we can see that contracted forms are more frequent in the spoken modality, such as 'isn't', 'don't', and 'can't' and that ordering of the verb tenses differs to some degree. Whether these are important distinctions for our task is something we will need to consider.\n\nWe can further cull our results by filtering out lemmas that are not well-dispersed across the sub-corpora. Although it may be tempting to use the threshold we used earlier, we should consider that the size of the sub-corpora are different and the distribution of the dispersion measure may be different. With this in mind, we need to visualize the distribution of the dispersion measure for each modality and apply the elbow method to identify a threshold for each modality.\n\nAfter assessing the density plots for the dispersion of each modality via the elbow method, we update our thresholds. We maintain the 0.91 threshold for the written subcorpus and use a 0.79 threshold for the spoken subcorpus. I apply these filters as seen in @exm-eda-masc-subcorpora-filtered.\n\n::: {#exm-eda-masc-subcorpora-filtered}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for lemmas with\n# dp <= 0.91 for written and\n# dp <= .79 for spoken\nmasc_metrics_thr <-\n  masc_metrics |>\n  filter(\n    (modality == \"Written\" & dp <= 0.91) |\n    (modality == \"Spoken\" & dp <= .79)\n  ) |>\n  arrange(desc(rf))\n```\n:::\n\n:::\n\nFiltering the less-dispersed types reduces the dataset from 33,428 to 4,865 observations. This will provide us with a more succinct list of common and well-dispersed lemmas that are used in each modality.\n\nAs much as the frequency and dispersion measures can provide us with a good starting point, it does not provide an understanding of what types are more indicative of a particular sub-corpus, modality subcorpora in our case. We can do this by calculating the log odds ratio of each lemma in each modality.\n\nThe **log odds ratio** is a measure that quantifies the difference between the frequencies of a type in two corpora or sub-corpora. In spirit and in name, it compares the odds of a type occurring in one corpus versus the other. The values range from negative to positive infinity, with negative values indicating that the type is more frequent in the first corpus and positive values indicating that the lemma is more frequent in the second corpus. The magnitude of the value indicates the strength of the association.\n\nThe `tidylo` package provides a convenient function `bind_log_odds()` to calculate the log odds ratio, and a weighed variant, for each type in each sub-corpus. The weighted log odds ratio measure provides a more robust and interpretable measure for comparing term frequencies across corpora, especially when term frequencies are low or when corpora are of different sizes. The weighting (or standardization) also makes it easier to identify terms that are particularly distinctive or characteristic of one corpus over another.\n\nLet's calculate the weighted log odds ratio for each lemma in each modality and preview the top 10 lemmas in each modality, as seen in @exm-eda-masc-log-odds-weighted.\n\n::: {#exm-eda-masc-log-odds-weighted}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load package\nlibrary(tidylo)\n\n# Calculate log odds ratio\nmasc_metrics_thr <-\n  masc_metrics_thr |>\n  bind_log_odds(\n    set = modality,\n    feature = type,\n    n = n\n  )\n\n# Preview top 10 lemmas in each modality\nmasc_metrics_thr |>\n  group_by(modality) |>\n  slice_max(n = 10, order_by = log_odds_weighted) |>\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 6\n   type                 n       rf     dp modality log_odds_weighted\n   <chr>            <dbl>    <dbl>  <dbl> <chr>                <dbl>\n 1 be_VBZ            2612 0.0489   0.0843 Spoken               14.0 \n 2 n't_RB             829 0.0155   0.139  Spoken               10.4 \n 3 do_VBP             728 0.0136   0.180  Spoken               10.3 \n 4 be_VBP            1282 0.0240   0.111  Spoken                8.67\n 5 think_VBP          350 0.00655  0.259  Spoken                8.32\n 6 have_VBP           766 0.0143   0.152  Spoken                8.01\n 7 know_VBP           282 0.00528  0.260  Spoken                7.04\n 8 well_RB            334 0.00626  0.283  Spoken                6.91\n 9 go_VBG             285 0.00534  0.207  Spoken                6.47\n10 understanding_NN    45 0.000843 0.649  Spoken                6.41\n11 t_NN               475 0.00249  0.778  Written              10.6 \n12 figure_NN          140 0.000733 0.868  Written               5.75\n13 financial_JJ       138 0.000723 0.880  Written               5.71\n14 city_NN            137 0.000718 0.766  Written               5.69\n15 email_NN           133 0.000697 0.866  Written               5.61\n16 eye_NNS            129 0.000676 0.731  Written               5.52\n17 style_NN           108 0.000566 0.829  Written               5.05\n18 mail_NN            106 0.000555 0.876  Written               5.00\n19 text_NN            103 0.000540 0.845  Written               4.93\n20 gift_NN             98 0.000513 0.826  Written               4.81\n```\n\n\n:::\n:::\n\n:::\n\nLet's imagine we would like to extract the most indicative verbs for each modality using the weighted log odds as our measure. We can do this with a little regular expression magic. Let's use the `str_subset()` function to filter for lemmas that contain `_V` and then use `slice_max()` to extract the top 10 most indicative verb lemmas, as seen in @exm-eda-masc-log-odds-weighted-verbs.\n\n::: {#exm-eda-masc-log-odds-weighted-verbs}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Preview (ordered by log_odds_weighted)\nmasc_metrics_thr |>\n  group_by(modality) |>\n  filter(str_detect(type, \"_V\")) |>\n  slice_max(n = 10, order_by = log_odds_weighted) |>\n  select(-n) |>\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 5\n   type                rf     dp modality log_odds_weighted\n   <chr>            <dbl>  <dbl> <chr>                <dbl>\n 1 be_VBZ        0.0489   0.0843 Spoken               14.0 \n 2 do_VBP        0.0136   0.180  Spoken               10.3 \n 3 be_VBP        0.0240   0.111  Spoken                8.67\n 4 think_VBP     0.00655  0.259  Spoken                8.32\n 5 have_VBP      0.0143   0.152  Spoken                8.01\n 6 know_VBP      0.00528  0.260  Spoken                7.04\n 7 go_VBG        0.00534  0.207  Spoken                6.47\n 8 do_VBD        0.00603  0.321  Spoken                5.97\n 9 mean_VBP      0.00247  0.543  Spoken                5.95\n10 do_VB         0.00455  0.207  Spoken                5.61\n11 don_VB        0.000361 0.839  Written               4.04\n12 doe_VBZ       0.000351 0.870  Written               3.98\n13 walk_VBD      0.000320 0.790  Written               3.79\n14 associate_VBN 0.000304 0.777  Written               3.70\n15 reply_VBD     0.000293 0.837  Written               3.64\n16 develop_VBG   0.000288 0.812  Written               3.60\n17 require_VBN   0.000272 0.793  Written               3.50\n18 fall_VBD      0.000267 0.757  Written               3.47\n19 meet_VB       0.000241 0.729  Written               3.30\n20 regard_VBG    0.000225 0.823  Written               3.19\n```\n\n\n:::\n:::\n\n:::\n\nNote that the log odds are larger for the spoken modality than the written modality. This indicates that theses types are more strongly indicative of the spoken modality than the types in the written modality are indicative of the written modality. This is not surprising, as the written modality is typically more diverse in terms of lexical usage than the spoken modality, where the terms tend to be repeated more often, including verbs.\n\n#### Co-occurrence analysis {#sec-eda-co-occurrence}\n\nMoving forward on our task, we have a good idea of the general vocabulary that we want to include in our ELL materials and can identify lemma types that are particularly indicative of each modality. Another useful approach to complement our analysis is to identify words that co-occur with our target lemmas (verbs). In English, it is common for verbs to appear with a preposition or adverb, such as 'give up', 'look after'. These 'phrasal verbs' form a semantic unit that is distinct from the verb alone.\n\nIn cases such as this, we are aiming to do a co-occurrence analysis. Co-occurrence analysis is a set of methods that are used to identify words that appear in close proximity to a target type.\n\n<!-- Concordances -->\n\nAn exploratory, primarily qualitative, approach is to display the co-occurrence of words in a Keyword in Context (KWIC). This is a table that displays the target word in the center of the table and the words that appear before and after the target word within some defined window. This is a useful approach for spot identifying collocations of a target word or phrase, however it can be time-consuming to inspect and is not suitable for large datasets.\n\n::: {.callout .halfsize}\n**{{< fa regular hand-point-up >}} Tip**\n\nKWIC tables are a common tool in corpus linguistics and can be used either before or after a quantitative analysis. If you are interested, the `quanteda` package includes a function `kwic()` that can be used to create a KWIC table.\n:::\n\n<!-- N-grams -->\n\nA straightforward quantitative way to explore co-occurrence is to set the unit of observation to an $n$-gram of terms. Then, the frequency and dispersion metrics can be calculated for each $n$-gram. Yet, there is an issue with this approach for our purposes. The frequency and dispersion of $n$-grams does not necessarily relate to whether the two words form a semantic unit.\n\n<!-- Collocation -->\n\nTo address better address our question, we can use a statistical measures to estimate collocational strength between two words. A **collocation** is a sequence of words that co-occur more often than would be expected by chance. A common measure of collocation is the **pointwise mutual information** (PMI) measure. PMI estimates how much more (or less) two words co-occur in reality compared to what you'd expect by chance if they were independent. A high PMI indicates a strong semantic association between the words.\n\nOne consideration that we need to take for our goal to identify verb particle constructions, is how we ultimately want to group our `lemma_pos` values. This is particularly important given the fact that our `pos` tags for verbs include information about the verb's tense and person. This means that a verb in a verb particle bigram, such as 'look after', will be represented by multiple `lemma_pos` values, such as `look_VB`, `look_VBP`, `look_VBD`, and `look_VBG`. We want to group the verb particle bigrams by a single verb value, so we need to recode the `pos` values for verbs. We can do this with the `case_when()` function from the `dplyr` package.\n\nIn @exm-eda-masc-lemma-pos, I recode the `pos` values for verbs to `V` and then join the `lemma` and `pos` columns into a single string.\n\n::: {#exm-eda-masc-lemma-pos}\n\n::: {.cell}\n\n```{.r .cell-code}\nmasc_lemma_pos_tbl <-\n  masc_tbl |>\n  mutate(pos = case_when(\n    str_detect(pos, \"^V\") ~ \"V\",\n    TRUE ~ pos\n  )) |>\n  group_by(doc_id) |>\n  mutate(lemma_pos = str_c(lemma, pos, sep = \"_\")) |>\n  ungroup()\n```\n:::\n\n:::\n\nLet's calculate the PMI for all the bigrams in the MASC dataset. We can use the `calc_assoc_metrics()` function from `qtkit`. We need to specify the `association` argument to `pmi` and the `type` argument to `bigrams`, as seen in @exm-eda-masc-bigrams-pmi.\n\n::: {#exm-eda-masc-bigrams-pmi}\n\n::: {.cell}\n\n```{.r .cell-code}\nmasc_lemma_pos_assoc <-\n  masc_lemma_pos_tbl |>\n  calc_assoc_metrics(\n    doc_index = doc_id,\n    token_index = term_num,\n    type = lemma_pos,\n    association = \"pmi\"\n  )\n\n# Preview\nmasc_lemma_pos_assoc |>\n  arrange(desc(pmi)) |>\n  slice_head(n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   x               y                   n   pmi\n   <chr>           <chr>           <dbl> <dbl>\n 1 #Christian_NN   bigot_NN            1  12.4\n 2 #FAIL_NN        phenomenally_RB     1  12.4\n 3 #NASCAR_NN      #indycar_NN         1  12.4\n 4 #PALM_NN        merchan_NN          1  12.4\n 5 #Twitter_NN     #growth_NN          1  12.4\n 6 #college_NN     #jobs_NN            1  12.4\n 7 #education_NN   #teaching_NN        1  12.4\n 8 #faculty_NN     #cites_NN           1  12.4\n 9 #fb_NN          siebel_NNP          1  12.4\n10 #glitchmyass_NN reps_NNP            1  12.4\n```\n\n\n:::\n:::\n\n:::\n\nOne caveat to using the PMI measure is that it is sensitive to the frequency of the words. If the words in a bigram pair are infrequent, and especially if they only occur once, then the PMI measure will be inflated. To mitigate this issue, we can apply a frequency threshold to the bigrams before calculating the PMI measure. Let's filter out bigrams that occur less than 10 times, and while we are at it, let's also filter `x` and `y` for the appropriate forms we are targeting that have a positive PMI value, as seen @exm-eda-masc-bigrams-pmi-filtered.\n\n::: {#exm-eda-masc-bigrams-pmi-filtered}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for target bigrams\nmasc_verb_part_assoc <-\n  masc_lemma_pos_assoc |>\n  filter(n >= 10) |>\n  filter(str_detect(x, \"_V\")) |>\n  filter(str_detect(y, \"_IN\")) |>\n  filter(pmi > 0) |>\n  arrange(desc(pmi), x)\n\n# Preview\nmasc_verb_part_assoc |>\n  slice_head(n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   x           y            n   pmi\n   <chr>       <chr>    <dbl> <dbl>\n 1 figure_V    out_IN      17  4.93\n 2 worry_V     about_IN    27  4.78\n 3 walk_V      up_IN       10  4.62\n 4 talk_V      about_IN   114  4.57\n 5 sound_V     like_IN     15  4.42\n 6 post_V      by_IN       57  4.29\n 7 derive_V    from_IN     17  4.27\n 8 stem_V      from_IN     10  4.13\n 9 deal_V      with_IN     53  4.12\n10 associate_V with_IN     48  4.05\n```\n\n\n:::\n:::\n\n:::\n\nWe have a working method for identify verb particle constructions. We can clean up the results a bit by removing the POS tags from the `x` and `y` variables, up our minimum PMI value, and create a network plot to visualize the results in @fig-eda-masc-verb-part-network.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Network plot of verb particle constructions in the MASC dataset](8_explore_files/figure-html/fig-eda-masc-verb-part-network-1.png){#fig-eda-masc-verb-part-network width=384}\n:::\n:::\n\n\nFrom @fig-eda-masc-verb-part-network, and from the underlying data, we can explore verb particle constructions. We could go further and apply our co-occurrence methods to each modality separately, if we wanted to identify verb particle constructions that are distinctive to each modality. We could also apply our co-occurrence methods to other parts-of-speech, such as adjectives and nouns, to identify collocations of these parts-of-speech. There is much more to explore with co-occurrence analysis, but this should give you a good idea of the types of questions that can be addressed.\n\n### Unsupervised learning {#sec-eda-unsupervised}\n\nAligned in purpose with descriptive approaches, unsupervised learning approaches to exploratory data analysis are used to identify patterns in the data from an algorithmic perspective. Common methods in text analysis include principle component analysis, clustering, and vector space modeling.\n\nWe will continue to use the MASC dataset as we develop materials for our ELL textbook to illustrate unsupervised learning methods. In the process, we will explore the following questions:\n\n- Can we identify and group documents based on linguistic features or co-occurrence patterns of the data itself?\n- Do the groups of documents relate to categories in the dataset?\n- Can we estimate the semantics of words based on their co-occurrence patterns?\n\nThrough these questions we will build on our knowledge of frequency, dispersion, and co-occurrence analysis and introduce concepts and methods associated with machine learning.\n\n#### Clustering {#sec-eda-clustering}\n\n**Clustering** is a unsupervised learning technique that can be used to group similar items in the text data, helping to organize the data into distinct categories and discover relationships between different elements in the text. The main steps in the procedure includes identifying the relevant linguistic features to use for clustering, representing the features in a way that can be used for clustering, applying a clustering algorithm to the data, and then interpreting the results.\n\nIn our ELL textbook task, we may very well want to explore the similiarities and/ or differences between the documents based on the distribution of linguistic features. This provides us a view to evaluate to what extent the variables in the dataset, say genre for this demonstration, map to the distribution of linguistic features. Based on this evaluation, we may want to consider re-categorizing the documents, collapsing categories, or even adding new categories.\n\nInstead of relying entirely on the variables' values in the MASC dataset, we can let the data itself say something about how documents may or may not be related. Yet, a pivotal question is what linguistic features will use, otherwise known as **feature selection**. We could use terms or lemmas, but we may want to consider other features, such as parts of speech or some co-occurrence pattern. We are not locked into using one criterion, and we can perform clustering multiple times with different features, but we should consider the implications of our feature selection for our interpretation of the results.\n\nImagine that among the various features that we are interested in associating documents, we consider lemma use and POS use. However, we need to operationalize what we mean by 'use'. In machine learning, this process is known as **feature engineering**. We likely want use some measure of frequency. Since we are comparing documents, a relative frequency measure will be most useful. Another consideration is what does it mean to use lemmas or POS tags as our features. Each represents a different linguistic of the documents. Lemmas represent the lexical diversity of the documents while POS tags approximate the grammatical diversity of the documents [@Petrenz2011].\n\nLet's assume that our interest is to gauge the grammatical diversity of the documents, so we will go with POS tags. With this approach, we aim to distinguish between documents in a way that may allow us to use consider whether genre-document categories are meaningful, along grammatical lines.\n\nThe next question to address in any analysis is how to represent the features. In machine learning, the most common way to represent document- feature relationsips is in a matrix. In our case, we want to create a matrix with the documents in the rows and the features in the columns. The values in the matrix will be the operationalization of grammatical diversity in each document. This configuration is known as a **document-term matrix** (DTM).\n\nTo recast a data frame into a DTM, we can use the `cast_dtm()` function from the `tidytext` package. This function takes a data frame with a document identifier, a feature identifier, and a value for each observation and casts it into a matrix. Operations such as normalization are easily and efficiently performed in R on matrices, so initially we can cast a frequency table of POS tags into a matrix and then normalize the matrix by documents.\n\nLet's see how this works with the MASC dataset in @exm-eda-masc-dtms.\n\n\n\n\n\n::: {#exm-eda-masc-dtms}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load package\nlibrary(tidytext)\n\n# Create a document-term matrix of POS tags\nmasc_pos_dtm <-\n  masc_tbl |>\n  count(doc_id, pos) |>\n  cast_dtm(doc_id, pos, n) |>\n  as.matrix()\n\n# Inpsect\ndim(masc_pos_dtm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 392  32\n```\n\n\n:::\n\n```{.r .cell-code}\n# Preview\nmasc_pos_dtm[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Terms\nDocs  CC DT EX IN JJ\n  1   14 35  1 44 27\n  10  11 38  0 39 18\n  100  0  2  0  2  3\n  101  3 16  0 23  7\n  102 20 29  0 34 20\n```\n\n\n:::\n:::\n\n:::\n\nThe matrix `masc_pos_dtm` has 392 documents and 32 POS tags. The values in the matrix are the frequency of each POS tag in each document. Note preview the a subset of the contents of a matrix, such as in @exm-eda-masc-dtms, we use bracket syntax `[]` instead of the `head()` function.\n\nWe can now normalize the matrix by documents. We can do this by dividing each feature count by the total count in each document. This is a row-wise transformation, so we can use the `rowSums()` function from base R to calculate the total count in each document. Then each count divided by its row's total count, as seen in @exm-eda-masc-dtms-normalized.\n\n::: {#exm-eda-masc-dtms-normalized}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Normalize pos matrix by documents\nmasc_pos_dtm <-\n  masc_pos_dtm / rowSums(masc_pos_dtm)\n```\n:::\n\n:::\n\nThere are two concerns to address before we can proceed with clustering. First, clustering algorithm performance tends to degrade with the number of features. Second, clustering algorithms perform better with more informative features. That is to say, features that are more distinct across the documents provide better information for deriving useful clusters.\n\nWe can address both of these concerns by reducing the number of features and increasing the informativeness of the features. To accomplish this is to use **dimensionality reduction**. Dimensionality reduction is a set of methods that are used to reduce the number of features in a dataset while retaining as much information as possible. The most common method for dimensionality reduction is **principle component analysis** (PCA). PCA is a method that transforms a set of correlated variables into a set of uncorrelated variables, known as principle components. The principle components are ordered by the amount of variance that they explain in the data. The first principle component explains the most variance, the second principle component explains the second most variance, and so on.\n\nWe can apply PCA to the matrix and assess how well it accounts for the variation in the data and how the variation is distributed across components. The `prcomp()` function from base R can be used to perform PCA.\n\nLet's apply PCA to the matrix, as seen in @exm-eda-masc-dtms-pca.\n\n::: {#exm-eda-masc-dtms-pca}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set seed\nset.seed(123)\n\n# Apply PCA to matrix\nmasc_pos_pca <-\n  masc_pos_dtm |>\n  prcomp()\n```\n:::\n\n:::\n\nWe can visualize the amount of variance explained by each principle component with a scree plot. The `fviz_eig()` function from the `factoextra` package implements a scree plot on a PCA object. We can set the number of number of components to visualize with `ncp =`.\n\nLet's create a scree plot for the matrix, as seen in @exm-eda-masc-dtms-pca-scree.\n\n::: {#exm-eda-masc-dtms-pca-scree}\n\n```r\n# Load package\nlibrary(factoextra)\n\n# Scree plot: POS relative frequency\nfviz_eig(masc_pos_pca, ncp = 10)\n```\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Scree plot of the principle components of the POS relative frequency](8_explore_files/figure-html/fig-eda-masc-dtms-pca-scree-1.png){#fig-eda-masc-dtms-pca-scree width=384}\n:::\n:::\n\n:::\n\n\n::: {.callout .halfsize}\n**{{< fa medal >}} Dive deeper**\n\nAs with many modeling techniques we will encounter, it is possible to extract the importance of features that contribute to the model. In the case of PCA, we can extract the feature values from the principle components using the `get_pca_var()` function from the `factoextra` package. Feature importance provides more detailed insight into the inner workings of the algorithms we employ in our research and therefore can serve to inform our interpretation of the results.\n:::\n\nFrom @fig-eda-masc-dtms-pca-scree, we can see that the first component shows the most variance explained, around 30%, and then drops for subsequent drops as the number of dimensions increase. Visually we will apply the elbow method to identify the number of dimensions to use for clustering. It appears hhe variance explained decreases between 4 and 5 dimensions. This is a good indication that we should use 4 dimensions for our clustering algorithm.\n\nLet's go ahead and create a matrix of the first four principle components for the POS data, as seen in @exm-eda-masc-pos-pca-pc.\n\n::: {#exm-eda-masc-pos-pca-pc}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a matrix of the first four principle components\nmasc_pos_pca_pc <-\n  masc_pos_pca$x[, 1:4]\n```\n:::\n\n:::\n\nNow that we have identified assessed the features that we want to use for clustering and we have represented the features in a way that can be used for clustering, we can apply a clustering algorithm to the data.\n\nSome algorithms are better suited for certain types of data and certain types of tasks. For example, **Hierarchical clustering** is a good choice when we are not sure how many clusters we want to identify, as it does not require us to specify the number of clusters from the outset. However, it is not a good choice when we have a large dataset, as it can be computationally expensive compared to some other algorithms. **K-means clustering**, on the other hand, is a good choice when we want to identify a pre-defined number of clusters, and the aim is to gauge how well the data fit the clusters. These two clustering techniques, therefore, complement each other with Hierarchical clustering being a good choice for initial exploration and K-means clustering being a good choice for targeted evaluation.\n\nSince we are exploring the usefulness of the 18 genre labels used in the MASC dataset we have a good idea of how many clusters we want to start with. This is a good case to employ the K-means clustering algorithm.\n\nIn K-means clustering, we specify the number of clusters that we want to identify. For each cluster number, a random center is generated. Then each observation is assigned to the cluster with the nearest center. The center of each cluster is then recalculated based on the distribution of the observations in the cluster. This process is iterates either a pre-defined number of times, or until the centers converge (*i.e* observations stop switching clusters).\n\nThe `kmeans()` function from base R takes the matrix of features as its first argument and the number of clusters as its second argument. We can specify the number of clusters with the `centers` argument. Other arguments `nstart` and `iter.max` can be used to specify the number of random starts and the maximum number of iterations, respectively. Since the starting point for centers is random, it is a good idea to run the algorithm multiple times with different starting points. And we limit the interations to avoid the algorithm running indefinitely.\n\nOur goal, then, will be to assess how well this number of clusters fits the data. After finding the optimal number of clusters, we can then compare the results with the genre variable to see how well the clusters map to the values of this variable.\n\nOne way to assess the fit of the clustering algorithm is to visualize the results, interpret, and adjust the number of clusters, if necessary, any number of times. Another, more efficient, approach is to algorithmically assess the variability of the clusters based on differing number of clusters and then select the number of clusters that best fits the data.\n\nWe will take the later approach and plot the **within-cluster sum of squares** (WSS) for a range of values for $k$. The WSS is the sum of the squared distance between each observation and its cluster center. With a plot of the WSS for a range of values for $k$, we can identify the value for $k$ where the WSS begins to level off, using the elbow method. It is not always clear where the elbow is, yet it is a good starting point for identifying the optimal number of clusters.\n\nThe `fviz_nbclust()` function can be used to plot the WSS for a range of values for $k$. The `fviz_nbclust()` function takes the `kmeans()` function as its first argument and the matrix of features as its second argument. The `fviz_nbclust()` function also takes arguments `method = \"wss\"` to specify the WSS method and `k.max = 20` to specify the maximum number of clusters to plot. Let's plot the WSS for a range of values for $k$, as seen in @fig-eda-masc-pos-kmeans-elbow.\n\n```r\nmasc_pos_pca_pc |>\n  fviz_nbclust(\n    FUNcluster = kmeans,\n    method = \"wss\", # method\n    k.max = 20,\n    nstart = 25,\n    iter.max = 20\n  )\n```\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Elbow method for $k$-means clustering of the MASC dataset](8_explore_files/figure-html/fig-eda-masc-pos-kmeans-elbow-1.png){#fig-eda-masc-pos-kmeans-elbow width=384}\n:::\n:::\n\n\nIt is clear that there is significant gains in cluster fit from 1 to 4 clusters, but the gains begin to level off after 5-7 clusters.\n\nNow we have an informed selection for $k$. Let's use 4 clusters in the `kmeans()` function and collect the results, as seen in @exm-eda-masc-pos-kmeans-fit.\n\n::: {#exm-eda-masc-pos-kmeans-fit}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set seed\nset.seed(123)\n\n# K-means: for 4 clusters\nmasc_pos_kmeans_fit <-\n  masc_pos_pca_pc |>\n  kmeans(\n    centers = 4,\n    nstart = 25,\n    iter.max = 20\n  )\n\n# Preview\nmasc_pos_kmeans_fit$cluster[1:10]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  1  10 100 101 102 103 104 105 106 107 \n  1   1   2   3   3   2   2   2   4   3 \n```\n\n\n:::\n:::\n\n:::\n\nThe preview from @exm-eda-masc-pos-kmeans-fit shows the cluster assignments for the first 10 documents (`doc_id`) in the dataset.\n\nFrom this point we can join document-cluster pairings produced by the $k$-means algorithm with the original dataset. We can then explore the clusters in terms of the original features. We can also explore the clusters in terms of the original labels.\n\nLet's join the cluster assignments to the original dataset, as seen in @exm-eda-masc-pos-kmeans-join.\n\n::: {#exm-eda-masc-pos-kmeans-join}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Organize $k$-means clusters into a tibble\nmasc_pos_cluster_tbl <-\n  tibble(\n    doc_id = names(masc_pos_kmeans_fit$cluster),\n    cluster = masc_pos_kmeans_fit$cluster\n  )\n\n# Join cluster assignments to original dataset\nmasc_cluster_tbl <-\n  masc_tbl|>\n  left_join(\n    masc_pos_cluster_tbl,\n    by = \"doc_id\"\n  )\n\n# Preview\nmasc_cluster_tbl |>\n  slice_head(n = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 8\n  doc_id modality genre   term_num term         lemma        pos   cluster\n  <chr>  <chr>    <chr>      <dbl> <chr>        <chr>        <chr>   <int>\n1 1      Written  Letters        2 Your         your         PRP$        1\n2 1      Written  Letters        3 contribution contribution NN          1\n3 1      Written  Letters        4 to           to           TO          1\n4 1      Written  Letters        6 will         will         MD          1\n5 1      Written  Letters        7 mean         mean         VB          1\n```\n\n\n:::\n:::\n\n:::\n\nWe now see that the cluster assignments from the $k$-means algorithm have been joined to the original dataset. We can now explore the clusters in terms of the original features. For example, let's look at the distribution of the clusters across genre, as seen in @exm-eda-masc-pos-kmeans-genre. To do this, we first need to reduce our dataset to the distinct combinations of genre and cluster. Then, we can use the `janitor` package's `tabyl()` function to provided formatted percentages.\n\n::: {#exm-eda-masc-pos-kmeans-genre}\n\n::: {#tbl-eda-masc-pos-kmeans-genre .cell tbl-cap='Distribution of clusters by genre in the MASC dataset'}\n\n```{.r .cell-code}\n# Load package\nlibrary(janitor)\n\n# Reduce to distinct combinations of genre and cluster\nmasc_meta_tbl <-\n  masc_cluster_tbl |>\n  distinct(genre, cluster)\n\n# Tabulate: cluster by genre\nmasc_meta_tbl |>\n  tabyl(genre, cluster) |>\n  adorn_totals(\"row\") |>\n  adorn_percentages(\"col\") |>\n  adorn_pct_formatting(digits = 1) |>\n  as_tibble() |>\n  tt(width = 1)\n```\n\n::: {.cell-output-display}\n\n+--------------+--------+--------+--------+--------+\n| genre        | 1      | 2      | 3      | 4      |\n+==============+========+========+========+========+\n| Blog         | 7.7%   | 20.0%  | 8.3%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Email        | 7.7%   | 20.0%  | 8.3%   | 20.0%  |\n+--------------+--------+--------+--------+--------+\n| Essay        | 7.7%   | 0.0%   | 8.3%   | 20.0%  |\n+--------------+--------+--------+--------+--------+\n| Face-to-face | 7.7%   | 0.0%   | 0.0%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Fiction      | 7.7%   | 0.0%   | 8.3%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Fictlets     | 7.7%   | 0.0%   | 0.0%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Government   | 0.0%   | 0.0%   | 8.3%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Jokes        | 7.7%   | 0.0%   | 0.0%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Journal      | 7.7%   | 0.0%   | 8.3%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Letters      | 7.7%   | 20.0%  | 8.3%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Movie Script | 7.7%   | 0.0%   | 8.3%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Newspaper    | 7.7%   | 20.0%  | 8.3%   | 20.0%  |\n+--------------+--------+--------+--------+--------+\n| Non-fiction  | 0.0%   | 0.0%   | 8.3%   | 20.0%  |\n+--------------+--------+--------+--------+--------+\n| Technical    | 0.0%   | 0.0%   | 8.3%   | 20.0%  |\n+--------------+--------+--------+--------+--------+\n| Telephone    | 7.7%   | 0.0%   | 0.0%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Transcript   | 7.7%   | 0.0%   | 0.0%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Travel Guide | 0.0%   | 0.0%   | 8.3%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Twitter      | 0.0%   | 20.0%  | 0.0%   | 0.0%   |\n+--------------+--------+--------+--------+--------+\n| Total        | 100.0% | 100.0% | 100.0% | 100.0% |\n+--------------+--------+--------+--------+--------+\n:::\n:::\n\n:::\n\nFrom @exm-eda-masc-pos-kmeans-genre, we can see that the clusters are not evenly distributed across the genres. In particular, cluster 2 tends to be more associated with 'blog', 'email', 'letters', 'twitter', and 'news'. Another interesting cluster is cluster 4, which is more associated with 'newspaper', 'non-fiction', and interestingly, 'email'. This suggest that the clusters are capturing some of the variation in the across the genres and potential within some of the genres.\n\nWe could continue to explore genre, but we could also entertain the possibility that the clusters may capture differences between modality --even some interaction between modality and genre! This highlights how exploratory data analysis through clustering can be used to identify new questions and new variables of interest.\n\n::: {.callout .halfsize}\n**{{< fa regular lightbulb >}} Consider this**\n\nGiven the cluster assignments derived using the distribution of POS tags, what other relationships between the clusters and the original features could one explore? What are the limitations of this approach? What are the implications of this approach for the interpretation of the results?\n:::\n\n#### Vector space models {#sec-eda-vector-space-models}\n\nIn our discussion of clustering, we targeted associations between documents based on the distribution of linguistic features. We now turn to targeting associations between linguistic features based on their distribution across documents. The technique we will introduce is known as **vector space modeling**. Vector space modeling aims to represent linguistic features as numerical vectors which reflect the various linguistic contexts in which the features appear. Together these vectors form a feature-context space in which features with similar contextual distributions are closer together.\n\nAn interesting property of vector space models is that are able to capture semantic and/ or syntactic relationships between features based on their distribution. In this way, vector space modeling can be seen as an implementation of the **distributional hypothesis** --that is, terms that appear in similar linguistic contexts tend to have similar meanings [@Harris1954]. As @Firth1957 states, \"you shall know a word by the company it keeps\".\n\n::: {.callout .halfsize}\n**{{< fa regular file-alt >}} Case study**\n\n@Garg2018 quantify and compare gender and ethnic stereotypes over time using word embeddings. The authors explore the temporal dynamics of stereotypes using word embeddings as a quantitative measure of bias. The data used includes word embeddings from the Google News dataset for contemporary analysis, as well as embeddings from the COHA and Google Books datasets for historical analysis. Additional validation is done using embeddings from the New York Times Annotated Corpus. Several word lists representing gender, ethnicity, and neutral words are collated for analysis. The main finding is that language reflects and perpetuates cultural stereotypes, and the analysis shows consistency in the relationships between embedding bias and external metrics across datasets over time. The results also highlight the impact of historical events, such as the women’s movement of the 1960s, on the encoding of stereotypes.\n:::\n\nLet's assume in our textbook project we are interested in gathering information about English's expression of the semantic concepts of manner and motion. For learners of English, this can be an area of difficulty as languages differ in how these semantic properties are expressed. English is a good example of a \"satellite-framed\" language, that is that manner and motion are often encoded in the same verb with a particle encoding the motion path (\"rush out\", \"climb up\"). Other languages such as Spanish, Turkish, and Japanese are \"verb-framed\" languages, that is that motion but not manner is encoded in the verb (\"salir corriendo\", \"koşarak çıkmak\", \"走り出す\").\n\nWe can use vector space modeling to attempt to represent the distribution of verbs in the MASC dataset and then target the concepts of manner and motion to then explore how English encodes these concepts. The question will be what will our features be. They could be terms, lemmas, POS tags, *etc*. Or they could be some combination. Considering the task at hand which we will ultimately want to know something about verbs, it makes sense to include the POS information in combination with either the term or the lemma.\n\nIf we include term and POS then we have a feature for every morphological variant of the term (*e.g.* house_VB, housed_VBD, housing_VBG). This can make the model more sizeable than it needs to be. If we include lemma and POS then we have a feature for every lemma with a distinct grammatical category (*e.g.* house_NN, house_VB). Note that as the POS tags are from the Penn tagset, many morphological variants appear in the tag itself (*e.g.* house_VB, houses_VBZ, housing_VBG). This is a good example of how the choice of features can impact the size of the model. In our case, it is not clear that we need to include the morphological variants of the verbs, so I will use lemmas and recode the POS variables as a simplified tagset.\n\n\n\n\n\nAfter simplifying the features, we can then apply the vector space model to the MASC dataset. When VSM is applied to words, it is known as **word embedding**. To calculate word embeddings there are various algorithms that can be used (BERT, word2vec, GloVe, *etc.*) We will use the **word2vec** [@Mikolov2013b] algorithm. Word2vec is a neural network-based algorithm that learns word embeddings from a large corpus of text. In the word2vec algorithm, the researcher can choose to learn embeddings from a **Continuous Bag of Words** (CBOW) or a **Skip-gram model**. The CBOW model predicts a target word based on the context words. The Skip-gram model predicts the context words based on the target word. The CBOW model is faster to train and is better for frequent words. The Skip-gram model is slower to train and is better for infrequent words.\n\n::: {.callout .halfsize}\n**{{< fa medal >}} Dive deeper**\n\nChoosing window size and dimensions for word2vec models is another important consideration. The window size is the number of words that the model will consider as context for the target word. Smaller window sizes tend to capture more syntactic information, while larger window sizes tend to capture more semantic information.\n\nThe number of dimensions is the number of features that the model will learn. More dimensions can capture more information, but can also lead to overfitting --picking up on nuances that are particular to the dataset and that do not generalize well. Fewer dimensions can capture less information, but can also lead to underfitting --not picking up on nuances that are particular to the dataset and that do generalize well. The number of dimensions is a hyperparameter that can be tuned to optimize the model for the task at hand.\n:::\n\nAnother consideration to take into account is the size of the corpus used to train the model. VSM provide more reliable results when trained on larger corpora. The MASC dataset is relatively small. We've simplified our features in order to have a smaller vocabulary in hopes to offset this limitation to a degree. But the choice of either CBOW or Skip-gram can also help to offset this limitation. CBOW can be better for smaller corpora as it aggregates context infomation. Skip-gram can be better for larger corpora as it can capture more nuanced relationships between words.\n\nTo implement the word2vec algorithm on our lemma + POS features, we will use the `word2vec` package. The `word2vec()` function takes a text file and uses it to train the vector representations. To prepare the MASC dataset for training, we will need to write the lemma + POS features to a text file as a single character string. We can do this by first collapsing the `lemma_pos` variable into a single string for the entire corpus using the `str_c()` function. Then we can use the `write_lines()` function to write the string to a text file, as in @exm-eda-masc-vsm-write-txt.\n\n::: {#exm-eda-masc-vsm-write-txt}\n```r\n# Write lemma + POS to text file\nmasc_tbl |>\n  summarize(text = str_c(lemma_pos, collapse = \" \")) |>\n  pull(text) |>\n  write_lines(\n    file = \"../data/analysis/masc_lemma_pos.txt\"\n  )\n```\n\n\n\n:::\n\nWith the single line text file on disk, we will read it in, apply the word2vec algorithm using the `word2vec` package, and write the model to disk. By default, te `word2vec()` function applies the CBOW model, with 50 dimensions, a window size of 5, and a minimum word count of 5. We can change these parameters as needed, but let's apply the default algorithm to the text file spliting features by sentence punctuation, as seen in @exm-eda-masc-vsm-word2vec-train.\n\n::: {#exm-eda-masc-vsm-word2vec-train}\n```r\n# Load package\nlibrary(word2vec)\n\n# Traing word2vec model\nmasc_model <-\n  word2vec(\n    x = \"../data/analysis/masc_lemma_pos.txt\",\n    type = \"cbow\", # or \"skip-gram\"\n    dim = 100,\n    split = c(\" \"),\n    threads = 8L\n  )\n\n# Write model to disk\nwrite.word2vec(\n  masc_model,\n  file = \"../data/analysis/masc_lemma_pos.bin\"\n)\n```\n\n\n::: {.cell}\n\n:::\n\n:::\n\nWriting the model to disk is important as it allows us to read the model in without having to retrain it. In cases where the corpus is large, this can save a lot of computational time.\n\nNow that we have a trained model, we can read it in with the `read.vectors()` function from the `wordVectors` package.\n\n::: {#exm-eda-masc-vsm-word2vec-read}\n```r\n# Load package\nlibrary(wordVectors)\n\n# Read word2vec model\nmasc_model <-\n  read.vectors(\n    filename = \"../data/analysis/masc_lemma_pos.bin\"\n  )\n```\n\n\n\n\n:::\n\nThe `read.vectors()` function returns a matrix where each row is a term in the model and each column is a dimension in the vector space, as seen in @exm-eda-masc-vsm-word2vec-vector-object.\n\n::: {#exm-eda-masc-vsm-word2vec-vector-object}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Inspect\ndim(masc_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5808  100\n```\n\n\n:::\n\n```{.r .cell-code}\n# Preview\nmasc_model[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA VectorSpaceModel object of  5  words and  5  vectors\n                   [,1]   [,2]    [,3]   [,4]    [,5]\nabbreviated_ADJ   1.068  1.103 -0.3439  0.386 -1.0062\nabsent_ADJ       -1.839 -1.753  0.0658  0.119  0.9376\nabsorb_VERB      -1.772 -1.528 -0.0554  0.664 -1.2453\naccidentally_ADV -1.264 -0.742 -0.6870  0.613 -1.0750\naesthetic_ADJ     0.567  0.524  1.0638 -0.332 -0.0424\nattr(,\".cache\")\n<environment: 0x7f8701884da0>\n```\n\n\n:::\n:::\n\n:::\n\nThe row-wise vector in the model is the vector representation of each feature. The notion is that these values can now be compared with other features to explore distributional relatedness. We can extract specific features from the matrix using the `[]` operator.\n\n\n\n\n\nAs an example, let's compare the vectors for noun-verb pairs for the lemmas 'run' and 'walk'. To do this we extract these features from the model. To appreciate the relatedness of these features it is best to visualize them. We can do this by first reducing the dimensionality of the vectors using principal components analysis (PCA). We can then plot the first two principle components, as seen in @fig-eda-masc-vsm-word2vec-similarity.\n\n::: {#exm-eda-masc-vsm-word2vec-similarity}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract vectors\nword_vectors <-\n  masc_model[c(\"run_VERB\", \"walk_VERB\", \"run_NOUN\", \"walk_NOUN\"), ] |>\n  as.matrix()\n\n# Set seed for reproducibility\nset.seed(123)\n\npca <-\n  word_vectors |>\n  scale() |>\n  prcomp()\n\npca_tbl <-\n  as_tibble(pca$x[, 1:2]) |>\n  mutate(word = rownames(word_vectors))\n\npca_tbl |>\n  ggplot(aes(x = PC1, y = PC2, label = word)) +\n  geom_point() +\n  ggrepel::geom_text_repel()\n```\n\n::: {.cell-output-display}\n![Similarity between 'run' and 'walk' in the MASC dataset](8_explore_files/figure-html/fig-eda-masc-vsm-word2vec-similarity-1.png){#fig-eda-masc-vsm-word2vec-similarity width=384}\n:::\n:::\n\n:::\n\nFrom @fig-eda-masc-vsm-word2vec-similarity, we can see that each of these features occupies a distinct position in the reduced vector space. But on closer inspection, we can see that there is a relationship between the lemma pairs. Remember that PCA reduces the dimensionality of the data by identifying the dimensions that capture the greatest amount of variance in the data. This means that of the 50 dimensions in the model, the PC1 and PC2 correspond to orthogonal dimensions that capture the greatest amount of variance in the data. If we look along PC1, we can see that there is a distinction between POS. Looking along PC2, we see some pariety between lemma meanings. Given these features, we can see that meaning and grammatical category can be approximated in the vector space.\n\nAn interesting property of vector space models is that we can build up a dimension of meaning by adding vectors that we expect to approximate that meaning. For example, we can add the vectors for typical motion verbs to create a vector for motion-similarity and one for manner-similarity. We can then compare the feature vectors for all verbs and assess their motion-similarity and manner-similarity.\n\nTo do this let's first subset the model to only include verbs, as in @exm-eda-masc-vsm-word2vec-verbs. We will also remove the POS tags from the rownames of the matrix as they are no longer needed.\n\n::: {#exm-eda-masc-vsm-word2vec-verbs}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter to verbs\nverbs <- str_subset(rownames(masc_model), \".*_VERB\")\nverb_vectors <- masc_model[verbs, ]\n\n# Remove POS tags\nrownames(verb_vectors) <-\n  verb_vectors |>\n  rownames() |>\n  str_replace_all(\"_VERB\", \"\")\n\n# Inspect\ndim(verb_vectors)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1115  100\n```\n\n\n:::\n\n```{.r .cell-code}\n# Preview\nverb_vectors[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA VectorSpaceModel object of  5  words and  5  vectors\n          [,1]   [,2]    [,3]    [,4]   [,5]\nabsorb  -1.772 -1.528 -0.0554  0.6642 -1.245\nauction -2.083 -0.977 -0.2505 -0.0204 -0.874\nbid      0.217 -0.490 -0.4588  0.1373  0.247\nbrief    1.215 -0.674 -0.7121  0.5072 -0.445\ncap     -0.135  0.884  0.2278 -0.2563 -0.207\nattr(,\".cache\")\n<environment: 0x7f871b48f780>\n```\n\n\n:::\n:::\n\n:::\n\nWe now have `verb_vectors` which includes the vector representations for all verbs 1,115 in the MASC dataset. Next, let's seed the vectors for motion-similarity and manner-similarity and calculate the vector 'closeness' to the motion and manner seed vectors with the `closest_to()` function from the `wordVectors()` package.\n\n::: {#exm-eda-masc-vsm-word2vec-manner-motion}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add vectors for motion-similarity and manner-similarity\nmotion <-\n  c(\"go\", \"come\", \"leave\", \"arrive\", \"enter\", \"exit\", \"depart\", \"return\")\n\nmotion_similarity <-\n  verb_vectors |> closest_to(motion, n = Inf)\n\n# Preview\nmotion_similarity |> glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,115\nColumns: 2\n$ word                   <chr> \"walk\", \"step\", \"return\", \"enter\", \"leave\", \"le…\n$ `similarity to motion` <dbl> 0.742, 0.741, 0.732, 0.727, 0.682, 0.669, 0.664…\n```\n\n\n:::\n\n```{.r .cell-code}\nmanner <-\n  c(\"run\", \"walk\", \"jump\", \"crawl\", \"swim\", \"fly\", \"drive\", \"ride\")\n\nmanner_similarity <-\n  verb_vectors |> closest_to(manner, n = Inf)\n\n# Preview\nmanner_similarity |> glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,115\nColumns: 2\n$ word                   <chr> \"walk\", \"drop\", \"step\", \"hang\", \"rub\", \"shut\", …\n$ `similarity to manner` <dbl> 0.865, 0.841, 0.831, 0.826, 0.826, 0.824, 0.820…\n```\n\n\n:::\n:::\n\n:::\n\nThe `motion_similarity` and `manner_similarity` data frames each contain all the verbs with a corresponding closeness measure. We can join these two data frames by feature to create a single data frame with the motion-similarity and manner-similarity measures, as seen in @exm-eda-masc-vsm-word2vec-manner-motion.\n\n::: {#exm-eda-masc-vsm-word2vec-manner-motion}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join motion-similarity and manner-similarity\nmanner_motion_similarity <-\n  manner_similarity |>\n  inner_join(motion_similarity)\n\n# Preview\nmanner_motion_similarity |> glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,115\nColumns: 3\n$ word                   <chr> \"walk\", \"drop\", \"step\", \"hang\", \"rub\", \"shut\", …\n$ `similarity to manner` <dbl> 0.865, 0.841, 0.831, 0.826, 0.826, 0.824, 0.820…\n$ `similarity to motion` <dbl> 0.742, 0.642, 0.741, 0.635, 0.624, 0.589, 0.561…\n```\n\n\n:::\n:::\n\n:::\n\n\nThe result of @exm-eda-masc-vsm-word2vec-manner-motion is a data frame with the motion-similarity and manner-similarity measures for all verbs in the MASC dataset. We can now visualize the distribution of motion-similarity and manner-similarity measures, as seen in @fig-eda-masc-vsm-word2vec-manner-motion-compare.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Motion-similarity and manner-similarity of verbs in the MASC dataset](8_explore_files/figure-html/fig-eda-masc-vsm-word2vec-manner-motion-compare-1.png){#fig-eda-masc-vsm-word2vec-manner-motion-compare width=384}\n:::\n:::\n\n\nFrom @fig-eda-masc-vsm-word2vec-manner-motion-compare, we can see that the   manner-similarity is plotted on the x-axis and the motion-similarity on the y-axis. I've added horizontal and vertical lines to break the scatterplot into quadrants --the top-right corresponding to high manner- and motion-similiarity and the bottom-left corresponding to low manner- and motion-similarity. This captures the majority of the verbs in the dataset. The verbs in the top-left quadrant have high motion-similarity but lower manner similarity, and verbs in the bottom-right quadrant have high manner-similarity but lower motion-similarity.\n\nI've randomly sampled 50 verbs from the dataset and plotted them as text labels. I've also plotted the motion and manner seed vectors as triangle and box points, respectively. We can see that motion- and manner-similiarity seed verbs are found in the top-left quandrant together, showing that they are semantically related. Verbs in the other quadrants are either lower in motion- or manner-similarity, or both. From a qualitative point of view it appears that many of the verbs coincide with inuition. Some, however, less so. This is to be expected to some degree as the model is trained on a relatively small corpus. All in all, this serves as an example of how vector space modeling can be used to explore semantic relationships between linguistic features.\n\n## Activities {.unnumbered}\n\nExploratory analysis is a wide-ranging term that encompasses many different methods. In these activities, we will focus on the methods that are most commonly used in the analysis of textual data. These include frequency and distributional analysis, clustering, and word embedding models. We will model how to explore iteratively using the output of one method to inform the next and ultimately to address a research question.\n\n::: {.callout}\n**{{< fa regular file-code >}} Recipe**\n\n**What**: Exploratory analysis methods\\\n**How**: Read Recipe 8, complete comprehension check, and prepare for Lab 8.\\\n**Why**: To illustrate how to prepare a dataset for descriptive and unsupervised machine learning methods and evaluate the results for exploratory data analysis.\n:::\n\n::: {.callout}\n**{{< fa flask >}} Lab**\n\n**What**: Pattern discovery\\\n**How**: Clone, fork, and complete the steps in Lab 8.\\\n**Why**: To gain experience working with coding strategies to prepare, feature engineer, explore, and evaluate results from exploratory data analyses, practice transforming datasets into new object formats and visualizing relationships, and implement organizational strategies for organizing and reporting results in a reproducible fashion.\n:::\n\n## Summary {.unnumbered}\n\nIn this chapter, we surveyed a range of methods for uncovering insights from data, particularly when we do not have a predetermined hypothesis. We broke the chapter discussion along the two central branches of exploratory data analysis: descriptive analysis and unsupervised learning. Descriptive analysis offers statistical or visual summaries of datasets through frequency, dispersion, and co-occurrence measures, while unsupervised learning utilizes machine learning techniques to uncover patterns without predefining variable relationships. Here we covered a few unsupervised learning methods including clustering, diminensionality reduction, and vector space modeling. Through either descriptive or unsupervised learning methodologies, we probe questions in a data-driven fashion and apply methods to summarize, reduce, and sort complex datasets. This in turn facilitates novel, quantitative perspectives that can subsequently be evaluated qualitatively, offering us a robust approach to exploring and generating research questions.\n",
    "supporting": [
      "8_explore_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}