<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Quantitative Text Analysis for Linguistics - 2&nbsp; Understanding data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./approaching-analysis.html" rel="next">
<link href="./foundations.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://hypothes.is/embed.js"></script><script src="site_libs/quarto-diagram/mermaid.min.js"></script><script src="site_libs/quarto-diagram/mermaid-init.js"></script><link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link rel="stylesheet" href="assets/style.css">
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./foundations.html">Foundations</a></li><li class="breadcrumb-item"><a href="./understanding-data.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Understanding data</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Text Analysis for Linguistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./orientation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Orientation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./text-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Text analysis in context</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./understanding-data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Understanding data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./approaching-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Approaching analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framing-research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Framing research</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preparation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acquire-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Acquire data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./curate-datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Curate data(sets)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./transform-datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Transform datasets</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exploration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exploration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Prediction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Inference</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./communication.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Communication</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Reporting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./collaboration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Collaboration</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Data</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#data" id="toc-data" class="nav-link active" data-scroll-target="#data"><span class="header-section-number">2.1</span> Data</a>
  <ul class="collapse">
<li><a href="#populations" id="toc-populations" class="nav-link" data-scroll-target="#populations"><span class="header-section-number">2.1.1</span> Populations</a></li>
  <li><a href="#samples" id="toc-samples" class="nav-link" data-scroll-target="#samples"><span class="header-section-number">2.1.2</span> Samples</a></li>
  <li><a href="#corpora" id="toc-corpora" class="nav-link" data-scroll-target="#corpora"><span class="header-section-number">2.1.3</span> Corpora</a></li>
  </ul>
</li>
  <li>
<a href="#information" id="toc-information" class="nav-link" data-scroll-target="#information"><span class="header-section-number">2.2</span> Information</a>
  <ul class="collapse">
<li><a href="#structure" id="toc-structure" class="nav-link" data-scroll-target="#structure"><span class="header-section-number">2.2.1</span> Structure</a></li>
  <li><a href="#transformation" id="toc-transformation" class="nav-link" data-scroll-target="#transformation"><span class="header-section-number">2.2.2</span> Transformation</a></li>
  </ul>
</li>
  <li>
<a href="#documentation" id="toc-documentation" class="nav-link" data-scroll-target="#documentation"><span class="header-section-number">2.3</span> Documentation</a>
  <ul class="collapse">
<li><a href="#data-origin-information" id="toc-data-origin-information" class="nav-link" data-scroll-target="#data-origin-information"><span class="header-section-number">2.3.1</span> Data origin information</a></li>
  <li><a href="#data-dictionaries" id="toc-data-dictionaries" class="nav-link" data-scroll-target="#data-dictionaries"><span class="header-section-number">2.3.2</span> Data dictionaries</a></li>
  </ul>
</li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions">Questions</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-understanding-data" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Understanding data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><!--

Content:

- [x] Move the data sources section to the online companion website (qtalr.com) and link to it from here. Note: I will want to specify here and for all links that the LaTeX version should add links as footnotes and the HTML version should add links as hyperlinks.

Exercises:

Formatting:

--><blockquote class="blockquote">
<p>The goal is to turn data into information, and information into insight.</p>
<p>— Carly Fiorina</p>
</blockquote>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-list-alt" aria-label="list-alt"></i> Outcomes</strong></p>
<ul>
<li>Analyze the distinct types of data and compare their differences.</li>
<li>Define information and describe format it takes.</li>
<li>Evaluate the importance of documentation in promoting reproducible research.</li>
</ul>
</div>
</div>
</div>
<p>In this chapter, the groundwork is laid for deriving insights from data by focusing on Data and Information. The concepts of populations and samples are introduced, highlighting their similarities and key differences. Connecting these topics to text analysis, language samples or corpora are explored, discussing their types, sources, formats, and ethical considerations. Subsequently, key concepts in information, such as organization and transformation, are examined. The ‘tidy’ approach to organizing data is discussed, including structural characteristics and semantic attributes. Moreover, data transformation techniques are introduced, which can enhance the quality and usability of data in subsequent analysis steps. The importance of documentation in quantitative research is emphasized through addressing data origin and data dictionaries. Methods for documenting sources and processes are provided to ensure a comprehensive understanding of extracting valuable insights from data.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-terminal" aria-label="terminal"></i> Swirl lesson</strong></p>
<p><strong>What</strong>: <a href="https://github.com/qtalr/swirl">Objects, Packages and functions</a><br><strong>How</strong>: In the R Console pane load <code>swirl</code>, run <code>swirl()</code>, and follow prompts to select the lesson.<br><strong>Why</strong>: To introduce you to the main types of objects in R and to understand the role and use of functions and packages in R programming.</p>
</div>
</div>
</div>
<section id="data" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="data">
<span class="header-section-number">2.1</span> Data</h2>
<p>Data is data, right? The term ‘data’ is so common in popular vernacular it is easy to assume we know what we mean when we say ‘data’. But as in most things, where there are common assumptions there are important details the require more careful consideration. Let’s turn to the first key distinction that we need to make to start to break down the term ‘data’: the difference between populations and samples.</p>
<!-- When we talk about data, we often assume that it is objective and unbiased. However, this is not always the case. In fact, there are many important details about data that require more careful consideration. Let's explore one of these details: the difference between populations and samples -->
<section id="populations" class="level3" data-number="2.1.1"><h3 data-number="2.1.1" class="anchored" data-anchor-id="populations">
<span class="header-section-number">2.1.1</span> Populations</h3>
<!--  
- Definition and examples
- Relation to research question
-->
<p>The first thing that comes to many people’s mind when the term population is used is human populations (derived from Latin ‘populus’). Say for example we pose the question –What’s the population of Milwuakee? When we speak of a population in these terms we are talking about the total sum of individuals living within the geographical boundaries of Milwaukee. In concrete terms, a <strong>population</strong> an idealized set of objects or events in reality which share a common characteristic or belong to a specific category. The term to highlight here is idealized. Although we can look up the US Census report for Milwaukee and retrieve a figure for the population, this cannot truly be the population. Why is that? Well, whatever method that was used to derive this numerical figure was surely incomplete. If not incomplete, by the time someone recorded the figure some number of residents of Milwaukee moved out, moved in, were born, or passed away. In either case, this example serves to point out that populations are not fixed and are subject to change over time.</p>
<p>Likewise when we talk about populations in terms of language we dealing with an idealized aspect of reality. Let’s take the words of the English language as an analog to our previous example population. In this case the words are the people and English is the grouping characteristic. Just as people, words move out, move in, are born, and pass away. Any compendium of the words of English at any moment is almost instananeously incomplete. This is true for all populations, save those relatively rare cases in which the grouping characteristics select a narrow slice of reality which is objectively measurable and whose membership is fixed (the complete works of Shakespeare, for example).</p>
<p>In sum, (most) populations are amorphous moving targets. We subjectively hold them to exist, but in practical terms we often cannot nail down the specifics of populations. So how do researchers go about studying populations if they are theoretically impossible to access directly? The strategy employed is called sampling.</p>
</section><section id="samples" class="level3" data-number="2.1.2"><h3 data-number="2.1.2" class="anchored" data-anchor-id="samples">
<span class="header-section-number">2.1.2</span> Samples</h3>
<!--  
- Definition and examples
- Sampling techniques (e.g., size, random, stratified)
-->
<p>A <strong>sample</strong> is the product of a subjective process of selecting a finite set of observations from an idealized population with the goal of capturing the relevant characteristics of the target population. The <strong>degree of representativeness</strong> of a sample is the extent to which the sample reflects the characteristics of the population. The degree of representativeness is crucial form research as it directly impacts of any findings based on the sample.</p>
<!-- Although there are strategies to minimize the mismatch between the characteristics of the sample and population, it is important to note that it is almost certainly true that any given sample diverges from the population it aims to represent to some degree. The aim, however, is to employ a series of sampling decisions, which are collectively known as a sampling frame, that maximize the chance of representing the population. -->
<p>To maximize the representativeness of a sample, researchers employ a variety of strategies. One of the first and sometimes the easiest strategy is to increase the <strong>sample size</strong>. A larger sample will always be more representative than a smaller sample. Sample size, however, is often not enough. It is not hard to imagine a large sample which by chance captures only a subset of the features of the population. Another step to enhance sample representativeness is to apply <strong>random sampling</strong>. Together a large random sample has an even better chance of reflecting the main characteristics of the population better than a large or random sample. But, random as random is, we still run the risk of acquiring a skewed sample (<em>i.e.</em> a sample with low representativeness).</p>
<p>To help mitigate these issues, there are two more strategies that can be applied to improve sample representativeness. Note, however, that while size and random samples can be applied to any sample with little information about internal characteristics of the population, these next two strategies require decisions depend on the presumed internal characteristics of the population. The first of these more informed sampling strategies is called <strong>stratified sampling</strong>. Stratified samples make (educated) assumptions about sub-components within the population of interest. With these sub-populations in mind, large random samples are acquired for each sub-population, or strata. At a minimum, stratified samples can be no less representative than random sampling alone, but the chances that the sample is better increases. Can there be problems in the approach? Yes, and on two fronts. First knowledge of the internal components of a population are often based on a limited or incomplete knowledge of the population (remember populations are idealized). In other words, strata are selected subjectively by researchers using various heuristics some of which are based on some sense of ‘common knowledge’.</p>
<p>The second front on which stratified sampling can err concerns the relative sizes of the sub-components relative to the whole population. Even if the relevant sub-components are identified, their relative size adds another challenge which researchers must address in order to maximize the representativeness of a sample. To attempt to align, or <strong>balance</strong>, the relative sizes of the samples for the strata is the second population-informed sampling strategy.</p>
</section><section id="corpora" class="level3" data-number="2.1.3"><h3 data-number="2.1.3" class="anchored" data-anchor-id="corpora">
<span class="header-section-number">2.1.3</span> Corpora</h3>
<p>A key feature of a sample is that it is purposely selected. Samples are not simply a collection or set of data from the population. Samples are rigorously selected with an explicit target population in mind. In text analysis, a purposely sampled collection of texts, of the type defined here, is known as a <strong>corpus</strong> (pl. corpora). For this same reason a set of texts or documents which have not been selected along a purposely selected sampling frame is not a corpus rather a collection of documents. The sampling frame, and therefore the populations modeled, in any given corpus most likely will vary and for this reason it is not a safe assumption that any given corpus is equally applicable for any and every research question. Corpus development (<em>i.e.</em> language sampling) is purposeful, and the characteristics of the corpus development process should be made explicit through documentation. Therefore vetting a corpus sample for its applicability to a research goal is a key step in that a research must take to ensure the integrity of the research findings.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-lightbulb" aria-label="lightbulb"></i> Consider this</strong></p>
<p>The ‘Standard Sample of Present-Day American English’ (known commonly as the Brown Corpus) is widely recognized as one of the first large, machine-readable corpora. Compiled by <span class="citation" data-cites="Kucera1967">Kucera and Francis (<a href="references.html#ref-Kucera1967" role="doc-biblioref">1967</a>)</span>, the corpus is comprised of 1,014,312 words from edited English prose published in the United States in 1961.</p>
<p>Given the sampling frame for this corpus visualized in <a href="#fig-brown-distribution">Figure&nbsp;<span>2.1</span></a>:</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/fig-brown-distribution_514571969b77232897660d6ffd749637">
<div class="cell-output-display">
<div id="fig-brown-distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="understanding-data_files/figure-html/fig-brown-distribution-1.png" class="img-fluid figure-img" style="width:75.0%" alt="The Brown Corpus sampling frame is shown as a bar plot comprised of 15 main categories (strata) of text on the y-axis. The relative size of each category is shown as a percentage of the total number of words in the corpus on the x-axis. The largest categories are 'Fiction' (23%) and 'Press' (18%) and the smallest categories are 'Religion' (0.3%) and 'Learned' (0.2%)."></p>
<figcaption class="figure-caption">Figure&nbsp;2.1: Overview of the sampling frame of the Brown Corpus.</figcaption></figure>
</div>
</div>
</div>
<p>Can you determine what language population this corpus aims to represent? What types of research might this corpus support or not support?</p>
</div>
</div>
</div>
<section id="types" class="level4"><h4 class="anchored" data-anchor-id="types">Types</h4>
<section id="reference" class="level5"><h5 class="anchored" data-anchor-id="reference">Reference</h5>
<p>With the notion of sampling frames in mind, some corpora are compiled with the aim to be of general purpose (general or <strong>reference corpora</strong>), and some with much more specialized sampling frames (<strong>specialized corpora</strong>). For example, the <a href="https://www.anc.org/">American National Corpus (ANC)</a> or the <a href="http://www.natcorp.ox.ac.uk/">British National Corpus (BNC)</a> are corpora which aim to model (represent/ reflect) the general characteristics of a variety of the English language, the former of American English and the later British English. These are ambitious projects, and require significant investments of time in corpus design and then in implementation (and continued development) that are usually undertaken by research teams <span class="citation" data-cites="Adel2020">(<a href="references.html#ref-Adel2020" role="doc-biblioref">Ädel 2020</a>)</span>.</p>
</section><section id="specialized" class="level5"><h5 class="anchored" data-anchor-id="specialized">Specialized</h5>
<!-- 
- Modality (e.g., written, spoken, signed)
- Genre (e.g., news, fiction, academic, social media)
- Population (age, region, language background, etc.)
- Comparision (e.g., parallel, comparable)
-->
<p>Specialized corpora aim to represent more specific populations. The <a href="https://www.linguistics.ucsb.edu/research/santa-barbara-corpus">Santa Barbara Corpus of Spoken American English (SBCSAE)</a>, as you can imagine from the name of the resource, aims to model spoken American English. No claim to written English is included. There are even more specific types of corpora which attempt to model other types of sub-populations such as <a href="https://www.coventry.ac.uk/research/research-directories/current-projects/2015/british-academic-written-english-corpus-bawe/">academic writing</a>, <a href="https://www.clarin.eu/resource-families/cmc-corpora">computer-mediated communication (CMC)</a>, language use in specific <a href="http://ice-corpora.net/ice/index.html">regions of the world</a>, a <a href="https://www.wgtn.ac.nz/lals/resources/corpora-default/corpora-wsc">country</a>, a <a href="https://cesa.arizona.edu">region of a country</a>, <em>etc</em>.</p>
<!-- <img src="figures/understanding-data/word-mapper.png" width="200" align="right"/>  -->
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-lightbulb" aria-label="lightbulb"></i> Consider this</strong></p>
<p><span class="citation" data-cites="Grieve2018">Grieve, Nini, and Guo (<a href="references.html#ref-Grieve2018" role="doc-biblioref">2018</a>)</span> compiled a 8.9 billion-word corpus of geotagged posts from Twitter between 2013-2014 in the United States. The authors provide a <a href="https://isogloss.shinyapps.io/isogloss/">search interface</a> to explore relationship between lexical usage and geographic location. Explore this corpus searching for terms related to slang (“hella”, “wicked”), geographical (“mountain”, “river”), meteorological (“snow”, “rain”), and/ or any other term types. What types of patterns do you find? What are the benefits and/ or limitations of this type of data and/ or interface?</p>
</div>
</div>
</div>
<p>Another set of specialized corpora are resources which aim to compile texts from different languages or different language varieties for direct or indirect comparison. Corpora that are directly comparable, that is they include source and translated texts, are called <strong>parallel corpora</strong>. Parallel corpora include different languages or language varieties that are indexed and aligned at some linguistic level (<em>i.e.</em> word, phrase, sentence, paragraph, or document), see <a href="https://opus.nlpl.eu/">OPUS</a>. Corpora that are compiled with different languages or language varieties but are not directly aligned are called <strong>comparable corpora</strong>. The comparable language or language varieties are sampled with the same or similar sampling frame, for example <a href="https://ota.bodleian.ox.ac.uk/repository/xmlui/handle/20.500.12024/0402">Brown</a> and <a href="https://ota.bodleian.ox.ac.uk/repository/xmlui/handle/20.500.12024/0167">LOB</a> corpora.</p>
<p>The aim of the quantitative text researcher is to select the corpus or corpora (plural of corpus) which best aligns with the purpose of the research. For example, a general corpus such as the American National Corpus may be better suited to address a question dealing with the way American English works, but this general resource may lack detail in certain areas, such as <a href="https://mtsamples.com/index.asp">medical language</a>, that may be vital for a research project aimed at understanding changes in medical terminology. Furthermore, a researcher studying spoken language might collect a corpus of transcribed conversations from a particular community or region, such as the SBCSAE. While this would not include every possible spoken utterance produced by members of that group, it could be considered a representative sample of the population of speech in that context.</p>
</section></section><section id="sources" class="level4"><h4 class="anchored" data-anchor-id="sources">Sources</h4>
<!--  
- Publicly available datasets and repositories
- Custom-built corpora (web scraping, APIs, OCR, etc.)
- Ethical considerations for data collection
-->
<section id="published" class="level5 unnumbered"><h5 class="unnumbered anchored" data-anchor-id="published">Published</h5>
<p>The most common source of data used in contemporary quantitative research is the internet. On the web an investigator can access corpora published for research purposes and language used in natural settings that can be compiled by investigators into a corpus. Many organizations exist around the globe that provide access to corpora in browsable catalogs, or <strong>repositories</strong>. There are repositories dedicated to language research, in general, such as the <a href="https://www.ldc.upenn.edu/">Language Data Consortium</a> or for specific language domains, such as the language acquisition repository <a href="http://talkbank.org/">TalkBank</a>. It is always advisable to start looking for the available language data in a repository. The advantage of beginning your data search in repositories is that a repository, especially those geared towards the linguistic community, will make identifying language corpora faster than through a general web search. Furthermore, repositories often require certain standards for corpus format and documentation for publication. A standardized resource many times will be easier to interpret and evaluate for its appropriateness for a particular research project.</p>
<p>Repositories are by no means the only source of corpora on the web. Researchers from around the world provide access to corpora and datasets on their own sites or through data sharing platforms. Corpora of various sizes and scopes will often be accessible on a dedicated homepage or appear on the homepage of a sponsoring institution. These resources may be available for download (<em>e.g.</em> LDC) or via search inferaces (<em>e.g.</em> COCA). Finding these resources is often a matter of doing a web search with the word ‘corpus’ and a list of desired attributes, including language, modality, register, <em>etc</em>.</p>
<p>As part of a general movement towards reproducibility, more corpora are available on <strong>data sharing platforms</strong> such as <a href="https://github.com/">GitHub</a>, <a href="https://zenodo.org/">Zenodo</a>, <a href="http://www.re3data.org/">Re3data</a>, <a href="https://osf.io/">OSF</a>, <em>etc</em>. These platforms enable researchers to securely store, manage, and share data with others. Support is provided for various types of data, including documents and code, and as such they are a good place to look as they often include reproducible research projects as well.</p>
</section><section id="custom-built" class="level5 unnumbered"><h5 class="unnumbered anchored" data-anchor-id="custom-built">Custom-built</h5>
<p>Language corpora prepared by researchers and research groups listed on repositories or hosted by the researchers themselves is often the first place to look for data. The web, however, contains a wealth of language and language-related data that can be accessed by researcher to compile their own corpus. There are two primary ways to attain language data from the web. The first is through the process of web scraping. <strong>Web scraping</strong> is the process of harvesting data from the public-facing web. Language texts may be found on sites as uploaded files, such as pdf or doc (Word) documents, or found displayed as the primary text of a site. Given the wide variety of documents uploaded and language behavior recorded daily on news sites, blogs and the like, compiling a corpus has never been easier. Having said that, how the data is structured and how much data needs to be retrieved can pose practical obstacles to collecting data from the web, particularly if the approach is to acquire the data by manually instead of automating the task.</p>
<p>The second way to acquire data from the web is through an <strong>Application Programming Interface</strong> (API). APIs are, as the title suggests, programming interfaces which allow access, under certain conditions, to information that a website or database accessible via the web contains.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-medal" aria-label="medal"></i> Dive deeper</strong></p>
<p>The process of corpus development is a topic in and of itself. For a more in-depth discussion of the process, see <span class="citation" data-cites="Adel2020">Ädel (<a href="references.html#ref-Adel2020" role="doc-biblioref">2020</a>)</span> and …</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-lightbulb" aria-label="lightbulb"></i> Consider this</strong></p>
<!--  
- [x] Add link to Guide 5 on companion website
-->
<p>Explore some of the resources listed on the <a href="https://qtalr.github.io/qtalrkit/articles/guide-5.html">qtalrkit compansion site</a> and consider their sampling frames. Can you think of a research question or questions that this resource may be well-suited to support research into? What types of questions would be less-than-adequate for a given resource?</p>
</div>
</div>
</div>
</section><section id="ethical-considerations" class="level5"><h5 class="anchored" data-anchor-id="ethical-considerations">Ethical considerations</h5>
<!--  
- [ ] Revise this section
  - [ ] adding web scraping, APIs.
  - [ ] adding examples of licenses, permissions, and citation/ attribution
-->
<p>Ethical practices in corpus data collection involve adhering to principles and guidelines that ensure researchers’ work is used fairly, respectfully, and with integrity. A corpus represents a form of Intellectual Property (IP) and must be treated accordingly. Individual data resources often have their own licensing agreements and terms of use, ranging from public domain to proprietary licenses. Public domain licenses, such as those found in Project Gutenberg, allow anyone to use the data for any purpose. Creative Commons licenses, like those used by the American National Corpus, Wikipedia, and TalkBank, span from open to more restrictive uses, including requirements for attribution or prohibiting commercial use. More restrictive licenses, such as those for the Corpus of Contemporary American English and the British National Corpus, may require a fee to access and use the data.</p>
<p>Respecting intellectual property rights is crucial when working with corpus data. Violating these rights can lead to legal and ethical issues, including lawsuits, fines, and damage to one’s professional reputation. To avoid these problems, researchers must ensure they have the necessary permissions to use copyrighted works in their corpora. Obtaining permissions involves contacting the author or publisher and requesting consent to use their work for research purposes. Documenting all obtained permissions is essential to demonstrate compliance with IP laws and ethical guidelines.</p>
<p>Attribution and citation are critical aspects of respecting intellectual property rights in corpus data collection. Researchers should follow established citation guidelines, such as APA, MLA, or Chicago, to accurately credit original authors. Providing clear and consistent citations helps maintain transparency and ensures that authors receive appropriate recognition for their work. By prioritizing ethical practices, researchers can protect intellectual property rights and uphold the integrity of their research, fostering trust and credibility in their findings.</p>
</section></section><section id="formats" class="level4"><h4 class="anchored" data-anchor-id="formats">Formats</h4>
<p>A corpus will often include various types of non-linguistic attributes, or <strong>meta-data</strong>, as well. Ideally this will include information regarding the source(s) of the data, dates when it was acquired or published, and other author or speaker information. It may also include any number of other attributes that were identified as potentially important in order to appropriately document the target population. Again, it is key to match the available meta-data with the goals of your research. In some cases a corpus may be ideal in some aspects but not contain all the key information to address your research question. This may mean you will need to compile your own corpus if there are fundamental attributes missing. Before you consider compiling your own corpus, however, it is worth investigating the possibility of augmenting an available corpus to bring it inline with your particular goals. This may include adding new language sources, harnessing software for linguistic annotation (part-of-speech, syntactic structure, named entities, <em>etc</em>.), or linking available corpus meta-data to other resources, linguistic or non-linguistic.</p>
<p>Corpora come in various formats, the main three being: running text, structured documents, and databases. The format of a corpus is often influenced by characteristics of the data but may also reflect an author’s individual preferences as well. It is typical for corpora with few meta-data characteristics to take the form of running text.</p>
<p>Running text sample from the <a href="https://www.statmt.org/europarl/">Europarle Parallel Corpus</a>.</p>
<div class="cell" data-layout-align="center" data-linewidth="0.9" data-hash="understanding-data_cache/html/formats-europarle_2f4d0b4cd45e9275c8fca33995a6288f">
<div class="cell-output cell-output-stdout">
<pre><code>&gt; Resumption of the session
&gt; I declare resumed the session of the European Parliament adjourned on
Friday 17 December 1999, and I would like once again to wish you a
happy new year in the hope that you enjoyed a pleasant festive period.
&gt; Although, as you will have seen, the dreaded 'millennium bug' failed
to materialise, still the people in a number of countries suffered a
series of natural disasters that truly were dreadful.
&gt; You have requested a debate on this subject in the course of the next
few days, during this part-session.
&gt; In the meantime, I should like to observe a minute' s silence, as a
number of Members have requested, on behalf of all the victims
concerned, particularly those of the terrible storms, in the various
countries of the European Union.
&gt; Please rise, then, for this minute' s silence.
&gt; (The House rose and observed a minute' s silence)
&gt; Madam President, on a point of order.
&gt; You will be aware from the press and television that there have been
a number of bomb explosions and killings in Sri Lanka.
&gt; One of the people assassinated very recently in Sri Lanka was Mr
Kumar Ponnambalam, who had visited the European Parliament just a few
months ago.</code></pre>
</div>
</div>
<p>In corpora with more meta-data, a header may be appended to the top of each running text document or the meta-data may be contained in a separate file with appropriate coding to coordinate meta-data attributes with each text in the corpus.</p>
<p>Meta-data header sample from the <a href="">Switchboard Dialog Act Corpus</a>.</p>
<div class="cell" data-layout-align="center" data-linewidth="0.9" data-hash="understanding-data_cache/html/formats-swda_085765e0c2e42f558e73c0ff2f10c0b2">
<div class="cell-output cell-output-stdout">
<pre><code>&gt; FILENAME: 4325_1632_1519
&gt; TOPIC#: 323
&gt; DATE: 920323
&gt; TRANSCRIBER: glp
&gt; UTT_CODER: tc
&gt; DIFFICULTY: 1
&gt; TOPICALITY: 3
&gt; NATURALNESS: 2
&gt; ECHO_FROM_B: 1
&gt; ECHO_FROM_A: 4
&gt; STATIC_ON_A: 1
&gt; STATIC_ON_B: 1
&gt; BACKGROUND_A: 1
&gt; BACKGROUND_B: 2
&gt; REMARKS: None.
&gt;
&gt;
=========================================================================
&gt;
&gt;
&gt; o A.1 utt1: Okay.  /
&gt; qw A.1 utt2: {D So, }
&gt;
&gt; qy^d B.2 utt1: [ [ I guess, +
&gt;
&gt; + A.3 utt1: What kind of experience [ do you, + do you ] have, then
with child care? /
&gt;
&gt; + B.4 utt1: I think, ] + {F uh, } I wonder ] if that worked. /
&gt;
&gt; qy A.5 utt1: Does it say something? /
&gt;
&gt; sd B.6 utt1: I think it usually does.  /
&gt; ad B.6 utt2: You might try, {F uh, } /
&gt; h B.6 utt3: I don't know, /
&gt; ad B.6 utt4: hold it down a little longer, /
&gt; ad B.6 utt5: {C and } see if it, {F uh, } -/</code></pre>
</div>
</div>
<p>When meta-data and/ or linguistic annotation increases in complexity it is common to structure each corpus document more explicitly with a markup language such as XML (Extensible Markup Language) or organize relationships between language and meta-data attributes in a database.</p>
<p>XML format for meta-data (and linguistic annotation) from the <a href="http://www.nltk.org/nltk_data/">Brown Corpus</a>.</p>
<div class="cell" data-layout-align="center" data-linewidth="0.9" data-hash="understanding-data_cache/html/formats-brown_58fb54066d61a93099d78964248f9e18">
<div class="cell-output cell-output-stdout">
<pre><code>&gt; &lt;TEI
xmlns="http://www.tei-c.org/ns/1.0"&gt;&lt;teiHeader&gt;&lt;fileDesc&gt;&lt;titleStmt&gt;&lt;title&gt;Sample
A01 from The Atlanta Constitution&lt;/title&gt;&lt;title type="sub"&gt; November 4,
1961, p.1 "Atlanta Primary ..."
&gt; "Hartsfield Files"
&gt; August 17, 1961, "Urged strongly ..."
&gt; "Sam Caldwell Joins"
&gt; March 6,1961, p.1 "Legislators Are Moving" by Reg Murphy
&gt; "Legislator to fight" by Richard Ashworth
&gt; "House Due Bid..."
&gt; p.18 "Harry Miller Wins..."
&gt; &lt;/title&gt;&lt;/titleStmt&gt;&lt;editionStmt&gt;&lt;edition&gt;A part of the XML version
of the Brown Corpus&lt;/edition&gt;&lt;/editionStmt&gt;&lt;extent&gt;1,988 words 431
(21.7%) quotes 2
symbols&lt;/extent&gt;&lt;publicationStmt&gt;&lt;idno&gt;A01&lt;/idno&gt;&lt;availability&gt;&lt;p&gt;Used
by permission of The Atlanta ConstitutionState News Service (H), and
Reg Murphy (E).&lt;/p&gt;&lt;/availability&gt;&lt;/publicationStmt&gt;&lt;sourceDesc&gt;&lt;bibl&gt;
The Atlanta
Constitution&lt;/bibl&gt;&lt;/sourceDesc&gt;&lt;/fileDesc&gt;&lt;encodingDesc&gt;&lt;p&gt;Arbitrary
Hyphen: multi-million [0520]&lt;/p&gt;&lt;/encodingDesc&gt;&lt;revisionDesc&gt;&lt;change
when="2008-04-27"&gt;Header auto-generated for TEI
version&lt;/change&gt;&lt;/revisionDesc&gt;&lt;/teiHeader&gt;
&gt; &lt;text xml:id="A01" decls="A"&gt;
&gt; &lt;body&gt;&lt;p&gt;&lt;s n="1"&gt;&lt;w type="AT"&gt;The&lt;/w&gt; &lt;w type="NP"
subtype="TL"&gt;Fulton&lt;/w&gt; &lt;w type="NN" subtype="TL"&gt;County&lt;/w&gt; &lt;w
type="JJ" subtype="TL"&gt;Grand&lt;/w&gt; &lt;w type="NN" subtype="TL"&gt;Jury&lt;/w&gt; &lt;w
type="VBD"&gt;said&lt;/w&gt; &lt;w type="NR"&gt;Friday&lt;/w&gt; &lt;w type="AT"&gt;an&lt;/w&gt; &lt;w
type="NN"&gt;investigation&lt;/w&gt; &lt;w type="IN"&gt;of&lt;/w&gt; &lt;w
type="NPg"&gt;Atlanta's&lt;/w&gt; &lt;w type="JJ"&gt;recent&lt;/w&gt; &lt;w
type="NN"&gt;primary&lt;/w&gt; &lt;w type="NN"&gt;election&lt;/w&gt; &lt;w
type="VBD"&gt;produced&lt;/w&gt; &lt;c type="pct"&gt;``&lt;/c&gt; &lt;w type="AT"&gt;no&lt;/w&gt; &lt;w
type="NN"&gt;evidence&lt;/w&gt; &lt;c type="pct"&gt;''&lt;/c&gt; &lt;w type="CS"&gt;that&lt;/w&gt; &lt;w
type="DTI"&gt;any&lt;/w&gt; &lt;w type="NNS"&gt;irregularities&lt;/w&gt; &lt;w
type="VBD"&gt;took&lt;/w&gt; &lt;w type="NN"&gt;place&lt;/w&gt; &lt;c type="pct"&gt;.&lt;/c&gt; &lt;/s&gt;
&gt; &lt;/p&gt;</code></pre>
</div>
</div>
<p>Although there has been a push towards standardization of corpus formats, most available resources display some degree of idiosyncrasy. Being able to parse the structure of a corpus is a skill that will develop with time. With more experience working with corpora you will become more adept at identifying how the data is stored and whether its content and format will serve the needs of your analysis.</p>
</section></section></section><section id="information" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="information">
<span class="header-section-number">2.2</span> Information</h2>
<p>Identifying an adequate corpus resource for the target research question is the first step in moving a quantitative text research project forward. The next step is to select the components or characteristics of this resource that are relevant for the research and then move to organize the attributes of this data into a more useful and informative format. This is the process of converting a corpus into a <strong>dataset</strong> –a tabular representation of the information to be leveraged in the analysis.</p>
<section id="structure" class="level3" data-number="2.2.1"><h3 data-number="2.2.1" class="anchored" data-anchor-id="structure">
<span class="header-section-number">2.2.1</span> Structure</h3>
<p>Data alone is not informative. Only through explicit organization of the data in a way that makes relationships explicit does the data become information. In this form, our data is called a dataset. This is a particularly salient hurdle in text analysis research. Many textual sources are <strong>unstructured data</strong> –that is, the relationships that will be used in the analysis have yet to be purposefully drawn and organized from the text to make the relationships meaningful and useful for analysis.</p>
<p>For the running text in the Europarle Corpus, we know that there are files which are the source text (original) and files that correspond to the target text (translation). In <a href="#tbl-structure-europarle">Table&nbsp;<span>2.1</span></a> we see that this text has been organized so that there are columns corresponding to the <code>type</code> and <code>sentence</code> with an additional <code>sentence_id</code> column to keep an index of how the sentences are aligned.</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-hand-point-up" aria-label="hand-point-up"></i> Tip</strong></p>
<p>It is conventional to work with column names for datasets in R using the same conventions that are used for naming objects. It is a matter of taste which convention is used, but I have adopted <a href="https://bookdown.org/content/d1e53ac9-28ce-472f-bc2c-f499f18264a3/names.html#snake_case">snake case</a> as my personal preference. There are also <a href="https://bookdown.org/content/d1e53ac9-28ce-472f-bc2c-f499f18264a3/names.html">alternatives</a>. Regardless of the convention you choose, it is good practice to be consistent.</p>
<p>It is also of note that the column names should be balanced for meaningfulness and brevity. This brevity is of practical concern but can be somewhat opaque. For questions into the meaning of the column and is values consult the resource’s dataset documentation.</p>
</div>
</div>
</div>
<!-- Unstructured, to tabular -->
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-structure-europarle_e83f38f65cb10dafd8aaa6e68ac10a28">
<div class="cell-output-display">
<div id="tbl-structure-europarle" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.1: First 10 source and target sentences in the Europarle Corpus.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 80%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">sentence</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Resumption of the session</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Reanudación del período de sesiones</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">I declare resumed the session of the European Parliament adjourned on Friday 17 December 1999, and I would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Declaro reanudado el período de sesiones del Parlamento Europeo, interrumpido el viernes 17 de diciembre pasado, y reitero a Sus Señorías mi deseo de que hayan tenido unas buenas vacaciones.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Although, as you will have seen, the dreaded ‘millennium bug’ failed to materialise, still the people in a number of countries suffered a series of natural disasters that truly were dreadful.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Como todos han podido comprobar, el gran “efecto del año 2000” no se ha producido. En cambio, los ciudadanos de varios de nuestros países han sido víctimas de catástrofes naturales verdaderamente terribles.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">You have requested a debate on this subject in the course of the next few days, during this part-session.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Sus Señorías han solicitado un debate sobre el tema para los próximos días, en el curso de este período de sesiones.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">In the meantime, I should like to observe a minute’ s silence, as a number of Members have requested, on behalf of all the victims concerned, particularly those of the terrible storms, in the various countries of the European Union.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">A la espera de que se produzca, de acuerdo con muchos colegas que me lo han pedido, pido que hagamos un minuto de silencio en memoria de todas las víctimas de las tormentas, en los distintos países de la Unión Europea afectados.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Please rise, then, for this minute’ s silence.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Invito a todos a que nos pongamos de pie para guardar un minuto de silencio.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">(The House rose and observed a minute’ s silence)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">(El Parlamento, de pie, guarda un minuto de silencio)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Madam President, on a point of order.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Señora Presidenta, una cuestión de procedimiento.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">You will be aware from the press and television that there have been a number of bomb explosions and killings in Sri Lanka.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Sabrá usted por la prensa y la televisión que se han producido una serie de explosiones y asesinatos en Sri Lanka.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">One of the people assassinated very recently in Sri Lanka was Mr Kumar Ponnambalam, who had visited the European Parliament just a few months ago.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Una de las personas que recientemente han asesinado en Sri Lanka ha sido al Sr.&nbsp;Kumar Ponnambalam, quien hace pocos meses visitó el Parlamento Europeo.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<!-- Semi-structured, to tabular -->
<p>Other corpus resources are <strong>semi-structured data</strong> –that is, there are some characteristics which are structured, but other which are not.</p>
<p>The Switchboard Dialog Act Corpus is an example of a semi-structured resource. It has meta-data associated with each of the 1,155 conversations in the corpus. In <a href="#tbl-structure-swda">Table&nbsp;<span>2.2</span></a> a language-relevant sub-set of the meta-data is associated with each utterance.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-structure-swda_db0325bda0cd90c35b6c87d0b334c8c1">
<div class="cell-output-display">
<div id="tbl-structure-swda" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.2: First 5 utterances from the Switchboard Dialog Act Corpus.</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 47%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">doc_id</th>
<th style="text-align: right;">speaker_id</th>
<th style="text-align: right;">topic_num</th>
<th style="text-align: left;">topicality</th>
<th style="text-align: left;">naturalness</th>
<th style="text-align: left;">damsl_tag</th>
<th style="text-align: left;">speaker</th>
<th style="text-align: left;">utterance_num</th>
<th style="text-align: left;">utterance_text</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">4325</td>
<td style="text-align: right;">1632</td>
<td style="text-align: right;">323</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">o</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">Okay. /</td>
</tr>
<tr class="even">
<td style="text-align: left;">4325</td>
<td style="text-align: right;">1632</td>
<td style="text-align: right;">323</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">qw</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">{D So, }</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4325</td>
<td style="text-align: right;">1519</td>
<td style="text-align: right;">323</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">qy^d</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">[ [ I guess, +</td>
</tr>
<tr class="even">
<td style="text-align: left;">4325</td>
<td style="text-align: right;">1632</td>
<td style="text-align: right;">323</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">+</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">What kind of experience [ do you, + do you ] have, then with child care? /</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4325</td>
<td style="text-align: right;">1519</td>
<td style="text-align: right;">323</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">+</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">I think, ] + {F uh, } I wonder ] if that worked. /</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<!-- Structured, to tabular -->
<p>Relatively fewer resources are <strong>structured datasets</strong>. In these cases a high amount of meta-data and/ or linguistic annotation is included in the corpus. The format convention, however, varies from resource to resource. Some of the formats are programming general (.csv, .xml, .json, <em>etc</em>.) and others are resource specific (.cha, .utt, .prd, <em>etc</em>.). In <a href="#tbl-structure-brown">Table&nbsp;<span>2.3</span></a> the XML version of the Brown Corpus is represented in tabular format. Note that along with other meta-data variables, it also contains a variable with linguistic annotation for grammatical category (<code>pos</code> part-of-speech) of each word.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-structure-brown_1b5f8f8e02051bafd4534d378bea056d">
<div class="cell-output-display">
<div id="tbl-structure-brown" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.3: First 10 words from the Brown Corpus.</caption>
<thead><tr class="header">
<th style="text-align: left;">document_id</th>
<th style="text-align: left;">category</th>
<th style="text-align: left;">words</th>
<th style="text-align: left;">pos</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">The</td>
<td style="text-align: left;">AT</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Fulton</td>
<td style="text-align: left;">NP</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">County</td>
<td style="text-align: left;">NN</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Grand</td>
<td style="text-align: left;">JJ</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Jury</td>
<td style="text-align: left;">NN</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">said</td>
<td style="text-align: left;">VBD</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Friday</td>
<td style="text-align: left;">NR</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">an</td>
<td style="text-align: left;">AT</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">of</td>
<td style="text-align: left;">IN</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<section id="ud-tidy-data" class="level4"><h4 class="anchored" data-anchor-id="ud-tidy-data">Tidy Data</h4>
<p>The selection of the attributes from a corpus and the juxtaposition of these attributes in a relational format, or dataset, that converts data into information is known as <strong>data curation</strong>. The process of data curation minimally involves creating a base dataset, or <em>derived dataset</em>, which establishes the main informational associations according to philosophical approach outlined by <span class="citation" data-cites="Wickham2014a">Wickham (<a href="references.html#ref-Wickham2014a" role="doc-biblioref">2014</a>)</span>.</p>
<p>In this work, a <strong>tidy dataset</strong> refers both to the structural (physical) and informational (semantic) organization of the dataset. Physically, a tidy dataset is a tabular data structure where each <em>row</em> is an observation and each <em>column</em> is a variable that contains measures of a feature or attribute of each observation. Each cell where a given row-column intersect contains a <em>value</em> which is a particular attribute of a particular observation for the particular observation-feature pair also known as a <em>data point</em>.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/fig-tidy-format-image_763ace243af3bd09344ddd7fd659b118">
<div class="cell-output-display">
<div id="fig-tidy-format-image" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="figures/understanding-data/tidy-format-paper.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2.2: Visual summary of the tidy format.</figcaption></figure>
</div>
</div>
</div>
</section><section id="ud-informational-values" class="level4"><h4 class="anchored" data-anchor-id="ud-informational-values">Informational values</h4>
<p>In a tidy dataset, each column represents a <strong>variable</strong> that measures a specific attribute with varying values. These values can be classified into two primary types: <strong>categorical</strong> and <strong>numeric</strong>. To further refine this classification, we can identify four distinct types of values: nominal, ordinal, interval, and ratio. Collectively, these four types are referred to as <strong>levels of measurement</strong>. By categorizing values into either categorical or numeric groups, we can better understand how to apprroach and analyze the data within each column.</p>
<!-- Provide a brief description of the two types of variables and their sub-types. -->
<p>Categorical variables are qualitative measures and can be further broken down into <strong>nominal</strong> and <strong>ordinal</strong>. Numeric variables are quantitative measures and can be further broken down into <strong>interval</strong> and <strong>ratio</strong>. The informational values of these variables are summarized in <a href="#fig-ud-informational-values">Figure&nbsp;<span>2.3</span></a>.</p>
<div class="cell" data-fig-attr="width=100%">
<div class="cell-output-display">
<div id="fig-ud-informational-values" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><div>
<pre class="mermaid mermaid-js" data-label="fig-ud-informational-values">%% Set node colors to greyscale

graph TD
classDef tier1 fill:#aaa,stroke:#333,stroke-width:1px;
classDef tier2 fill:#ccc,stroke:#333,stroke-width:1px;
classDef tier3 fill:#eee,stroke:#333,stroke-width:1px;

A[Variables]:::tier1 --&gt; |Attributes| B[Categorical]:::tier2
A --&gt; |Quantities| C[Numeric]:::tier2

B --&gt; |Categories| D[Nominal]:::tier3
B --&gt; |Nominal + ordered categories| E[Ordinal]:::tier3

C --&gt; |Ordinal + equal intervals| F[Interval]:::tier3
C --&gt; |Interval + non-arbitrary zero| G[Ratio]:::tier3
</pre>
</div>
<figcaption class="figure-caption">Figure&nbsp;2.3: Informational values of variables.</figcaption></figure>
</div>
</div>
</div>
<ul class="task-list">
<li><p><input type="checkbox">Create a drawio diagram for this figure.</p></li>
<li><p><input type="checkbox">Provide examples of each of these types of levels of measurement.</p></li>
</ul>
<p>…. examples of levels of measurement ….</p>
<!-- 
-[ ] Consider  if this is a good moment to introduce the concept of informational values. Or if just make mention of it and then introduce it later.

Examples categorical variables: 

* Number of vowels in a word: This variable can only take on integer values and can be counted easily.

* Frequency of word use: This variable can be measured by counting how many times a particular word appears in a corpus.

* Age range of speakers: This variable can be broken down into categories such as 18-24, 25-34, 35-44, etc.

* Parts of speech: Parts of speech are categories used to describe words in a sentence. For example, nouns, verbs, adjectives, etc.

* Syllable structure: The number of syllables in a word can only take on integer values, making it a discrete variable.

* Sentence length: The number of words or syllables in a sentence.

* Language family: The language that the speaker uses can be grouped into various language families such as Indo-European, Semitic, Sino-Tibetan, etc.


Examples numeric variables:

* Duration of speech sounds: The length of time it takes to produce a vowel or consonant sound.

* Frequency of voice pitch: The number of times per second that a person's vocal cords vibrate when producing speech.

* Reaction time: The amount of time it takes for a speaker to respond to a prompt or question.

More applicable to text analysis: 

* Age of speaker: The age of the speaker is a continuous variable because it can take on any value (depending on the level of granularity). For example, a speaker can be 18.5 years old.

* Term-Frequency Inverse-Document Frequency (TF-IDF):  is a measure which is used to determine the importance of a word in a corpus. It is a continuous variable because it can take on any value between 0 and 1.

* Type-Token Ratio (TTR): The ratio of the number of unique words in a corpus to the total number of words in the corpus. It is a continuous variable because it can take on any value between 0 and 1.

* Collocation strength: The strength of association between two linguistic units in a corpus (per a particular measurement) is a continuous varaible as it can take any non-negative real number. 

-->
<!--

Levels of Measurement in Statistical Analysis
There are 4 levels of measurement in statistical analysis:

Nominal
Ordinal
Interval
Ratio

The four levels of measurement are grouped into two categories based on the type and amount of information they provide. Nominal and ordinal are considered qualitative or categorical data, while interval and ratio are considered quantitative or numerical data. 

Qualitative data consists of non-numerical measurements that express attributes such as colors, names, and categories.
Quantitative data comprises numerical measurements that indicate quantities such as height, weight, temperature, and time.


Nominal Level

At the nominal level, data is categorized into distinct categories, and there's no inherent order or ranking among them. Nominal scales classify data into distinct groups or categories that have no inherent order. The only operations allowed on nominal data are counting frequency and calculating percentages.

Examples using measures relevant to linguistic studies could be:

* Native language: English, Spanish, Chinese
* Part of speech: noun, verb, adjective
* Gender: male, female, non-binary
* Phrase type: noun phrase, verb phrase, prepositional phrase
* Region of origin: Northeast, Southeast, Midwest
* Grammatical role: subject, object, indirect object, direct object, prepositional object
* Word form: base form, past tense, past participle, present participle, gerund, infinitive

Ordinal Level

At the ordinal level, data is ranked in a particular order, but the difference between the ranks does not have any meaning. Ordinal scales represent data that can be arranged in an ordered sequence or series but do not have equal intervals between them. These types of data allow us to rank items or events in a meaningful way, but we cannot calculate the difference between the ranks.

Examples using measures relevant to linguistic studies could be:

* Educational degree: high school, bachelor's, master's, PhD
* Language proficiency: beginner, intermediate, advanced
* Frequency of use: never, rarely, sometimes, often, always
* Level of formality: colloquial, informal, formal, academic
* Age group of speaker: 18-24, 25-34, 35-44, 45-54, 55-64, 65+

Interval Level

At the interval level, data is measured on a scale with equal intervals between points, but do not have a true zero point. Interval scales measure data with equal intervals between values; however, they do not have a true zero point. This means that ratios cannot be calculated. 

Examples using measures relevant to linguistic studies could be:

* Time: minutes, hours, days
* Standardized test scores
* Frequency of word use per million words of text
* Scale of attitude: strongly disagree, disagree, neutral, agree, strongly agree

Ratio Level

At the ratio level, data can be measured on a scale with equal intervals, and there is a true zero point. Ratio scales possess all the characteristics of interval scales but also have a true zero point. This allows for meaningful ratios to be calculated.

Examples using measures relevant to linguistic studies could be:

* Age (years)
* Words per minute (speaking, writing)
* Number of syllables per word
* Word frequency per sentence
* Number of errors made in a writing sample
* Number of words in a text
* Response time (in milliseconds)

I hope this helps you better understand the different levels of measurement in statistical analysis, as well as providing some examples specific to linguistic studies at each level!

-->
</section><section id="ud-semantic-value" class="level4"><h4 class="anchored" data-anchor-id="ud-semantic-value">Semantic value</h4>
<p>Semantic value in a tidy dataset is derived from the association of this physical structure along the two dimensions of this rectangular format. First, each column is a variable which reflects measures for a particular attribute that can take on different values. In this way it ‘varies’.</p>
<p>In the Europarle Corpus dataset, in Table <a href="#tbl-structure-europarle">Table&nbsp;<span>2.1</span></a>, for example, the <code>type</code> column measures the type of text, either <code>Source</code> or <code>Target</code>. Futhermore variables can contain measures which are either qualitative or quantitative, that is category- or scale-based.</p>
<p>Second, each row is an <strong>observation</strong> that contains all of the variables associated with the primary <strong>unit of observation</strong>. The primary unit of observation the variable that is the essential focus of the informational structure. In this same dataset the first observation contains the <code>type</code>, <code>sentence_id</code>, and the <code>sentence</code>. As this dataset is currently structured, the primary unit of investigation is the <code>sentence</code> as each of the other variables have measures that characterize each value of <code>sentence</code>.</p>
<p>The decision as to what the primary unit of observation is is fundamentally guided by the research question, and therefore highly specific to the particular research project. Say instead we wanted to focus on words instead of sentences. The dataset would need to be transformed such that a new variable (<code>words</code>) would be created and each row would index a word in the corpus.</p>
<!--

- [ ] Incorporate the role of unit of analysis and unit of observation into the discussion of dataset organization (under Information section).
  - [ ] What role does the unit of analysis and the unit of observation play in structuring the dataset?
      - Define unit of analysis: the levels of observation that are the focus of the analysis (e.x. speaker, language, text genre, etc.)
      - Define unit of observation: the types of data that is collected for each unit of analysis (e.x. text, utterances, n-grams, words, lemmas, morphemes, etc.)
  - [ ] The unit of analysis and the unit of observation are derived from the research question or hypothesis.
    - [ ] Add examples of research questions and hypotheses that would lead to different units of analysis and units of observation. Such as "A what rate does lexical diversity increase for second language learners of Spanish whose first language is English?" Unit of analysis: learners. Unit of observation: words at distinct levels. 


---- 

NOTES:

The *unit of analysis refers to the entity that is studied and analyzed* in a research study or corpus linguistics, while the *unit of observation refers to the specific item or element that is actually observed or measured* within the selected unit of analysis. In simpler terms, the unit of analysis is the larger context while the unit of observation is the subset within that context.

Examples of primary unit of analysis:

* Words: The most common unit of analysis in corpus linguistics is the word. Researchers often examine the use of different types of words, such as nouns or verbs, or the frequency of specific individual words.

* Phrases: Phrases can also be a useful unit of analysis in corpus linguistics. For example, researchers might examine the frequency of certain collocations or the use of particular grammatical structures.

* Sentences: Sentences can provide valuable insights into how language is used, particularly in terms of syntax and grammar. Researchers might analyze sentence length or the use of specific sentence structures.

* Discourse: Discourse refers to larger units of language use, such as conversations, speeches, or written texts. Researchers might analyze patterns in discourse, such as how speakers use language to convey social status or power.

* Speakers/Writers: Another important unit of analysis in corpus linguistics is the individual speaker or writer. Researchers might analyze differences between male and female speakers, regional dialects, or the language use of different age groups.

* Language and language varieties: Researchers might also analyze differences between languages or language varieties. For example, researchers might compare the use of different types of words in English and Spanish, or the use of different grammatical structures in British and American English.

Examples of primary unit of observation:

* Tokens
* Types
* Lemmas
* Part-of-speech tags
* Sentences
* Paragraphs
* Documents
* Speakers
* Languages
* Genres
* Years/time periods
* Social media posts
* Comments/reviews
* Text messages


Note that the unit of observation is the entity or object on which data is collected or measured and there can be multiple units of observation for a given unit of analysis. 

-->
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-tidy-words-europarle_fc9da685082ad9bc96bb1e6f9a6821bb">
<div class="cell-output-display">
<div id="tbl-tidy-words-europarle" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.4: Europarle Paralle Corpus with <code>words</code> as primary unit of investigation.</caption>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">words</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Resumption</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">of</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">the</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">session</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Reanudación</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">del</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">período</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">de</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">sesiones</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The values for the variables <code>type</code> and <code>sentence_id</code> maintain the necessary description for each <code>word</code> to ensure the required semantic relationships to identify the particular attributes for each word observation. This dataset may seem redundant in that the values for <code>type</code> and <code>sentence_id</code> are repeated numerous times but this ‘redundancy’ makes the relationship between each variable associated with the primary unit of investigation explicit. This format makes a tidy dataset a versatile format for researchers to conduct analyses in a powerful and flexible way, as we will see throughout this textbook.</p>
<p>It is important to make clear that data in tabular format in itself does not constitute a dataset, in the tidy sense we will be using. Data can be organized in many ways which do not make relationships between variables and observations explicit.</p>

<!-- *Consider adding some 'messy' data and/ or summary tables which do not reflect the relational structure we are aiming to create to base our research on.* -->
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-lightbulb" aria-label="lightbulb"></i> Consider this</strong></p>
<p>All tabular data does not have the ‘tidy’ format that I have described here. Can you think of examples of tabular information that would not be in a tidy format? What would be the implications of this for data analysis?</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-lightbulb" aria-label="lightbulb"></i> Consider this</strong></p>
<p>Consider the following dataset:</p>
<p>What is the primary unit of observation in this dataset? What are the variables? What are the values for each variable? What is the semantic value of this dataset?</p>
</div>
</div>
</div>
</section></section><section id="transformation" class="level3" data-number="2.2.2"><h3 data-number="2.2.2" class="anchored" data-anchor-id="transformation">
<span class="header-section-number">2.2.2</span> Transformation</h3>
<p>At this point have introduced the first step in data curation in which the original data is converted into a relational dataset (derived dataset) and highlighted the importance of this informational structure for setting the stage for data analysis. However, the primary derived dataset is often not the final organizational step before proceeding to statistical analysis. Many times, if not always, the derived dataset requires some manipulation or transformation to prepare the dataset for the specific analysis approach to be taken. This is another level of human intervention and informational organization, and therefore another step forward in our journey from data to insight and as such a step up in the DIKI hierarchy. Common types of transformations include cleaning variables (normalization), separating or eliminating variables (recoding), creating new variables (generation), or incorporating others datasets which integrate with the existing variables (merging). The results of these transformations build on and manipulate the derived dataset and produce an <em>analysis dataset</em>. Let’s now turn to provide a select set of examples of each of these transformations using the datasets we have introduced in this chapter.</p>
<!--
- [ ] Highlight the changes in the datasets visually so that it is easier for the reader to see the changes.
-->
<section id="normalization" class="level4"><h4 class="anchored" data-anchor-id="normalization">Normalization</h4>
<p>The process of normalization aims to <em>sanitize</em> the values within a variable or set of variables. This may include removing whitespace, punctuation, numerals, or special characters or substituting uppercase for lowercase characters, numerals for word versions, acronyms for their full forms, irregular or incorrect spelling for accepted forms, or removing common words (<strong>stopwords</strong>), <em>etc</em>.</p>
<!-- - Remove non-speech -->
<p>On inspecting the Europarle dataset (<a href="#tbl-structure-europarle">Table&nbsp;<span>2.1</span></a>) we will see that there are sentence lines which do not represent actual parliament speeches. In <a href="#tbl-normalize-non-speech-identify-europarle">Table&nbsp;<span>2.5</span></a> we see these lines.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-normalize-non-speech-identify-europarle_880c8785318a8ca5360535785aaed944">
<div class="cell-output-display">
<div id="tbl-normalize-non-speech-identify-europarle" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.5: Non-speech lines in the Europarle dataset.</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 16%">
<col style="width: 73%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">sentence</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Resumption of the session</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Reanudación del período de sesiones</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">(The House rose and observed a minute’ s silence)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">(El Parlamento, de pie, guarda un minuto de silencio)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A research project aiming to analyze speech would want to normalize this dataset removing these lines, as seen in <a href="#tbl-normalize-non-speech-remove-europarle">Table&nbsp;<span>2.6</span></a>.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-normalize-non-speech-remove-europarle_187f168d101add70733722560db3c247">
<div class="cell-output-display">
<div id="tbl-normalize-non-speech-remove-europarle" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.6: The Europarle dataset with non-speech lines removed.</caption>
<colgroup>
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 92%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">sentence</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">I declare resumed the session of the European Parliament adjourned on Friday 17 December 1999, and I would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Declaro reanudado el período de sesiones del Parlamento Europeo, interrumpido el viernes 17 de diciembre pasado, y reitero a Sus Señorías mi deseo de que hayan tenido unas buenas vacaciones.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Although, as you will have seen, the dreaded ‘millennium bug’ failed to materialise, still the people in a number of countries suffered a series of natural disasters that truly were dreadful.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Como todos han podido comprobar, el gran “efecto del año 2000” no se ha producido. En cambio, los ciudadanos de varios de nuestros países han sido víctimas de catástrofes naturales verdaderamente terribles.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">You have requested a debate on this subject in the course of the next few days, during this part-session.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Sus Señorías han solicitado un debate sobre el tema para los próximos días, en el curso de este período de sesiones.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">In the meantime, I should like to observe a minute’ s silence, as a number of Members have requested, on behalf of all the victims concerned, particularly those of the terrible storms, in the various countries of the European Union.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">A la espera de que se produzca, de acuerdo con muchos colegas que me lo han pedido, pido que hagamos un minuto de silencio en memoria de todas las víctimas de las tormentas, en los distintos países de la Unión Europea afectados.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Please rise, then, for this minute’ s silence.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Invito a todos a que nos pongamos de pie para guardar un minuto de silencio.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Madam President, on a point of order.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Señora Presidenta, una cuestión de procedimiento.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">You will be aware from the press and television that there have been a number of bomb explosions and killings in Sri Lanka.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Sabrá usted por la prensa y la televisión que se han producido una serie de explosiones y asesinatos en Sri Lanka.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">One of the people assassinated very recently in Sri Lanka was Mr Kumar Ponnambalam, who had visited the European Parliament just a few months ago.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Una de las personas que recientemente han asesinado en Sri Lanka ha sido al Sr.&nbsp;Kumar Ponnambalam, quien hace pocos meses visitó el Parlamento Europeo.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<!-- - Remove whitespace (possessives) -->
<p>Another feature of this dataset which may require attention is the fact that the English lines include whitespace between possessive nouns.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-normalize-whitespace-identify-europarle_12299ab7fd261cb707e9a32576f64234">
<div class="cell-output-display">
<div id="tbl-normalize-whitespace-identify-europarle" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.7: Lines with possessives with extra whitespace in the Europarle dataset.</caption>
<colgroup>
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 92%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">sentence</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">In the meantime, I should like to observe a minute’ s silence, as a number of Members have requested, on behalf of all the victims concerned, particularly those of the terrible storms, in the various countries of the European Union.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Please rise, then, for this minute’ s silence.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>This may affect another transformation process or subsequent analysis, so it may be a good idea to normalize these forms by removing the extra whitespace.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-normalize-whitespace-remove-europarle_95a5347ee908c5719b74c46120dd7cab">
<div class="cell-output-display">
<div id="tbl-normalize-whitespace-remove-europarle" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.8: The Europarle dataset with whitespace from possessives removed.</caption>
<colgroup>
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 92%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">sentence</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">In the meantime, I should like to observe a minute’s silence, as a number of Members have requested, on behalf of all the victims concerned, particularly those of the terrible storms, in the various countries of the European Union.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Please rise, then, for this minute’s silence.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<!-- - lowercase text -->
<p>A final normalization case scenario involves changing converting all the text to lowercase. If the goal for the research is to count words at some point the fact that a word starts a sentence and by convention the first letter is capitalized will result distinct counts for words that are in essence the same (<em>i.e.</em> “In” vs.&nbsp;“in”).</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-normalize-lowercase-europarle_11b809ef97b940b77308a0301fab44d5">
<div class="cell-output-display">
<div id="tbl-normalize-lowercase-europarle" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.9: The Europarle dataset with lowercasing applied.</caption>
<colgroup>
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 92%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">sentence</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">i declare resumed the session of the european parliament adjourned on friday 17 december 1999, and i would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">declaro reanudado el período de sesiones del parlamento europeo, interrumpido el viernes 17 de diciembre pasado, y reitero a sus señorías mi deseo de que hayan tenido unas buenas vacaciones.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">although, as you will have seen, the dreaded ‘millennium bug’ failed to materialise, still the people in a number of countries suffered a series of natural disasters that truly were dreadful.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">como todos han podido comprobar, el gran “efecto del año 2000” no se ha producido. en cambio, los ciudadanos de varios de nuestros países han sido víctimas de catástrofes naturales verdaderamente terribles.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">you have requested a debate on this subject in the course of the next few days, during this part-session.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">sus señorías han solicitado un debate sobre el tema para los próximos días, en el curso de este período de sesiones.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">in the meantime, i should like to observe a minute’s silence, as a number of members have requested, on behalf of all the victims concerned, particularly those of the terrible storms, in the various countries of the european union.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">a la espera de que se produzca, de acuerdo con muchos colegas que me lo han pedido, pido que hagamos un minuto de silencio en memoria de todas las víctimas de las tormentas, en los distintos países de la unión europea afectados.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">please rise, then, for this minute’s silence.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">invito a todos a que nos pongamos de pie para guardar un minuto de silencio.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">madam president, on a point of order.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">señora presidenta, una cuestión de procedimiento.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">you will be aware from the press and television that there have been a number of bomb explosions and killings in sri lanka.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">sabrá usted por la prensa y la televisión que se han producido una serie de explosiones y asesinatos en sri lanka.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">one of the people assassinated very recently in sri lanka was mr kumar ponnambalam, who had visited the european parliament just a few months ago.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">una de las personas que recientemente han asesinado en sri lanka ha sido al sr. kumar ponnambalam, quien hace pocos meses visitó el parlamento europeo.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Note that lowercasing text, and normalization steps in general, can come at a cost. For example, lowercasing the Europarle dataset sentences means we lose potentially valuable information; namely the ability to identify proper names (<em>i.e.</em> “Mr Kumar Ponnambalam”) and titles (<em>i.e.</em> “European Parliament”) directly from the orthographic forms. There are, however, transformation steps that can be applied which aim to recover ‘lost’ information in situations such as this and others.</p>
</section><section id="recoding" class="level4"><h4 class="anchored" data-anchor-id="recoding">Recoding</h4>
<p>The process of recoding aims to <em>recast</em> the values of a variable or set of variables to a new variable or set of variables to enable more direct access. This may include extracting values from a variable, stemming or lemmatization of words, tokenization of linguistic forms (words, ngrams, sentences, <em>etc</em>.), calculating the lengths of linguistic units, removing variables that will not be used in the analysis, <em>etc</em>.</p>
<!-- - Stemming/ lemmatization  -->
<p>Words that we intuitively associate with a ‘base’ word can take many forms in language use. For example the word forms ‘investigation’, ‘investigation’, ‘investigate’, ‘investigated’, <em>etc</em>. are intuitively linked. There are two common methods that can be applied to create a new variable to facilitate the identification of these associations. The first is stemming. <strong>Stemming</strong> is a rule-based heuristic to reduce word forms to their stem or root form.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-recoding-stemming-brown-example_231a7c057b670041861a7e1a12ad305d">
<div class="cell-output-display">
<div id="tbl-recoding-stemming-brown-example" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.10: Results for stemming the first words in the Brown Corpus.</caption>
<thead><tr class="header">
<th style="text-align: left;">document_id</th>
<th style="text-align: left;">category</th>
<th style="text-align: left;">words</th>
<th style="text-align: left;">pos</th>
<th style="text-align: left;">word_stems</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">The</td>
<td style="text-align: left;">AT</td>
<td style="text-align: left;">The</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Fulton</td>
<td style="text-align: left;">NP</td>
<td style="text-align: left;">Fulton</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">County</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">Counti</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Grand</td>
<td style="text-align: left;">JJ</td>
<td style="text-align: left;">Grand</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Jury</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">Juri</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">said</td>
<td style="text-align: left;">VBD</td>
<td style="text-align: left;">said</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Friday</td>
<td style="text-align: left;">NR</td>
<td style="text-align: left;">Fridai</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">an</td>
<td style="text-align: left;">AT</td>
<td style="text-align: left;">an</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investig</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">of</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">of</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A few things to note here. First there are a number of stemming algorithms both for individual languages and distinct languages <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Second not all words can be stemmed as they do not have alternate morphological forms (<em>i.e.</em> “The”, “of”, <em>etc</em>.). This generally related to the distinction between closed-class (articles, prepositions, conjunctions, <em>etc</em>.) and open-class (nouns, verbs, adjectives, <em>etc</em>.) grammatical categories. Third the stem generated for those words that can be stemmed result in forms that are not words themselves. Nonetheless, stems can be very useful for more easily extracting a set of related word forms.</p>
<p>As an example, let’s identify all the word forms for the stem ‘investig’.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-recoding-stemming-brown-search_0db24ddaca774ab41a7fe3adb50f93ea">
<div class="cell-output-display">
<div id="tbl-recoding-stemming-brown-search" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.11: Results for filter word stems for “investig” in the Brown Corpus.</caption>
<thead><tr class="header">
<th style="text-align: left;">document_id</th>
<th style="text-align: left;">category</th>
<th style="text-align: left;">words</th>
<th style="text-align: left;">pos</th>
<th style="text-align: left;">word_stems</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investig</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigate</td>
<td style="text-align: left;">VB</td>
<td style="text-align: left;">investig</td>
</tr>
<tr class="odd">
<td style="text-align: left;">03</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investig</td>
</tr>
<tr class="even">
<td style="text-align: left;">03</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investig</td>
</tr>
<tr class="odd">
<td style="text-align: left;">07</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigations</td>
<td style="text-align: left;">NNS</td>
<td style="text-align: left;">investig</td>
</tr>
<tr class="even">
<td style="text-align: left;">07</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigate</td>
<td style="text-align: left;">VB</td>
<td style="text-align: left;">investig</td>
</tr>
<tr class="odd">
<td style="text-align: left;">08</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investig</td>
</tr>
<tr class="even">
<td style="text-align: left;">09</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investig</td>
</tr>
<tr class="odd">
<td style="text-align: left;">09</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigating</td>
<td style="text-align: left;">VBG</td>
<td style="text-align: left;">investig</td>
</tr>
<tr class="even">
<td style="text-align: left;">09</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investig</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We can see from the results in <a href="#tbl-recoding-stemming-brown-search">Table&nbsp;<span>2.11</span></a> that searching for <code>word_stems</code> that match ‘investig’ returns a set of stem-related forms. But it is worth noting that these forms cut across a number of grammatical categories. If instead you want to draw a distinction between grammatical categories, we can apply <strong>lemmatization.</strong> This process is distinct from stemming in two important ways: (1) inflectional forms are grouped by grammatical category and (2) the resulting forms are lemmas or ‘base’ forms of words.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-recoding-lemmatization-brown-example_cffd803b59717f02fc1d878053433950">
<div class="cell-output-display">
<div id="tbl-recoding-lemmatization-brown-example" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.12: Results for lemmatization of the first words in the Brown Corpus.</caption>
<thead><tr class="header">
<th style="text-align: left;">document_id</th>
<th style="text-align: left;">category</th>
<th style="text-align: left;">words</th>
<th style="text-align: left;">pos</th>
<th style="text-align: left;">word_lemmas</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">The</td>
<td style="text-align: left;">AT</td>
<td style="text-align: left;">The</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Fulton</td>
<td style="text-align: left;">NP</td>
<td style="text-align: left;">Fulton</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">County</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">County</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Grand</td>
<td style="text-align: left;">JJ</td>
<td style="text-align: left;">Grand</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Jury</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">Jury</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">said</td>
<td style="text-align: left;">VBD</td>
<td style="text-align: left;">say</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">Friday</td>
<td style="text-align: left;">NR</td>
<td style="text-align: left;">Friday</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">an</td>
<td style="text-align: left;">AT</td>
<td style="text-align: left;">a</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investigation</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">of</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">of</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>To appreciate the difference between stemming and lemmatization, let’s compare a filter for <code>word_lemmas</code> which match ‘investigation’.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-recoding-lemmatization-brown-investigation_cbf4e250e37fe0a069bd5a084f17569f">
<div class="cell-output-display">
<div id="tbl-recoding-lemmatization-brown-investigation" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.13: Results for filter word stems for “investigation” in the Brown Corpus.</caption>
<thead><tr class="header">
<th style="text-align: left;">document_id</th>
<th style="text-align: left;">category</th>
<th style="text-align: left;">words</th>
<th style="text-align: left;">pos</th>
<th style="text-align: left;">word_lemmas</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investigation</td>
</tr>
<tr class="even">
<td style="text-align: left;">03</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investigation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">03</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investigation</td>
</tr>
<tr class="even">
<td style="text-align: left;">07</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigations</td>
<td style="text-align: left;">NNS</td>
<td style="text-align: left;">investigation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">08</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investigation</td>
</tr>
<tr class="even">
<td style="text-align: left;">09</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investigation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">09</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investigation</td>
</tr>
<tr class="even">
<td style="text-align: left;">23</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investigation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">25</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investigation</td>
</tr>
<tr class="even">
<td style="text-align: left;">41</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">investigation</td>
<td style="text-align: left;">NN</td>
<td style="text-align: left;">investigation</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Only lemma forms of ‘investigate’ which are nouns appear. Let’s run a similar search but for the lemma ‘be’.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-recoding-lemmatization-brown-be_0a0eefbde48960f3e26fa4aae714c686">
<div class="cell-output-display">
<div id="tbl-recoding-lemmatization-brown-be" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.14: Results for filter word stems for “be” in the Brown Corpus.</caption>
<thead><tr class="header">
<th style="text-align: left;">document_id</th>
<th style="text-align: left;">category</th>
<th style="text-align: left;">words</th>
<th style="text-align: left;">pos</th>
<th style="text-align: left;">word_lemmas</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">was</td>
<td style="text-align: left;">BEDZ</td>
<td style="text-align: left;">be</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">been</td>
<td style="text-align: left;">BEN</td>
<td style="text-align: left;">be</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">was</td>
<td style="text-align: left;">BEDZ</td>
<td style="text-align: left;">be</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">was</td>
<td style="text-align: left;">BEDZ</td>
<td style="text-align: left;">be</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">are</td>
<td style="text-align: left;">BER</td>
<td style="text-align: left;">be</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">are</td>
<td style="text-align: left;">BER</td>
<td style="text-align: left;">be</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">be</td>
<td style="text-align: left;">BE</td>
<td style="text-align: left;">be</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">is</td>
<td style="text-align: left;">BEZ</td>
<td style="text-align: left;">be</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">was</td>
<td style="text-align: left;">BEDZ</td>
<td style="text-align: left;">be</td>
</tr>
<tr class="even">
<td style="text-align: left;">01</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">be</td>
<td style="text-align: left;">BE</td>
<td style="text-align: left;">be</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Again only words of the same grammatical category are returned. In this case the verb ‘be’ has many more inflectional forms than ‘investigate’.</p>
<!-- - Match and extract -->
<p>Another form of recoding is to detect a pattern in the values of an existing variable and create a new variable whose values are the extracted pattern or register that the pattern occurs and/ or how many times it occurs. As an example, let’s count the number of disfluencies (‘uh’ or ‘um’) that occur in each utterance in <code>utterance_text</code> from the Switchboard Dialog Act Corpus. <em>Note I’ve simplified the dataset dropping the non-relevant variables for this example.</em></p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-recoding-extract-switchboard_6cdc861fbe4349ca926ef94dbcc469a6">
<div class="cell-output-display">
<div id="tbl-recoding-extract-switchboard" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.15: Disfluency counts in the first 10 utterance text values from the Switchboard Corpus.</caption>
<colgroup>
<col style="width: 81%">
<col style="width: 18%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">utterance_text</th>
<th style="text-align: right;">disfluency_count</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Okay. /</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">{D So, }</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">[ [ I guess, +</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">What kind of experience [ do you, + do you ] have, then with child care? /</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I think, ] + {F uh, } I wonder ] if that worked. /</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Does it say something? /</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I think it usually does. /</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">You might try, {F uh, } /</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I don’t know, /</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">hold it down a little longer, /</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<!-- - Tokenization -->
<p>One of the most common forms of recoding in text analysis is tokenization. <strong>Tokenization</strong> is the process of recasting the text into smaller linguistic units. When working with text that has not been linguistically annotated, the most feasible linguistic tokens are words, ngrams, and sentences. While word and sentence tokens are easily understandable, ngram tokens need some explanation. An <strong>ngram</strong> is a sequence of either characters or words where <em>n</em> is the length of this sequence. The ngram sequences are drawn incrementally, so the bigrams (two-word sequences) for the sentence “This is an input sentence.” are:</p>
<p>this is, is an, an input, input sentence</p>
<p>We’ve already seen word tokenization exemplified with the Europarle Corpus in subsection <a href="#structure">Structure</a> in <a href="#tbl-tidy-words-europarle">Table&nbsp;<span>2.4</span></a>, so let’s create (word) bigram tokens for this corpus.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-recoding-tokenization-europarle-bigram-words_da04fa08781696340cc1dc3a8b65ce57">
<div class="cell-output-display">
<div id="tbl-recoding-tokenization-europarle-bigram-words" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.16: The first 10 word bigrams of the Europarle Corpus.</caption>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">word_bigrams</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">i declare</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">declare resumed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">resumed the</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">the session</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">session of</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">of the</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">the european</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">european parliament</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">parliament adjourned</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">adjourned on</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>As I just mentioned, ngrams sequences can be formed of characters as well. Here are character trigram (three-character) sequences.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-recoding-tokenization-europarle-trigram-chars_cb2660265f8aab54dd45bf4943a69d24">
<div class="cell-output-display">
<div id="tbl-recoding-tokenization-europarle-trigram-chars" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.17: The first 10 character trigrams of the Europarle Corpus.</caption>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">char_trigrams</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">ide</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">dec</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">ecl</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">cla</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">lar</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">are</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">rer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">ere</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">res</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">esu</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section><section id="generation" class="level4"><h4 class="anchored" data-anchor-id="generation">Generation</h4>
<p>The process of generation aims to <em>augment</em> a variable or set of variables. In essence this aims to make implicit attributes explicit to that they are directly accessible. This often targeted at the automatic generation of linguistic annotations such as grammatical category (part-of-speech) or syntactic structure.</p>
<!-- - Linguistic annotation (part of speech, syntactic structure) -->
<p>In the examples below I’ve added linguistic annotation to a target (English) and source (Spanish) example sentence from the Europarle Parallel Corpus. First, note the variables that are added to our dataset that correspond to grammatical category. In addition to the <code>type</code> and <code>sentence_id</code> we have an assortment of variables which replace the <code>sentence</code> variable. As part of the process of annotation the input text to be annotated <code>sentence</code> is tokenized <code>token</code> and indexed <code>token_id</code>. Then <code>upos</code> contains the Universal Part of Speech tags<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, and a detailed list of features is included in <code>feats</code>. The syntactic annotation is reflected in the <code>token_id_source</code> and <code>syntactic_relation</code> variables. These variables correspond to the type of syntactic parsing that has been done, in this case Dependency Parsing (using the <a href="https://universaldependencies.org/">Universal Dependencies</a> framework). Another common syntactic parsing framework is phrase constituency parsing <span class="citation" data-cites="Jurafsky2020">(<a href="references.html#ref-Jurafsky2020" role="doc-biblioref">Jurafsky and Martin 2020</a>)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-generation-europarle-en-example_2ea783cd257de62a2c0da73a4bc5a28a">
<div class="cell-output-display">
<div id="tbl-generation-europarle-en-example" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.18: Automatic linguistic annotation for grammatical category and syntactic structure for an example English sentence from the Europarle Corpus.</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 28%">
<col style="width: 14%">
<col style="width: 17%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">token_id</th>
<th style="text-align: left;">token</th>
<th style="text-align: left;">upos</th>
<th style="text-align: left;">feats</th>
<th style="text-align: left;">token_id_source</th>
<th style="text-align: left;">syntactic_relation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">Invito</td>
<td style="text-align: left;">ADP</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">case</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">a</td>
<td style="text-align: left;">DET</td>
<td style="text-align: left;">Definite=Ind|PronType=Art</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">det</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">todos</td>
<td style="text-align: left;">NOUN</td>
<td style="text-align: left;">Number=Plur</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">nmod</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">a</td>
<td style="text-align: left;">DET</td>
<td style="text-align: left;">Definite=Ind|PronType=Art</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">det</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">que</td>
<td style="text-align: left;">ADJ</td>
<td style="text-align: left;">Degree=Pos</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">amod</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">nos</td>
<td style="text-align: left;">NOUN</td>
<td style="text-align: left;">Number=Plur</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">root</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">pongamos</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">goeswith</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">de</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">Foreign=Yes</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">goeswith</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">pie</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">goeswith</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">para</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">goeswith</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">guardar</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">goeswith</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">un</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">goeswith</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">minuto</td>
<td style="text-align: left;">NOUN</td>
<td style="text-align: left;">Number=Sing</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">appos</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">de</td>
<td style="text-align: left;">PROPN</td>
<td style="text-align: left;">Number=Sing</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">compound</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">silencio</td>
<td style="text-align: left;">PROPN</td>
<td style="text-align: left;">Number=Sing</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">flat</td>
</tr>
<tr class="even">
<td style="text-align: left;">Target</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">.</td>
<td style="text-align: left;">PUNCT</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">punct</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Now compare the English example sentence dataset in <a href="#tbl-generation-europarle-en-example">Table&nbsp;<span>2.18</span></a> with the parallel sentence in Spanish. Note that the grammatical features are language specific. For example, Spanish has gender which is apparent when scanning the <code>feats</code> variable.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-generation-europarle-es-example_91e13eaa1f995181d3f4f01e69bfab88">
<div class="cell-output-display">
<div id="tbl-generation-europarle-es-example" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.19: Automatic linguistic annotation for grammatical category and syntactic structure for an example Spanish sentence from the Europarle Corpus.</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 48%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">sentence_id</th>
<th style="text-align: left;">token_id</th>
<th style="text-align: left;">token</th>
<th style="text-align: left;">upos</th>
<th style="text-align: left;">feats</th>
<th style="text-align: left;">token_id_source</th>
<th style="text-align: left;">syntactic_relation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">Please</td>
<td style="text-align: left;">PROPN</td>
<td style="text-align: left;">Gender=Fem|Number=Sing</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">nsubj</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">rise</td>
<td style="text-align: left;">PROPN</td>
<td style="text-align: left;">Number=Sing</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">flat</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">,</td>
<td style="text-align: left;">PUNCT</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">punct</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">then</td>
<td style="text-align: left;">VERB</td>
<td style="text-align: left;">Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">root</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">,</td>
<td style="text-align: left;">PUNCT</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">punct</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">for</td>
<td style="text-align: left;">ADP</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">compound</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">this</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">compound</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">minute’s</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">Gender=Masc|Number=Sing</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">compound</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">silence</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">Gender=Masc|Number=Sing</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">conj</td>
</tr>
<tr class="even">
<td style="text-align: left;">Source</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">.</td>
<td style="text-align: left;">PUNCT</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">punct</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>There is much more to explore with linguistic annotation, and syntactic parsing in particular, but at this point it will suffice to note that it is possible to augment a dataset with grammatical information automatically.</p>
<p>There are strengths and shortcomings with automatic linguistic annotation that a research should be aware of. First, automatic linguistic annotation provides quick access to rich and highly reliable linguistic information for a large number of languages. However, part-of-speech taggers and syntactic parsers are not magic. They are resources that are built by training a computational algorithm to recognize patterns in manually annotated datasets producing a language model. This model is then used to predict the linguistic annotations for new language (as we just did in the previous examples). The shortcomings of automatic linguistic annotation is first, not all languages have trained language models and second, the data used to train the model inevitably reflect a particular variety, register, modality, <em>etc</em>. The accuracy of the linguistic annotation is highly dependent on alignment between the language sampling frame of the trained data and the language data to be automatically annotated. Many (most) of the language models available for automatic linguistic annotation are based on language that is most readily available and for most languages this has traditionally been newswire text. It is important to be aware of these characteristics when using linguistic annotation tools.</p>
<!-- *Consider adding 'creating measures' here* -->
</section><section id="merging" class="level4"><h4 class="anchored" data-anchor-id="merging">Merging</h4>
<p>The process of merging aims to <em>join</em> a variable or set of variables with another variable or set of variables from another dataset. The option to merge two (or more) datasets requires that there is a shared variable that indexes and aligns the datasets.</p>
<p>To provide an example let’s look at the Switchboard Diaglog Act Corpus. Our existing, disfluency recoded, version includes the following variables.</p>
<!-- - Join other information with the dataset -->
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/merging-swda-disfluencies_01d0a2761470a35bb3b7b4ba9ddab5a8">
<div class="cell-output cell-output-stdout">
<pre><code>&gt; Rows: 5
&gt; Columns: 11
&gt; $ doc_id           &lt;chr&gt; "4325", "4325", "4325", "4325", "4325"
&gt; $ speaker_id       &lt;dbl&gt; 1632, 1632, 1519, 1632, 1519
&gt; $ topic_num        &lt;dbl&gt; 323, 323, 323, 323, 323
&gt; $ topicality       &lt;chr&gt; "3", "3", "3", "3", "3"
&gt; $ naturalness      &lt;chr&gt; "2", "2", "2", "2", "2"
&gt; $ damsl_tag        &lt;chr&gt; "o", "qw", "qy^d", "+", "+"
&gt; $ speaker          &lt;chr&gt; "A", "A", "B", "A", "B"
&gt; $ turn_num         &lt;chr&gt; "1", "1", "2", "3", "4"
&gt; $ utterance_num    &lt;chr&gt; "1", "2", "1", "1", "1"
&gt; $ utterance_text   &lt;chr&gt; "Okay.  /", "{D So, }", "[ [ I guess, +", "What kind …
&gt; $ disfluency_count &lt;int&gt; 0, 0, 0, 0, 1</code></pre>
</div>
</div>
<p>It turns out that on the <a href="https://catalog.ldc.upenn.edu/docs/LDC97S62/">corpus website</a> a number of meta-data files are available, including files pertaining to speakers and the topics of the conversations.</p>
<p>The speaker meta-data for this corpus is in a the <code>caller_tab.csv</code> file and contains a <code>speaker_id</code> variable which corresponds to each speaker in the corpus and other potentially relevant variables for a language research project including <code>sex</code>, <code>birth_year</code>, <code>dialect_area</code>, and <code>education</code>.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-merging-swda-speaker_f06b6231a73ec7d4ca4802177ebb326b">
<div class="cell-output-display">
<div id="tbl-merging-swda-speaker" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.20: Speaker meta-data for the Switchboard Dialog Act Corpus.</caption>
<thead><tr class="header">
<th style="text-align: right;">speaker_id</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">birth_year</th>
<th style="text-align: left;">dialect_area</th>
<th style="text-align: right;">education</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1632</td>
<td style="text-align: left;">FEMALE</td>
<td style="text-align: right;">1962</td>
<td style="text-align: left;">WESTERN</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">1632</td>
<td style="text-align: left;">FEMALE</td>
<td style="text-align: right;">1962</td>
<td style="text-align: left;">WESTERN</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1519</td>
<td style="text-align: left;">FEMALE</td>
<td style="text-align: right;">1971</td>
<td style="text-align: left;">SOUTH MIDLAND</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1632</td>
<td style="text-align: left;">FEMALE</td>
<td style="text-align: right;">1962</td>
<td style="text-align: left;">WESTERN</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1519</td>
<td style="text-align: left;">FEMALE</td>
<td style="text-align: right;">1971</td>
<td style="text-align: left;">SOUTH MIDLAND</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Since both datasets contain a shared index, <code>speaker_id</code> we can merge these two datasets. The result is found in <a href="#tbl-merging-swda-speaker-added">Table&nbsp;<span>2.21</span></a>.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/tbl-merging-swda-speaker-added_9c65529a2b6943019964759900f3c70a">
<div class="cell-output-display">
<div id="tbl-merging-swda-speaker-added" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.21: Merged conversations and speaker meta-data for the Switchboard Dialog Act Corpus.</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 33%">
<col style="width: 7%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">doc_id</th>
<th style="text-align: right;">speaker_id</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">birth_year</th>
<th style="text-align: left;">dialect_area</th>
<th style="text-align: right;">education</th>
<th style="text-align: right;">topic_num</th>
<th style="text-align: left;">topicality</th>
<th style="text-align: left;">naturalness</th>
<th style="text-align: left;">damsl_tag</th>
<th style="text-align: left;">speaker</th>
<th style="text-align: left;">turn_num</th>
<th style="text-align: left;">utterance_num</th>
<th style="text-align: left;">utterance_text</th>
<th style="text-align: right;">disfluency_count</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">4325</td>
<td style="text-align: right;">1632</td>
<td style="text-align: left;">FEMALE</td>
<td style="text-align: right;">1962</td>
<td style="text-align: left;">WESTERN</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">323</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">o</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">Okay. /</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">4325</td>
<td style="text-align: right;">1632</td>
<td style="text-align: left;">FEMALE</td>
<td style="text-align: right;">1962</td>
<td style="text-align: left;">WESTERN</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">323</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">qw</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">{D So, }</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4325</td>
<td style="text-align: right;">1519</td>
<td style="text-align: left;">FEMALE</td>
<td style="text-align: right;">1971</td>
<td style="text-align: left;">SOUTH MIDLAND</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">323</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">qy^d</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">[ [ I guess, +</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">4325</td>
<td style="text-align: right;">1632</td>
<td style="text-align: left;">FEMALE</td>
<td style="text-align: right;">1962</td>
<td style="text-align: left;">WESTERN</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">323</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">+</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">What kind of experience [ do you, + do you ] have, then with child care? /</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4325</td>
<td style="text-align: right;">1519</td>
<td style="text-align: left;">FEMALE</td>
<td style="text-align: right;">1971</td>
<td style="text-align: left;">SOUTH MIDLAND</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">323</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">+</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">I think, ] + {F uh, } I wonder ] if that worked. /</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In this example case the dataset that was merged was already in a structured format (.csv). Many corpus resources contain meta-data in stand-off files that are structured.</p>
<p>In some cases a researcher would like to merge information that does not already accompany the corpus resource. This is possible as long as a dataset can be created that contains a variable that is shared. Without a shared variable to index the datasets the merge cannot take place.</p>
<p>In sum, the transformation steps described here collectively aim to produce higher quality datasets that are relevant in content and structure to submit to analysis. The process may include one or more of the previous transformations but is rarely linear and is most often iterative. It is typical to do some normalization then generation, then recoding, and then return to normalizing, and so forth. This process is highly idiosyncratic given the characteristics of the derived dataset and the ultimate goals for the analysis dataset.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note in some cases we may convert our tidy tabular dataset to other data formats that may be required for some particular statistic approaches but at all times the relationship between the variables should be maintained in line with our research purpose. We will touch on examples of other types of data formats (<em>e.g.</em> Corpus and Document-Term Matrix (DTM) objects in R) when we dive into particular statistical approaches that require them later in the textbook.</p>
</div>
</div>
</section></section></section><section id="documentation" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="documentation">
<span class="header-section-number">2.3</span> Documentation</h2>
<section id="data-origin-information" class="level3" data-number="2.3.1"><h3 data-number="2.3.1" class="anchored" data-anchor-id="data-origin-information">
<span class="header-section-number">2.3.1</span> Data origin information</h3>
<!--  
- [ ] Include data origin information: source, date, version, license, permissions, attribution, etc.
- [ ] Emphasize 'read-only' nature of acquired corpus data/ datasets
-->
</section><section id="data-dictionaries" class="level3" data-number="2.3.2"><h3 data-number="2.3.2" class="anchored" data-anchor-id="data-dictionaries">
<span class="header-section-number">2.3.2</span> Data dictionaries</h3>
<!--  
- [ ] Point out curation and transformation steps are documented in code and in prose (README.md, or other?)
-->
<p>As we have seen in this chapter that acquiring data and converting that data into information involves a number of conscious decisions and implementation steps. As a favor to ourselves as researchers and to the research community, it is crucial to document these decisions and steps. This makes it both possible to retrace our own steps and also provides a guide for future researchers that want to reproduce and/ or build on your research. A programmatic approach to quantitative research helps ensure that the implementation steps are documented and reproducible but it is also vital that the decisions that are made are documented as well. This includes the creation/ selection of the corpus data, the description of the variables chosen from the corpus for the derived dataset, and the description of the variables created from the derived dataset for the analysis dataset.</p>
<p>For an existing corpus sample acquired from a repository (<em>e.g.</em> <a href="https://catalog.ldc.upenn.edu/LDC97S62">Switchboard Dialog Act Corpus</a>, Language Data Consortium), a research group (<em>e.g.</em> <a href="http://cedel2.learnercorpora.com/">CEDEL2</a>), or an individual researcher (<em>e.g.</em> <a href="https://www.dt.fee.unicamp.br/~tiago/smsspamcollection/">SMS Spam Collection</a>), there is often documentation provided describing key attributes of the resource. This documentation should be included with the acquisition of the corpus and added to the research project. For a corpus that a researcher compiles themselves, they will need to generate this documentation.</p>
<p>The curation and transformation steps conducted on the original corpus data to produce the datasets should also be documented. The steps themselves can be included in the programming scripts as code comments (or in prose if using a literate programming strategy (<em>e.g.</em> R Markdown)). The structure of each resulting dataset should include what is called a <strong>data dictionary</strong>. This is a table which includes the variable names, the values they contain, and a short prose description of each variable (<em>e.g.</em> <a href="https://osf.io/9jafz/">ACTIV-ES Corpus</a>).</p>
<!-- 
- Selecting or developing a corpus
  - if you develop a corpus you should document your procedure, including the sampling frame
  - by the same token, selecting a corpus requires that you consult the corpus documentation and vet the resources for its potential to be a viable research resource
  - include the __corpus documentation__
  
- Depending on the original structure of a corpus and the goals of the research, the data will need human intervention to create a tabular structure which provides the base physical form which makes explicit the semantic relationships between the variables of primary interest
  - this is a derived dataset, it serves as the base dataset for a research project. 
  - include the __derived dataset documentation__
  
- With an eye towards the method of analysis many times there will additional transformations necessary
  - this may include variable normalization, variable recoding, or the creation or incorporation of new variables (linguistic and/ or non-linguistic) which bring the dataset inline with the goals of the research
  - include the __analysis dataset documentation__


- Acquired data: original corpus (reference to the source)
- Curated data: derived dataset (description of the relational structure/ variables)
- Transformed data: analysis dataset (description of the procedures to prepare for analysis)
-->
</section></section><section id="summary" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<p>In this chapter we have focused on data and information –the first two components of DIKI Hierarchy. This process is visualized in <a href="#fig-understanding-data-vis-sum">Figure&nbsp;<span>2.4</span></a>.</p>
<div class="cell" data-layout-align="center" data-hash="understanding-data_cache/html/fig-understanding-data-vis-sum_1a22621a2a1e35d5c225a123c156abb4">
<div class="cell-output-display">
<div id="fig-understanding-data-vis-sum" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="figures/understanding-data/ud-diki.drawio.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2.4: Understanding data: visual summary</figcaption></figure>
</div>
</div>
</div>
<p>First a distinction is made between populations and samples, the latter being a intentional and subjective selection of observations from the world which attempt to represent the population of interest. The result of this process is known as a corpus. Whether developing a corpus or selecting an existing a corpus it is important to vet the sampling frame for its applicability and viability as a resource for a given research project.</p>
<p>Once a viable corpus is identified, then that corpus is converted into a derived dataset which adopts the tidy dataset format where each column is a variable, each row is an observation, and the intersection of columns and rows contain values. This derived dataset serves to establish the base informational relationships from which your research will stem.</p>
<p>The derived dataset will most likely require transformations including normalization, recoding, generation, and/ or merging to enhance the usefulness of the information to analysis. An analysis dataset is the result of this process.</p>
<p>Finally, documentation should be implemented at each stage of the analysis project process. Employing a programmatic approach establishes documentation of the implementation steps but the motivation behind the decisions taken and the content of the corpus data and datasets generated also need documentation to ensure transparent and reproducible research.</p>
</section><section id="activities" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="activities">Activities</h2>
<ul class="task-list">
<li>
<input type="checkbox">Add summary of the purpose, goals, outcomes of these activities</li>
</ul>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-regular fa-file-code" aria-label="file-code"></i> Recipe</strong></p>
<p><strong>What</strong>: <a href="https://qtalr.github.io/qtalrkit/articles/recipe-2.html">Reading, inspecting, and writing data</a><br><strong>How</strong>: Read Recipe 2 and participate in the Hypothes.is online social annotation.<br><strong>Why</strong>: To use literate programming in Quarto to work with R coding strategies for reading, inspecting, and writing datasets.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><i class="fa-solid fa-flask" aria-label="flask"></i> Lab</strong></p>
<p><strong>What</strong>: <a href="https://github.com/qtalr/lab-2">Reading, inspecting, and writing data</a><br><strong>How</strong>: Clone, fork, and complete the steps in Lab 2.<br><strong>Why</strong>: To read datasets from packages and from plain-text files, inspect and report characteristics of datasets, and write datasets to plain-text files.</p>
</div>
</div>
</div>
</section><section id="questions" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="questions">Questions</h2>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Conceptual questions</strong></p>
<ol type="1">
<li><p>What is the difference between a population and a sample in linguistic research?</p></li>
<li><p>Why is it important to vet a corpus before using it in a research project?</p></li>
<li><p>What is a derived dataset in the context of linguistic research?</p></li>
<li><p>How does the tidy table format help with linguistic analysis?</p></li>
<li><p>What kinds of transformations may be performed on a derived dataset to enhance its usefulness for analysis?</p></li>
<li><p>What is an analysis dataset and why is it important in linguistic research?</p></li>
<li><p>Why is documentation important in the process of conducting linguistic analysis?</p></li>
<li><p>How does a programmatic approach enhance documentation in linguistic research?</p></li>
<li><p>Why is it important to document the motivation behind decisions taken in linguistic analysis projects?</p></li>
<li><p>How does documenting the corpus data and generated datasets contribute to transparent and reproducible research in linguistics?</p></li>
</ol>
<hr>
<p>To add:</p>
<ul>
<li>What is the difference between a variable and a value?</li>
<li>Why is it important to identify the levels of measurement of variables in a dataset?</li>
<li>What is the difference between the unit of analysis and the unit of observation?</li>
<li>How does the unit of analysis and the unit of observation relate to the levels of measurement of variables in a dataset?</li>
<li>In what ways can a dataset be considered a model of the world?</li>
<li>To what extent does the sample represent the population? What implications does this have for the generalizability of the results of a research project?</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Technical questions</strong></p>
<!-- Compare with the swirl, recipe, and lab exercises. -->
<ol type="1">
<li>Creating a Sample Corpus:</li>
<li>Writing a Corpus Documentation</li>
<li>Converting a Corpus to a Derived Dataset:</li>
<li>Writing a Data Dictionary</li>
<li>Transforming a Derived Dataset:</li>
<li>Merging Datasets:</li>
<li>Writing a dataset to disk</li>
<li>Consider (an example dataset) and its data dictionary, write a script to read the dataset, inspect it, and write it to disk.</li>
<li>Consider a dataset and its data dictionary what appears to be the unit of analysis and the unit of observation?</li>
</ol>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Adel2020" class="csl-entry" role="listitem">
Ädel, Annelie. 2020. <span>“Corpus Compilation.”</span> In <em>A Practical Handbook of Corpus Linguistics</em>, edited by Magali Paquot and Stefan Th. Gries, 3–24. Switzerland: Springer.
</div>
<div id="ref-Grieve2018" class="csl-entry" role="listitem">
Grieve, Jack, Andrea Nini, and Diansheng Guo. 2018. <span>“Mapping Lexical Innovation on American Social Media.”</span> <em>Journal of English Linguistics</em> 46 (4): 293–319.
</div>
<div id="ref-Jurafsky2020" class="csl-entry" role="listitem">
Jurafsky, Daniel, and James H. Martin. 2020. <em>Speech and Language Processing</em>.
</div>
<div id="ref-Kucera1967" class="csl-entry" role="listitem">
Kucera, H, and W N Francis. 1967. <em>Computational Analysis of Present Day American English</em>. Brown University Press Providence.
</div>
<div id="ref-Wickham2014a" class="csl-entry" role="listitem">
Wickham, Hadley. 2014. <span>“Tidy Data.”</span> <em>Journal of Statistical Software</em> 59 (10). <a href="https://doi.org/10.18637/jss.v059.i10">https://doi.org/10.18637/jss.v059.i10</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>https://snowballstem.org/algorithms/<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><a href="https://universaldependencies.org/u/pos/">Descriptions of the UPOS tagset</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./foundations.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Foundations</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./approaching-analysis.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Approaching analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>